package com.wethaq.app;

import android.app.*;
import android.content.*;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public final class AdminAccessActivity extends Activity {
    private static final String API="https://wethaq-backend-production.up.railway.app";
    private SharedPreferences prefs;
    private LinearLayout root,content;
    private String adminToken="", selectedUserId="", selectedAssignmentId="", selectedRole="";
    private String currentRole="";
    private JSONObject roleJson=new JSONObject(), capabilities=new JSONObject();
    private EditText targetName,targetBirth;
    private TextView targetStatus;
    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private int gold(){return Color.rgb(212,175,55);}
    private TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(12),dp(10),dp(12),dp(10));return t;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setTextSize(17);e.setSingleLine(true);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setPadding(dp(14),0,dp(14),0);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(24,24,27));d.setCornerRadius(dp(14));d.setStroke(dp(2),Color.rgb(75,75,80));e.setBackground(d);e.setMinHeight(dp(62));return e;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(17);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setStateListAnimator(null);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(28,28,32));d.setCornerRadius(dp(14));d.setStroke(dp(2),gold());b.setBackground(d);b.setMinHeight(dp(62));return b;}
    private LinearLayout card(String title){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(14));GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(22,22,25));d.setCornerRadius(dp(18));d.setStroke(dp(2),gold());box.setBackground(d);TextView h=tv(title,20,gold());h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setGravity(Gravity.CENTER);box.addView(h,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);box.setLayoutParams(p);return box;}
    private void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(14));root.setBackgroundColor(Color.BLACK);TextView h=tv(title,22,gold());h.setGravity(Gravity.CENTER);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(h,new LinearLayout.LayoutParams(-1,dp(68)));ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("wethaq",MODE_PRIVATE);adminToken=prefs.getString("admin_token","");if(isOwner()&&adminToken.isEmpty()){founderSession();}else if(!adminToken.isEmpty()){loadRole();}else{showAdminLogin();}}
    private boolean isOwner(){return "Hatem_Hussin_Al_Haj_Ramadan1995".equals(prefs.getString("wethaq_id",""));}
    private void founderSession(){String identityToken=prefs.getString("token","");if(identityToken.length()<10){showAdminLogin();return;}request("POST","/api/admin/founder-code",null,identityToken,r->{try{String code=new JSONObject(r).getString("adminCode");JSONObject q=new JSONObject();q.put("name",prefs.getString("name",""));q.put("birthYear",Integer.parseInt(prefs.getString("birth_year","0")));q.put("adminCode",code);request("POST","/api/admin/login",q.toString(),null,login->{try{JSONObject a=new JSONObject(login);adminToken=a.getString("token");prefs.edit().putString("admin_token",adminToken).putString("admin_role","founder").apply();loadRole();}catch(Exception e){showAdminLogin();}});}catch(Exception e){showAdminLogin();}});}
    private void showAdminLogin(){base("🔐 الدخول إلى لوحة الإدارة — وَثاق");content.addView(tv("الدخول بالاسم وسنة الميلاد ورمز المنصب السري.",16,Color.WHITE));EditText n=field("الاسم الثلاثي"),y=field("سنة الميلاد"),c=field("الرمز السري للمنصب");y.setInputType(InputType.TYPE_CLASS_NUMBER);c.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(n);content.addView(y);content.addView(c);Button l=btn("🔐 دخول لوحة المنصب"),back=btn("رجوع");content.addView(l);content.addView(back);l.setOnClickListener(v->adminLogin(n.getText().toString().trim(),y.getText().toString().trim(),c.getText().toString().trim()));back.setOnClickListener(v->finish());}
    private void adminLogin(String n,String y,String c){if(n.split("\\s+").length<3){toast("اكتب الاسم الثلاثي");return;}try{JSONObject q=new JSONObject();q.put("name",n);q.put("birthYear",Integer.parseInt(y));q.put("adminCode",c);request("POST","/api/admin/login",q.toString(),null,r->{try{JSONObject z=new JSONObject(r);adminToken=z.getString("token");prefs.edit().putString("admin_token",adminToken).putString("admin_role",z.optString("role")).apply();loadRole();}catch(Exception e){toast("بيانات الدخول غير صحيحة");}});}catch(Exception e){toast("سنة الميلاد غير صحيحة");}}
    private void loadRole(){request("GET","/api/admin/role",null,adminToken,r->{try{roleJson=new JSONObject(r);currentRole=roleJson.optString("role","");buildCapabilities(roleJson);showPanel(roleJson);}catch(Exception e){prefs.edit().remove("admin_token").remove("admin_role").apply();adminToken="";if(isOwner())founderSession();else showAdminLogin();}});}
    private void buildCapabilities(JSONObject z){capabilities=new JSONObject();try{JSONArray p=z.optJSONArray("permissions");Set<String>s=new HashSet<>();if(p!=null)for(int i=0;i<p.length();i++)s.add(p.optString(i));boolean founder="founder".equals(currentRole);boolean senior=founder||"executive".equals(currentRole)||"deputy1".equals(currentRole)||"deputy2".equals(currentRole)||"deputy3".equals(currentRole)||"supervisor".equals(currentRole);boolean appoint=s.contains("تعيين وإزالة المناصب")||s.contains("تعيين أعضاء الإدارة")||s.contains("تعيين 3 أعضاء إدارة")||s.contains("تعيين أعضاء مميزين")||s.contains("تعيين أعضاء مميزين ضمن الحد");capabilities.put("manageUsers",founder||senior||s.contains("الحظر المؤقت للمستخدمين"));capabilities.put("assign",founder||appoint);capabilities.put("viewStructure",founder||senior||s.contains("عرض الإدارة"));capabilities.put("viewAudit",founder);capabilities.put("banTemporary",founder||s.contains("الحظر ضمن النطاق")||s.contains("الحظر المؤقت للمستخدمين"));capabilities.put("banPermanent",founder);capabilities.put("warn",founder||s.contains("التحذير والتنبيهات")||s.contains("التحذير"));capabilities.put("unban",founder||s.contains("الحظر ضمن النطاق"));capabilities.put("removeRole",founder||s.contains("تعيين وإزالة المناصب"));}catch(Exception ignored){}}
    private boolean can(String k){return capabilities.optBoolean(k,false);}
    private void showPanel(JSONObject role){String label=role.optString("label",currentRole),icon=role.optString("icon","");base(icon+" لوحة "+label+" — وَثاق");double fee=role.optDouble("fee",-1);String expiry=role.optString("subscriptionExpiresAt","");StringBuilder head=new StringBuilder("المنصب: ").append(icon).append(' ').append(label).append("\n");if(fee>=0)head.append("الاشتراك السنوي: ").append(fee).append(" دولار\n");else head.append("رسوم المنصب: بدون اشتراك للمؤسس\n");if(!expiry.isEmpty())head.append("انتهاء الاشتراك: ").append(expiry);else if(fee>=0)head.append("مدة الاشتراك: سنة واحدة");content.addView(tv(head.toString(),17,Color.WHITE));
        if(can("manageUsers"))addUserControlCard();
        if(can("assign"))addAssignmentCard(role);
        if(can("viewStructure")&&!can("viewAudit"))addStructureCard();
        if(can("viewAudit"))addAuditCards();
        if(!can("manageUsers")&&!can("assign")&&!can("viewStructure")&&!can("viewAudit"))content.addView(card("🔒 الصلاحيات الحالية\n"+permissionsText(role)));Button logout=btn("🚪 خروج من لوحة المنصب");content.addView(logout);logout.setOnClickListener(v->{prefs.edit().remove("admin_token").remove("admin_role").apply();adminToken="";finish();});}
    private String permissionsText(JSONObject role){try{JSONArray a=role.optJSONArray("permissions");StringBuilder s=new StringBuilder();if(a!=null)for(int i=0;i<a.length();i++)s.append("• ").append(a.optString(i)).append('\n');return s.length()==0?"لا توجد صلاحيات إضافية.":s.toString();}catch(Exception e){return "تعذر قراءة الصلاحيات.";}}
    private void addUserControlCard(){LinearLayout box=card("🛡 بطاقة الحظر والتنبيهات وإدارة المستخدمين");targetName=field("الاسم الثلاثي للمستخدم");targetBirth=field("سنة الميلاد");targetBirth.setInputType(InputType.TYPE_CLASS_NUMBER);box.addView(targetName);box.addView(targetBirth);Button find=btn("🔎 بحث واختيار المستخدم");box.addView(find);targetStatus=tv("لم يتم اختيار مستخدم.",15,Color.WHITE);box.addView(targetStatus);LinearLayout r1=new LinearLayout(this);r1.setOrientation(LinearLayout.HORIZONTAL);Button temp=btn("حظر مؤقت"),per=btn("حظر دائم");temp.setEnabled(can("banTemporary"));per.setEnabled(can("banPermanent"));r1.addView(temp,new LinearLayout.LayoutParams(0,dp(64),1));r1.addView(per,new LinearLayout.LayoutParams(0,dp(64),1));box.addView(r1);LinearLayout r2=new LinearLayout(this);r2.setOrientation(LinearLayout.HORIZONTAL);Button warn=btn("تنبيه"),unban=btn("إزالة حظر");warn.setEnabled(can("warn"));unban.setEnabled(can("unban"));r2.addView(warn,new LinearLayout.LayoutParams(0,dp(64),1));r2.addView(unban,new LinearLayout.LayoutParams(0,dp(64),1));box.addView(r2);if(can("removeRole")){Button remove=btn("🗑 إزالة المنصب الإداري");box.addView(remove);remove.setOnClickListener(v->removeTargetRole());}find.setOnClickListener(v->findTarget());temp.setOnClickListener(v->temporaryBanDialog());per.setOnClickListener(v->banTarget(0));warn.setOnClickListener(v->warnTarget());unban.setOnClickListener(v->unbanTarget());content.addView(box);}
    private void findTarget(){String q=targetName.getText().toString().trim();if(q.length()<2){toast("أدخل الاسم الثلاثي ثم ابحث");return;}request("GET","/api/admin/users?q="+enc(q),null,adminToken,r->{try{JSONArray a=new JSONObject(r).optJSONArray("users");if(a==null||a.length()==0){selectedUserId="";targetStatus.setText("❌ لم يتم العثور على المستخدم");return;}JSONObject u=a.getJSONObject(0);selectedUserId=u.optString("wethaq_id");targetName.setText(u.optString("name"));targetBirth.setText(u.optString("birth_year"));JSONObject ban=u.optJSONObject("ban");targetStatus.setText("👤 "+u.optString("name")+"\n🆔 "+selectedUserId+"\nالحالة: "+(ban==null?"نشط":"محظور"));}catch(Exception e){toast("تعذر قراءة المستخدم");}});}
    private void temporaryBanDialog(){if(!can("banTemporary")){toast("الحظر المؤقت غير متاح");return;}EditText m=field("مدة الحظر بالدقائق");m.setInputType(InputType.TYPE_CLASS_NUMBER);new AlertDialog.Builder(this).setTitle("حظر مؤقت").setView(m).setPositiveButton("تنفيذ",(d,w)->{try{int x=Integer.parseInt(m.getText().toString().trim());if(x<=0)throw new Exception();banTarget(x);}catch(Exception e){toast("أدخل مدة صحيحة");}}).setNegativeButton("إلغاء",null).show();}
    private void banTarget(int minutes){if(selectedUserId.isEmpty()){toast("اختر المستخدم أولًا");return;}if(minutes==0&&!can("banPermanent")){toast("الحظر الدائم غير متاح");return;}if(minutes>0&&!can("banTemporary")){toast("الحظر المؤقت غير متاح");return;}try{JSONObject q=new JSONObject();q.put("wethaqId",selectedUserId);q.put("minutes",minutes);q.put("reason",minutes>0?"حظر مؤقت بقرار إداري":"حظر دائم بقرار إداري");request("POST","/api/admin/rbac/ban",q.toString(),adminToken,r->{targetStatus.setText("🚫 تم تنفيذ "+(minutes>0?"الحظر المؤقت":"الحظر الدائم"));toast("تم التنفيذ ✓");});}catch(Exception e){toast("فشل الحظر");}}
    private void unbanTarget(){if(selectedUserId.isEmpty()){toast("اختر المستخدم أولًا");return;}request("POST","/api/admin/unban",jsonOne("wethaqId",selectedUserId),adminToken,r->toast("تمت إزالة الحظر ✓"));}
    private void warnTarget(){if(selectedUserId.isEmpty()){toast("اختر المستخدم أولًا");return;}EditText msg=field("رسالة التنبيه");new AlertDialog.Builder(this).setTitle("تنبيه المستخدم").setView(msg).setPositiveButton("إرسال",(d,w)->{String x=msg.getText().toString().trim();if(x.isEmpty()){toast("اكتب رسالة التنبيه");return;}try{JSONObject q=new JSONObject();q.put("wethaqId",selectedUserId);q.put("message",x);request("POST","/api/admin/alert",q.toString(),adminToken,r->toast("تم إرسال التنبيه ✓"));}catch(Exception e){toast("فشل التنبيه");}}).setNegativeButton("إلغاء",null).show();}
    private void removeTargetRole(){if(selectedUserId.isEmpty()){toast("اختر صاحب المنصب أولًا");return;}new AlertDialog.Builder(this).setTitle("إزالة المنصب").setMessage("سيتم إنهاء المنصب الإداري المحدد.").setPositiveButton("إزالة",(d,w)->request("POST","/api/admin/remove-role",jsonOne("wethaqId",selectedUserId),adminToken,r->toast("تمت إزالة المنصب ✓"))).setNegativeButton("إلغاء",null).show();}
    private void addAssignmentCard(JSONObject role){LinearLayout box=card("📋 بطاقة التعيين الإداري");EditText name=field("الاسم الثلاثي للمستخدم"),birth=field("سنة الميلاد"),personal=field("الرقم الشخصي (6-12 أرقام)");birth.setInputType(InputType.TYPE_CLASS_NUMBER);personal.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);box.addView(name);box.addView(birth);box.addView(personal);Button verify=btn("🔎 تحقق أولي");box.addView(verify);TextView selected=tv("لم يتم اختيار مستخدم للتعيين.",15,Color.WHITE);box.addView(selected);Spinner sp=new Spinner(this);ArrayList<String> labels=new ArrayList<>(),keys=new ArrayList<>();labels.add("اختر المنصب");keys.add("");JSONArray allowed=role.optJSONArray("appoints");String[][] all={{"executive","🏛 المدير التنفيذي"},{"deputy1","🥇 النائب الأول"},{"deputy2","🥈 النائب الثاني"},{"deputy3","🥉 النائب الثالث"},{"supervisor","🛡 المشرف"},{"admin_member","👥 عضو الإدارة"},{"premium","⭐ عضو مميز"}};for(String[] x:all){if(allowed!=null&&allowed.toString().contains("\""+x[0]+"\"")){keys.add(x[0]);labels.add(x[1]);}}sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,labels){public android.view.View getView(int p,android.view.View v,android.view.ViewGroup g){TextView t=(TextView)super.getView(p,v,g);t.setTextColor(Color.WHITE);t.setGravity(Gravity.RIGHT);return t;}});box.addView(sp,new LinearLayout.LayoutParams(-1,dp(62)));sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,android.view.View v,int pos,long id){selectedRole=keys.get(pos);}public void onNothingSelected(android.widget.AdapterView<?> p){selectedRole="";}});Button confirm=btn("📌 تثبيت التعيين");box.addView(confirm);TextView note=tv("تحتوي المناصب المدفوعة على اشتراك سنوي، وتظهر قيمة الاشتراك ضمن بطاقة المنصب.",15,Color.WHITE);box.addView(note);verify.setOnClickListener(v->findAssignmentUser(name,birth,personal,selected));confirm.setOnClickListener(v->assign(name,birth,personal,note));content.addView(box);}
    private void findAssignmentUser(EditText n,EditText b,EditText p,TextView result){String q=n.getText().toString().trim();if(q.length()<2){toast("أدخل الاسم الثلاثي");return;}request("GET","/api/admin/users?q="+enc(q),null,adminToken,r->{try{JSONArray a=new JSONObject(r).optJSONArray("users");if(a==null||a.length()==0){selectedAssignmentId="";result.setText("❌ المستخدم غير موجود");return;}JSONObject u=a.getJSONObject(0);selectedAssignmentId=u.optString("wethaq_id");n.setText(u.optString("name"));b.setText(u.optString("birth_year"));result.setText("✅ تم تحديد: "+u.optString("name")+" — "+selectedAssignmentId);}catch(Exception e){toast("تعذر التحقق");}});}
    private void assign(EditText n,EditText b,EditText p,TextView result){if(selectedAssignmentId.isEmpty()||selectedRole.isEmpty()){toast("تحقق من المستخدم واختر المنصب");return;}String code=p.getText().toString().trim();if(!code.matches("\\d{6,12}")){toast("الرقم الشخصي يجب أن يكون 6-12 أرقام");return;}try{JSONObject q=new JSONObject();q.put("wethaqId",selectedAssignmentId);q.put("name",n.getText().toString().trim());q.put("birthYear",Integer.parseInt(b.getText().toString().trim()));q.put("personalCode",code);q.put("role",selectedRole);request("POST","/api/admin/assign",q.toString(),adminToken,r->{try{JSONObject z=new JSONObject(r);String codeOut=z.optString("adminCode");result.setText("✅ تم التعيين\n"+z.optString("label")+"\nالاشتراك السنوي: "+feeLabel(selectedRole)+"\nرمز المنصب: "+codeOut);new AlertDialog.Builder(this).setTitle("تم التعيين").setMessage("المنصب: "+z.optString("label")+"\nالاشتراك السنوي: "+feeLabel(selectedRole)+"\nرمز المنصب السري:\n"+codeOut).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل قراءة نتيجة التعيين");}});}catch(Exception e){toast("بيانات التعيين غير صحيحة");}}
    private String feeLabel(String role){double v=role.equals("executive")?100:role.equals("deputy1")?70:role.equals("deputy2")?50:role.equals("deputy3")?30:role.equals("supervisor")?15:role.equals("admin_member")?7:role.equals("premium")?2:0;return v==0?"بدون اشتراك للمؤسس":String.format(Locale.US,"%.0f دولار",v);}
    private void addStructureCard(){Button structure=btn("📊 عرض الهيكل الإداري العام");content.addView(structure);structure.setOnClickListener(v->historyPublic());}
    private void addAuditCards(){Button login=btn("👤 سجل المستخدمين"),pos=btn("🏛 سجل التعيينات والمناصب"),structure=btn("📊 الهيكل الإداري العام"),audit=btn("🧾 سجل تدقيق المؤسس");content.addView(login);content.addView(pos);content.addView(structure);content.addView(audit);login.setOnClickListener(v->history("/api/admin/login-history?limit=200","سجل المستخدمين"));pos.setOnClickListener(v->history("/api/admin/position-history?limit=200","سجل التعيينات والمناصب"));structure.setOnClickListener(v->historyPublic());audit.setOnClickListener(v->history("/api/admin/audit-log","سجل تدقيق المؤسس"));}
    private void history(String path,String title){request("GET",path,null,adminToken,r->showText(title,r));}
    private void historyPublic(){request("GET","/api/admin/structure",null,adminToken,r->showText("الهيكل الإداري",r));}
    private void showText(String title,String raw){try{new AlertDialog.Builder(this).setTitle(title).setMessage(new JSONObject(raw).toString(2)).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("تعذر عرض السجل");}}
    private JSONObject jsonOne(String k,String v){try{return new JSONObject().put(k,v);}catch(Exception e){return new JSONObject();}}
    private String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return "";}}
    private interface CB{void ok(String s);}
    private void request(String method,String path,String body,String token,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setUseCaches(false);c.setRequestProperty("Accept","application/json");if(token!=null&&!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(in!=null){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);in.close();}String s=new String(out.toByteArray(),StandardCharsets.UTF_8);runOnUiThread(()->{if(code>=200&&code<300)cb.ok(s);else toast("فشل الطلب: "+error(s));});}catch(Exception e){runOnUiThread(()->toast("تعذر الاتصال بالخادم"));}}).start();}
    private String error(String s){try{return new JSONObject(s).optString("error",s);}catch(Exception e){return "الطلب مرفوض";}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
