pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://raw.githubusercontent.com/ALEXGREENCH/google-webrtc/master' }
    }
}

rootProject.name = 'Wethaq'
include ':app'
