const base = `http://127.0.0.1:${process.env.PORT || 3100}`;
const assert = (ok, msg) => { if (!ok) throw new Error(msg); };
async function req(path, options = {}) { const r = await fetch(base + path, { ...options, headers: { 'content-type':'application/json', ...(options.headers || {}) } }); const text = await r.text(); let body={}; try { body=JSON.parse(text); } catch {} return {r,body}; }
const s = String(Date.now()).slice(-8);
const founderName = 'حاتم حسين الحاج رمضان';
const founderCode = String(100000 + (Date.now() % 899999));
const memberName = `عضو إدارة ${s}`;
const memberCode = String(100000 + ((Date.now()+12345) % 899999));
const founder = await req('/api/identity',{method:'POST',body:JSON.stringify({name:founderName,birthYear:1995,personalCode:founderCode,deviceKey:`f-${s}`})});
assert(founder.r.status===201 && founder.body.token,'founder identity failed');
const issued = await req('/api/admin/founder-code',{method:'POST',headers:{authorization:`Bearer ${founder.body.token}`}});
assert(issued.r.ok && issued.body.adminCode,'founder code failed');
const login = await req('/api/admin/login',{method:'POST',body:JSON.stringify({name:founderName,birthYear:1995,adminCode:issued.body.adminCode})});
assert(login.r.ok && login.body.role==='founder','founder admin login failed');
const member = await req('/api/identity',{method:'POST',body:JSON.stringify({name:memberName,birthYear:1998,personalCode:memberCode,deviceKey:`m-${s}`})});
assert(member.r.status===201,'member identity failed');
const bad = await req('/api/admin/assign',{method:'POST',headers:{authorization:`Bearer ${login.body.token}`},body:JSON.stringify({wethaqId:member.body.user.wethaq_id,name:memberName,birthYear:1998,personalCode:String(Number(memberCode)+1),role:'admin_member'})});
assert(bad.r.status===403 && bad.body.error==='assignment_personal_code_invalid','invalid assignment code bypassed');
const assigned = await req('/api/admin/assign',{method:'POST',headers:{authorization:`Bearer ${login.body.token}`},body:JSON.stringify({wethaqId:member.body.user.wethaq_id,name:memberName,birthYear:1998,personalCode:memberCode,role:'admin_member'})});
assert(assigned.r.status===201 && assigned.body.adminCode,'verified assignment failed');
assert((await req('/api/admin/structure')).r.status===401,'admin structure is public');
const structure = await req('/api/admin/structure',{headers:{authorization:`Bearer ${login.body.token}`}});
assert(structure.r.ok && Array.isArray(structure.body.roles),'founder structure failed');
const memberLogin = await req('/api/admin/login',{method:'POST',body:JSON.stringify({name:memberName,birthYear:1998,adminCode:assigned.body.adminCode})});
assert(memberLogin.r.ok && memberLogin.body.role==='admin_member','member admin login failed');
assert((await req('/api/admin/structure',{headers:{authorization:`Bearer ${memberLogin.body.token}`}})).r.status===403,'member can view restricted structure');
assert((await req('/api/admin/audit-log',{headers:{authorization:`Bearer ${memberLogin.body.token}`}})).r.status===403,'member can view founder audit log');
const personal = await req('/api/login',{method:'POST',body:JSON.stringify({name:memberName,birthYear:1998,personalCode:memberCode,deviceKey:`m2-${s}`})});
assert(personal.r.ok && personal.body.token,'personal login broke after assignment');
const removed = await req('/api/admin/remove-role',{method:'POST',headers:{authorization:`Bearer ${login.body.token}`},body:JSON.stringify({wethaqId:member.body.user.wethaq_id})});
assert(removed.r.ok,'role removal failed');
console.log('WETHAQ_HARDENING_SMOKE_OK');
