import express from 'express';
import cors from 'cors';
import http from 'http';
import crypto from 'crypto';
import jwt from 'jsonwebtoken';
import Database from 'better-sqlite3';
import { WebSocketServer } from 'ws';
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'});
const db=new Database(process.env.DB_PATH||'wethaq.db'),PORT=Number(process.env.PORT||3000),JWT_SECRET=process.env.JWT_SECRET||crypto.randomBytes(32).toString('hex');
const MAX_MESSAGE=4000,MAX_AUDIO_BASE64=5*1024*1024,MAX_IMAGE_BASE64=6*1024*1024,MAX_NAME=80,MAX_DEVICE_KEY=256,OWNER_WETHAQ_ID=process.env.OWNER_WETHAQ_ID||'Hatem_Hussin_Al_Haj_Ramadan1995';
app.disable('x-powered-by');app.set('trust proxy',1);app.use(cors({origin:(_o,c)=>c(null,true)}));app.use(express.json({limit:'12mb'}));
const online=new Map(),attempts=new Map(),now=()=>new Date().toISOString();const validText=(v,m)=>typeof v==='string'&&v.trim().length>0&&v.trim().length<=m;
function rateLimit(k,l,w){const t=Date.now(),o=attempts.get(k)||{count:0,at:t};if(t-o.at>w){attempts.set(k,{count:1,at:t});return true}o.count++;attempts.set(k,o);return o.count<=l}function ensureColumn(t,c,d){const a=db.prepare(`PRAGMA table_info(${t})`).all().map(x=>x.name);if(!a.includes(c))db.exec(`ALTER TABLE ${t} ADD COLUMN ${c} ${d}`)}
db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,wethaq_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,birth_year INTEGER NOT NULL DEFAULT 0,password_hash TEXT,device_key TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT,avatar_data TEXT,avatar_mime TEXT);CREATE TABLE IF NOT EXISTS contacts(user_id INTEGER NOT NULL,contact_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,contact_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(contact_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER NOT NULL,receiver_id INTEGER NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'sent',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(receiver_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS call_signals(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER NOT NULL,receiver_id INTEGER NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_messages_pair ON messages(sender_id,receiver_id,id);CREATE INDEX IF NOT EXISTS idx_users_name ON users(name COLLATE NOCASE);CREATE INDEX IF NOT EXISTS idx_users_wethaq_id ON users(wethaq_id);CREATE INDEX IF NOT EXISTS idx_call_receiver ON call_signals(receiver_id,id);`);
ensureColumn('users','birth_year','INTEGER NOT NULL DEFAULT 0');ensureColumn('users','last_seen','TEXT');ensureColumn('users','device_key','TEXT');ensureColumn('users','avatar_data','TEXT');ensureColumn('users','avatar_mime','TEXT');ensureColumn('users','personal_code_hash','TEXT');ensureColumn('messages','message_type',"TEXT NOT NULL DEFAULT 'text'");ensureColumn('messages','mime_type','TEXT');ensureColumn('messages','audio_data','TEXT');db.exec(`CREATE TABLE IF NOT EXISTS bans(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,ban_type TEXT NOT NULL,expires_at TEXT,reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by INTEGER,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS complaints(id INTEGER PRIMARY KEY AUTOINCREMENT,from_user_id INTEGER NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(from_user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_bans_user ON bans(user_id);`);
const AR={'حاتم':'Hatem','حسين':'Hussin','الحاج':'Al_Haj','رمضان':'Ramadan','عبد':'Abd','الله':'Allah','محمد':'Mohammad','أحمد':'Ahmed','علي':'Ali','خالد':'Khalid','سارة':'Sara','سما':'Sama','نور':'Noor','هدى':'Huda','أمان':'Aman','وسام':'Wisam','يامن':'Yamen','هشام':'Hisham','أيمن':'Ayman','حسام':'Hossam'};const MAP={'ا':'a','أ':'a','إ':'i','آ':'a','ب':'b','ت':'t','ث':'th','ج':'j','ح':'h','خ':'kh','د':'d','ذ':'dh','ر':'r','ز':'z','س':'s','ش':'sh','ص':'s','ض':'d','ط':'t','ظ':'z','ع':'a','غ':'gh','ف':'f','ق':'q','ك':'k','ل':'l','م':'m','ن':'n','ه':'h','و':'w','ي':'y','ى':'a','ة':'h'};
function transliterateWord(w){if(AR[w])return AR[w];let o='';for(const c of w)o+=MAP[c]??(/[A-Za-z0-9]/.test(c)?c:'');return o?o[0].toUpperCase()+o.slice(1):''}function makeBaseId(n,y){return `${n.replace(/ـ/g,'').trim().split(/[\s،,]+/).filter(Boolean).map(transliterateWord).filter(Boolean).join('_')}${y}`.replace(/[^A-Za-z0-9_]/g,'_')}function makeWethaqId(name,birthYear){const b=makeBaseId(name,birthYear)||`Wethaq_User${birthYear}`;let id=b,seq=2;while(db.prepare('SELECT 1 FROM users WHERE wethaq_id=?').get(id))id=`${b}_${seq++}`;return id}
function isOnline(id){const s=online.get(Number(id));return !!s&&[...s].some(w=>w.readyState===1)}function publicUser(u,full=false){return{id:u.id,wethaq_id:u.wethaq_id,name:u.name,created_at:u.created_at,last_seen:u.last_seen||null,online:isOnline(u.id),has_avatar:!!u.avatar_data,...(full&&u.avatar_data?{avatar_data:u.avatar_data,avatar_mime:u.avatar_mime||'image/jpeg'}:{})}}function tokenFor(u){return jwt.sign({sub:u.id,wethaqId:u.wethaq_id},JWT_SECRET,{expiresIn:'365d'})}function activeBan(userId){const b=db.prepare('SELECT * FROM bans WHERE user_id=? ORDER BY id DESC LIMIT 1').get(userId);if(!b)return null;if(b.ban_type==='temporary'&&b.expires_at&&new Date(b.expires_at)<=new Date()){db.prepare('DELETE FROM bans WHERE id=?').run(b.id);return null}return b}function auth(req,res,next){const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):'';if(!t)return res.status(401).json({error:'unauthorized'});try{req.user=jwt.verify(t,JWT_SECRET);const b=activeBan(Number(req.user.sub));if(b)return res.status(403).json({error:'user_banned',ban_type:b.ban_type,expires_at:b.expires_at||null,reason:b.reason||''});next()}catch{return res.status(401).json({error:'invalid_token'})}}function admin(req,res,next){if(req.user?.wethaqId!==OWNER_WETHAQ_ID)return res.status(403).json({error:'admin_only'});next()}
function safeName(v){return String(v||'').replace(/[<>\u0000-\u001f]/g,'').trim().replace(/\s+/g,' ')}function safeMessage(v){return String(v||'').trim()}function validPersonalCode(v){return /^\d{6,12}$/.test(String(v||'').trim())}function hashPersonalCode(code){const salt=crypto.randomBytes(16),hash=crypto.scryptSync(String(code).trim(),salt,32);return `${salt.toString('hex')}:${hash.toString('hex')}`}function verifyPersonalCode(code,stored){try{const[a,b]=String(stored||'').split(':');if(!a||!b)return false;const salt=Buffer.from(a,'hex'),expected=Buffer.from(b,'hex'),actual=crypto.scryptSync(String(code||'').trim(),salt,32);return expected.length===actual.length&&crypto.timingSafeEqual(expected,actual)}catch{return false}}function identityInput(req,res){const name=safeName(req.body?.name),birthYear=Number(req.body?.birthYear),deviceKey=String(req.body?.deviceKey||'').trim(),personalCode=String(req.body?.personalCode||'').trim(),currentYear=new Date().getUTCFullYear();if(!validText(name,MAX_NAME)||name.split(/\s+/).length<3||!Number.isInteger(birthYear)||birthYear<1900||birthYear>currentYear||deviceKey.length>MAX_DEVICE_KEY||!validPersonalCode(personalCode)){res.status(400).json({error:'invalid_identity'});return null}return{name,birthYear,deviceKey:deviceKey||crypto.randomBytes(24).toString('hex'),personalCode}}
function linkContacts(a,b){if(!a||!b||Number(a)===Number(b))return;db.prepare('INSERT OR IGNORE INTO contacts(user_id,contact_id) VALUES(?,?)').run(Number(a),Number(b));db.prepare('INSERT OR IGNORE INTO contacts(user_id,contact_id) VALUES(?,?)').run(Number(b),Number(a))}
function pushUser(id,event){const set=online.get(Number(id));if(!set)return;const data=JSON.stringify(event);for(const socket of set){if(socket.readyState===1){try{socket.send(data)}catch{}}}}
function pushMessage(message,sender,receiver){pushUser(receiver.id,{event:'message',message:{...message,sender_name:sender.name,sender_wethaq_id:sender.wethaq_id}})}
app.get('/',(_q,r)=>r.json({service:'wethaq',status:'online',health:'/health'}));app.get('/health',(_q,r)=>r.json({ok:true,service:'wethaq',version:'6.0.1',auth:'name_birth_year_personal_code',search:'public',websocket:'/ws',audio:true,image:true,avatar:true,video:true,contacts:true,notifications:true,time:now()}));
app.post('/api/identity',(req,res)=>{const x=identityInput(req,res);if(!x)return;const{name,birthYear,deviceKey,personalCode}=x,base=makeBaseId(name,birthYear);let u=db.prepare('SELECT * FROM users WHERE wethaq_id=?').get(base);if(u){if(u.device_key&&u.device_key!==deviceKey)return res.status(409).json({error:'identity_claimed'});if(u.personal_code_hash&&!verifyPersonalCode(personalCode,u.personal_code_hash))return res.status(401).json({error:'invalid_personal_code'});db.prepare('UPDATE users SET device_key=?,name=?,birth_year=?,personal_code_hash=?,last_seen=? WHERE id=?').run(deviceKey,name,birthYear,hashPersonalCode(personalCode),now(),u.id)}else{const id=makeWethaqId(name,birthYear),z=db.prepare('INSERT INTO users(wethaq_id,name,birth_year,personal_code_hash,device_key,last_seen) VALUES(?,?,?,?,?,?)').run(id,name,birthYear,hashPersonalCode(personalCode),deviceKey,now());u=db.prepare('SELECT * FROM users WHERE id=?').get(z.lastInsertRowid)}u=db.prepare('SELECT * FROM users WHERE id=?').get(u.id);res.status(201).json({user:publicUser(u),token:tokenFor(u)})});
app.post('/api/login',(req,res)=>{const x=identityInput(req,res);if(!x)return;let u=db.prepare('SELECT * FROM users WHERE name=? AND birth_year=?').get(x.name,x.birthYear);if(!u)return res.status(404).json({error:'user_not_found'});if(!u.personal_code_hash){db.prepare('UPDATE users SET personal_code_hash=? WHERE id=?').run(hashPersonalCode(x.personalCode),u.id)}else if(!verifyPersonalCode(x.personalCode,u.personal_code_hash))return res.status(401).json({error:'invalid_personal_code'});const ban=activeBan(u.id);if(ban)return res.status(403).json({error:'user_banned',ban_type:ban.ban_type,expires_at:ban.expires_at||null,reason:ban.reason||''});db.prepare('UPDATE users SET device_key=?,last_seen=? WHERE id=?').run(x.deviceKey,now(),u.id);u=db.prepare('SELECT * FROM users WHERE id=?').get(u.id);res.json({user:publicUser(u),token:tokenFor(u)})});app.get('/api/me',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.sub);if(!u)return res.status(404).json({error:'user_not_found'});db.prepare('UPDATE users SET last_seen=? WHERE id=?').run(now(),u.id);res.json({user:publicUser(u,true)})});
app.get('/api/search',(req,res)=>{const q=safeName(req.query.q);if(q.length<2)return res.json({users:[]});const a=db.prepare('SELECT id,wethaq_id,name,birth_year,last_seen,created_at,avatar_data FROM users WHERE wethaq_id LIKE ? OR name LIKE ? ORDER BY name COLLATE NOCASE LIMIT 30').all(`%${q}%`,`%${q}%`);res.json({users:a.map(publicUser)})});app.post('/api/profile/avatar',auth,(req,res)=>{const data=String(req.body?.imageBase64||'').trim(),mime=String(req.body?.mimeType||'image/jpeg').trim();if(!data||data.length>MAX_IMAGE_BASE64||!/^[A-Za-z0-9+/=]+$/.test(data)||!/^image\/(jpeg|png|webp)$/.test(mime))return res.status(400).json({error:'invalid_avatar'});db.prepare('UPDATE users SET avatar_data=?,avatar_mime=? WHERE id=?').run(data,mime,req.user.sub);res.json({ok:true})});app.get('/api/users/:wethaqId/avatar',auth,(req,res)=>{const u=db.prepare('SELECT avatar_data,avatar_mime FROM users WHERE wethaq_id=?').get(req.params.wethaqId);if(!u||!u.avatar_data)return res.status(404).json({error:'avatar_not_found'});res.json({imageBase64:u.avatar_data,mimeType:u.avatar_mime||'image/jpeg'})});
app.get('/api/messages/inbox',auth,(req,res)=>{const rows=db.prepare(`SELECT m.*,u.name sender_name,u.wethaq_id sender_wethaq_id FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.receiver_id=? ORDER BY m.id ASC LIMIT 200`).all(req.user.sub);db.prepare("UPDATE messages SET status='delivered' WHERE receiver_id=? AND status='sent'").run(req.user.sub);res.json({messages:rows})});app.get('/api/messages/:wethaqId',auth,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE wethaq_id=?').get(req.params.wethaqId);if(!u)return res.status(404).json({error:'user_not_found'});linkContacts(Number(req.user.sub),u.id);const rows=db.prepare(`SELECT m.*,su.name sender_name,su.wethaq_id sender_wethaq_id,ru.name receiver_name,ru.wethaq_id receiver_wethaq_id FROM messages m JOIN users su ON su.id=m.sender_id JOIN users ru ON ru.id=m.receiver_id WHERE (m.sender_id=? AND m.receiver_id=?) OR (m.sender_id=? AND m.receiver_id=?) ORDER BY m.id ASC LIMIT 500`).all(req.user.sub,u.id,u.id,req.user.sub);db.prepare("UPDATE messages SET status='read' WHERE sender_id=? AND receiver_id=? AND status<>'read'").run(u.id,req.user.sub);res.json({contact:publicUser(u,true),messages:rows})});
function receiver(to,res){const u=db.prepare('SELECT id,wethaq_id,name FROM users WHERE wethaq_id=?').get(to);if(!u){res.status(404).json({error:'user_not_found'});return null}return u}
app.post('/api/contacts',auth,(req,res)=>{const wethaqId=String(req.body?.wethaqId||'').trim();if(!wethaqId)return res.status(400).json({error:'invalid_contact'});const u=db.prepare('SELECT * FROM users WHERE wethaq_id=?').get(wethaqId);if(!u)return res.status(404).json({error:'user_not_found'});if(Number(u.id)===Number(req.user.sub))return res.status(400).json({error:'self_contact'});linkContacts(Number(req.user.sub),u.id);res.status(201).json({contact:publicUser(u,true)})});
app.post('/api/messages',auth,(req,res)=>{const to=String(req.body?.to||'').trim(),body=safeMessage(req.body?.body??req.body?.text);if(!to||!body||body.length>MAX_MESSAGE)return res.status(400).json({error:'invalid_message'});const u=receiver(to,res);if(!u||u.id===Number(req.user.sub))return;const sender=db.prepare('SELECT id,wethaq_id,name FROM users WHERE id=?').get(req.user.sub);linkContacts(req.user.sub,u.id);const z=db.prepare("INSERT INTO messages(sender_id,receiver_id,body,status,message_type) VALUES(?,?,?,?,'text')").run(req.user.sub,u.id,body,isOnline(u.id)?'delivered':'sent');const message=db.prepare('SELECT * FROM messages WHERE id=?').get(z.lastInsertRowid);pushMessage(message,sender,u);res.status(201).json({message})});
app.post('/api/messages/audio',auth,(req,res)=>{const to=String(req.body?.to||'').trim(),audio=String(req.body?.audioBase64||'').trim(),mime=String(req.body?.mimeType||'audio/mp4');if(!to||!audio||audio.length>MAX_AUDIO_BASE64||!/^[A-Za-z0-9+/=]+$/.test(audio))return res.status(400).json({error:'invalid_audio'});const u=receiver(to,res);if(!u||u.id===Number(req.user.sub))return;const sender=db.prepare('SELECT id,wethaq_id,name FROM users WHERE id=?').get(req.user.sub);linkContacts(req.user.sub,u.id);const z=db.prepare("INSERT INTO messages(sender_id,receiver_id,body,status,message_type,mime_type,audio_data) VALUES(?,?,?,'sent','audio',?,?)").run(req.user.sub,u.id,'',mime,audio);const message=db.prepare('SELECT * FROM messages WHERE id=?').get(z.lastInsertRowid);pushMessage(message,sender,u);res.status(201).json({message})});
app.post('/api/messages/image',auth,(req,res)=>{const to=String(req.body?.to||'').trim(),image=String(req.body?.imageBase64||'').trim(),mime=String(req.body?.mimeType||'image/jpeg');if(!to||!image||image.length>MAX_IMAGE_BASE64||!/^[A-Za-z0-9+/=]+$/.test(image)||!/^image\/(jpeg|png|webp)$/.test(mime))return res.status(400).json({error:'invalid_image'});const u=receiver(to,res);if(!u||u.id===Number(req.user.sub))return;const sender=db.prepare('SELECT id,wethaq_id,name FROM users WHERE id=?').get(req.user.sub);linkContacts(req.user.sub,u.id);const z=db.prepare("INSERT INTO messages(sender_id,receiver_id,body,status,message_type,mime_type,audio_data) VALUES(?,?,?,'sent','image',?,?)").run(req.user.sub,u.id,'',mime,image);const message=db.prepare('SELECT * FROM messages WHERE id=?').get(z.lastInsertRowid);pushMessage(message,sender,u);res.status(201).json({message})});
app.post('/api/calls/signal',auth,(req,res)=>{const to=String(req.body?.to||'').trim(),type=String(req.body?.type||''),payload=String(req.body?.payload||'');if(!to||!['offer','answer','ice','end'].includes(type)||payload.length>200000)return res.status(400).json({error:'invalid_signal'});const u=receiver(to,res);if(!u)return;linkContacts(req.user.sub,u.id);const z=db.prepare('INSERT INTO call_signals(sender_id,receiver_id,type,payload) VALUES(?,?,?,?)').run(req.user.sub,u.id,type,payload);pushUser(u.id,{event:'call',from:db.prepare('SELECT wethaq_id,name FROM users WHERE id=?').get(req.user.sub),type,payload,signal_id:z.lastInsertRowid});res.status(201).json({id:z.lastInsertRowid})});app.get('/api/calls/signals/:wethaqId',auth,(req,res)=>{const u=db.prepare('SELECT id FROM users WHERE wethaq_id=?').get(req.params.wethaqId);if(!u)return res.status(404).json({error:'user_not_found'});const rows=db.prepare('SELECT id,type,payload,created_at FROM call_signals WHERE receiver_id=? AND sender_id=? ORDER BY id ASC LIMIT 100').all(req.user.sub,u.id);if(rows.length)db.prepare('DELETE FROM call_signals WHERE receiver_id=? AND sender_id=? AND id<=?').run(req.user.sub,u.id,rows[rows.length-1].id);res.json({signals:rows})});
wss.on('connection',(socket,request)=>{try{const token=new URL(request.url,'http://localhost').searchParams.get('token')||'',d=jwt.verify(token,JWT_SECRET),id=Number(d.sub);if(!db.prepare('SELECT id FROM users WHERE id=?').get(id))return socket.close(1008);if(!online.has(id))online.set(id,new Set());online.get(id).add(socket);socket.on('close',()=>{const s=online.get(id);if(s){s.delete(socket);if(!s.size)online.delete(id)}})}catch{socket.close(1008)}});app.post('/api/complaints',auth,(req,res)=>{const message=safeMessage(req.body?.message||'أرغب بالتواصل مع مؤسس وَثاق');const owner=db.prepare('SELECT id FROM users WHERE wethaq_id=?').get(OWNER_WETHAQ_ID);if(!owner)return res.status(503).json({error:'owner_not_found'});if(owner.id===Number(req.user.sub))return res.status(400).json({error:'owner_cannot_complain_to_self'});const sender=db.prepare('SELECT id,wethaq_id,name FROM users WHERE id=?').get(req.user.sub);linkContacts(req.user.sub,owner.id);const z=db.prepare("INSERT INTO messages(sender_id,receiver_id,body,status,message_type) VALUES(?,?,?,?,'text')").run(req.user.sub,owner.id,message,isOnline(owner.id)?'delivered':'sent');const saved=db.prepare('SELECT * FROM messages WHERE id=?').get(z.lastInsertRowid);pushMessage(saved,sender,owner);db.prepare('INSERT INTO complaints(from_user_id,message) VALUES(?,?)').run(req.user.sub,message);res.status(201).json({ok:true,message_id:z.lastInsertRowid})});
app.get('/api/admin/users',auth,admin,(req,res)=>{const q=safeName(req.query.q||'');const rows=q?db.prepare('SELECT id,wethaq_id,name,birth_year,last_seen FROM users WHERE wethaq_id LIKE ? OR name LIKE ? ORDER BY id DESC LIMIT 50').all(`%${q}%`,`%${q}%`):db.prepare('SELECT id,wethaq_id,name,birth_year,last_seen FROM users ORDER BY id DESC LIMIT 50').all();res.json({users:rows.map(u=>({...u,ban:activeBan(u.id)}))})});
app.post('/api/admin/ban',auth,admin,(req,res)=>{const wethaqId=String(req.body?.wethaqId||'').trim(),minutes=Math.max(0,Number(req.body?.minutes||0)),reason=safeMessage(req.body?.reason||'بقرار من إدارة وَثاق');const u=db.prepare('SELECT id,wethaq_id,name FROM users WHERE wethaq_id=?').get(wethaqId);if(!u)return res.status(404).json({error:'user_not_found'});if(u.wethaq_id===OWNER_WETHAQ_ID)return res.status(400).json({error:'cannot_ban_owner'});db.prepare('DELETE FROM bans WHERE user_id=?').run(u.id);const type=minutes>0?'temporary':'permanent',expires=minutes>0?new Date(Date.now()+minutes*60000).toISOString():null;db.prepare('INSERT INTO bans(user_id,ban_type,expires_at,reason,created_by) VALUES(?,?,?,?,?)').run(u.id,type,expires,reason,req.user.sub);res.json({ok:true,wethaq_id:u.wethaq_id,ban_type:type,expires_at:expires})});
app.post('/api/admin/unban',auth,admin,(req,res)=>{const u=db.prepare('SELECT id FROM users WHERE wethaq_id=?').get(String(req.body?.wethaqId||'').trim());if(!u)return res.status(404).json({error:'user_not_found'});db.prepare('DELETE FROM bans WHERE user_id=?').run(u.id);res.json({ok:true})});
app.get('/api/admin/complaints',auth,admin,(req,res)=>{const rows=db.prepare('SELECT c.*,u.name from_name,u.wethaq_id from_wethaq_id FROM complaints c JOIN users u ON u.id=c.from_user_id ORDER BY c.id DESC LIMIT 100').all();res.json({complaints:rows})});
// WETHAQ_ADMIN_ACCESS_LAYER_V1
const ADMIN_POLICY={
  founder:{label:'المؤسس',icon:'👑',fee:null,capacity:1,appoints:['executive','deputy1','deputy2','deputy3','supervisor','admin_member','premium'],permissions:['إدارة النظام','تعيين وإزالة المناصب','إصدار وتجديد رموز المناصب','الحظر والإلغاء','التحذير والتنبيهات','عرض سجل التدقيق']},
  executive:{label:'المدير التنفيذي',icon:'🏛',fee:100,capacity:1,appoints:['admin_member','premium'],permissions:['تعيين أعضاء الإدارة','تعيين أعضاء مميزين','الحظر ضمن النطاق','التحذير والتنبيهات','عرض الإدارة']},
  deputy1:{label:'النائب الأول',icon:'🥇',fee:70,capacity:1,appoints:['admin_member','premium'],adminMemberQuota:3,permissions:['تعيين 3 أعضاء إدارة','تعيين أعضاء مميزين','الحظر ضمن النطاق','التحذير والتنبيهات','عرض الإدارة']},
  deputy2:{label:'النائب الثاني',icon:'🥈',fee:50,capacity:1,appoints:['admin_member','premium'],permissions:['تعيين أعضاء إدارة','تعيين أعضاء مميزين','الحظر ضمن النطاق','التحذير والتنبيهات','عرض الإدارة']},
  deputy3:{label:'النائب الثالث',icon:'🥉',fee:30,capacity:1,appoints:['premium'],permissions:['تعيين أعضاء مميزين','الحظر ضمن النطاق','التحذير والتنبيهات','عرض الإدارة']},
  supervisor:{label:'المشرف',icon:'🛡',fee:15,capacity:9,appoints:['premium'],supervisorPremiumQuota:null,permissions:['تعيين أعضاء مميزين ضمن الحد','الحظر ضمن النطاق','التحذير والتنبيهات','عرض الإدارة']},
  admin_member:{label:'عضو الإدارة',icon:'👥',fee:7,capacity:27,appoints:[],permissions:['الحظر المؤقت للمستخدمين','التحذير']},
  premium:{label:'عضو مميز',icon:'⭐',fee:2,capacity:null,appoints:[],permissions:['التحذير للمستخدمين']}
};
const ADMIN_RANK={founder:0,executive:1,deputy1:2,deputy2:3,deputy3:4,supervisor:5,admin_member:6,premium:7,user:8};
const ADMIN_CODE_LIMIT=64;
db.exec(`CREATE TABLE IF NOT EXISTS admin_roles(user_id INTEGER PRIMARY KEY,role TEXT NOT NULL,code_hash TEXT,subscription_expires_at TEXT,appointed_by INTEGER,appointed_by_role TEXT,appointed_at TEXT,active INTEGER NOT NULL DEFAULT 1,code_version INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS admin_audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_user_id INTEGER,target_user_id INTEGER,action TEXT NOT NULL,role TEXT,details TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(target_user_id) REFERENCES users(id) ON DELETE SET NULL);CREATE INDEX IF NOT EXISTS idx_admin_role ON admin_roles(role,active);CREATE INDEX IF NOT EXISTS idx_admin_audit ON admin_audit_log(id);`);
const roleRow=userId=>db.prepare(`SELECT ar.*,u.name,u.wethaq_id,u.birth_year FROM admin_roles ar JOIN users u ON u.id=ar.user_id WHERE ar.user_id=? AND ar.active=1`).get(Number(userId));
const activeAdminRole=userId=>{const r=roleRow(userId);if(!r)return null;if(r.role!=='founder'&&r.subscription_expires_at&&new Date(r.subscription_expires_at)<=new Date()){db.prepare('UPDATE admin_roles SET active=0 WHERE user_id=?').run(Number(userId));return null}return r};
const adminTokenFor=r=>jwt.sign({sub:r.user_id,wethaqId:r.wethaq_id,admin:true,role:r.role},JWT_SECRET,{expiresIn:'30d'});
function adminAuth(req,res,next){const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):'';if(!t)return res.status(401).json({error:'admin_unauthorized'});try{const d=jwt.verify(t,JWT_SECRET);if(d.admin!==true)return res.status(403).json({error:'admin_token_required'});const r=activeAdminRole(Number(d.sub));if(!r||r.role!==d.role)return res.status(403).json({error:'admin_role_inactive'});req.admin=d;req.adminRow=r;next()}catch{return res.status(401).json({error:'invalid_admin_token'})}}
function hashAdminCode(code){return crypto.createHash('sha256').update(String(code)).digest('hex')}
function timingCodeMatch(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function newAdminCode(){return crypto.randomBytes(24).toString('base64url').slice(0,ADMIN_CODE_LIMIT)}
function audit(actor,target,action,role,details=''){db.prepare('INSERT INTO admin_audit_log(actor_user_id,target_user_id,action,role,details) VALUES(?,?,?,?,?)').run(actor?Number(actor):null,target?Number(target):null,action,role||null,details)}
function roleRank(role){return ADMIN_RANK[role]??ADMIN_RANK.user}
function canAssign(actorRole,targetRole){const p=ADMIN_POLICY[actorRole];return !!p&&p.appoints.includes(targetRole)}
function canManageTarget(actorRole,targetRole){if(targetRole==='founder')return actorRole==='founder';return roleRank(actorRole)<roleRank(targetRole)}
function publicAdminMember(row){return{name:row.name,wethaq_id:row.wethaq_id,birth_year:row.birth_year,role:row.role,appointedBy:row.appointed_by_name?`${row.appointed_by_name} — ${row.appointed_by_role||''}`.trim():'' ,appointedAt:row.appointed_at||null}}
function assignmentCard(target,role,code,appointedBy){const p=ADMIN_POLICY[role];return `🎉 بطاقة تهنئة من وَثاق\n\nتهانينا ${target.name}!\nتم تعيينك رسميًا في منصب: ${p.icon} ${p.label}.\n\n🔐 رمز المنصب السري: ${code}\n\nللبدء في مهمتك واستلام الصلاحيات، يرجى التواصل مع مدير ومؤسس وَثاق لبدء مهمتك واستلام الصلاحيات.\n\nتم التعيين بواسطة: ${appointedBy.name} — ${ADMIN_POLICY[appointedBy.role]?.label||appointedBy.role}\n\nملاحظة أمنية: هذا الرمز سري ومخصص لهذا الحساب وهذا المنصب فقط. لا تشاركه مع أي شخص.`}
function sendAdminAppointmentMessage(target,body){const founder=db.prepare('SELECT id,wethaq_id,name FROM users WHERE wethaq_id=?').get(OWNER_WETHAQ_ID);if(!founder||founder.id===target.id)return;const status=isOnline(target.id)?'delivered':'sent';const z=db.prepare("INSERT INTO messages(sender_id,receiver_id,body,status,message_type) VALUES(?,?,?,?,'admin_assignment')").run(founder.id,target.id,body,status);const saved=db.prepare('SELECT * FROM messages WHERE id=?').get(z.lastInsertRowid);pushMessage(saved,founder,target);}
app.post('/api/admin/login',(req,res)=>{const name=safeName(req.body?.name),birthYear=Number(req.body?.birthYear),code=String(req.body?.adminCode||'').trim();if(!validText(name,MAX_NAME)||name.split(/\s+/).length<3||!Number.isInteger(birthYear)||birthYear<1900||birthYear>new Date().getUTCFullYear()||code.length<8||code.length>ADMIN_CODE_LIMIT)return res.status(400).json({error:'invalid_admin_credentials'});const key=`admin-login:${req.ip}:${name}`;if(!rateLimit(key,8,15*60*1000))return res.status(429).json({error:'too_many_attempts'});const r=db.prepare(`SELECT ar.*,u.name,u.wethaq_id,u.birth_year FROM admin_roles ar JOIN users u ON u.id=ar.user_id WHERE u.name=? AND u.birth_year=? AND ar.active=1`).get(name,birthYear);if(!r||!r.code_hash||!timingCodeMatch(hashAdminCode(code),r.code_hash))return res.status(401).json({error:'admin_invalid_code'});if(r.role!=='founder'&&r.subscription_expires_at&&new Date(r.subscription_expires_at)<=new Date()){db.prepare('UPDATE admin_roles SET active=0 WHERE user_id=?').run(r.user_id);return res.status(403).json({error:'admin_subscription_expired'})}res.json({token:adminTokenFor(r),role:r.role,label:ADMIN_POLICY[r.role].label,icon:ADMIN_POLICY[r.role].icon,subscriptionExpiresAt:r.subscription_expires_at||'',permissions:ADMIN_POLICY[r.role].permissions});});
app.post('/api/admin/founder-code',auth,(req,res)=>{if(req.user?.wethaqId!==OWNER_WETHAQ_ID)return res.status(403).json({error:'founder_only'});const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.sub);if(!u)return res.status(404).json({error:'user_not_found'});const code=newAdminCode();db.prepare(`INSERT INTO admin_roles(user_id,role,code_hash,subscription_expires_at,appointed_by,appointed_by_role,appointed_at,active,code_version) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET role='founder',code_hash=excluded.code_hash,subscription_expires_at=NULL,appointed_by=NULL,appointed_by_role=NULL,appointed_at=excluded.appointed_at,active=1,code_version=admin_roles.code_version+1`).run(u.id,'founder',hashAdminCode(code),null,null,null,now(),1,1);audit(u.id,u.id,'founder_code_issued','founder','bootstrap');res.json({ok:true,adminCode:code,role:'founder',label:ADMIN_POLICY.founder.label});});
app.get('/api/admin/role',adminAuth,(req,res)=>{const p=ADMIN_POLICY[req.adminRow.role];res.json({role:req.adminRow.role,label:p.label,icon:p.icon,fee:p.fee,subscriptionExpiresAt:req.adminRow.subscription_expires_at||'',permissions:p.permissions,appoints:p.appoints,capacity:p.capacity});});
app.get('/api/admin/policy',(_req,res)=>{res.json({roles:Object.entries(ADMIN_POLICY).map(([role,p])=>({role,...p}))});});
app.get('/api/admin/structure',(_req,res)=>{const roles=Object.entries(ADMIN_POLICY).map(([role,p])=>{const members=db.prepare(`SELECT ar.role,ar.appointed_at,ar.appointed_by,u.name,u.wethaq_id,u.birth_year,au.name appointed_by_name,ar.appointed_by_role FROM admin_roles ar JOIN users u ON u.id=ar.user_id LEFT JOIN users au ON au.id=ar.appointed_by WHERE ar.role=? AND ar.active=1 ORDER BY ar.appointed_at ASC`).all(role);return{role,label:p.label,icon:p.icon,fee:p.fee,capacity:p.capacity,activeCount:members.length,members:members.map(publicAdminMember)};});res.json({roles});});
app.post('/api/admin/assign',adminAuth,(req,res)=>{const targetId=String(req.body?.wethaqId||'').trim(),targetRole=String(req.body?.role||'').trim();if(!ADMIN_POLICY[targetRole]||!targetId)return res.status(400).json({error:'invalid_assignment'});if(!canAssign(req.adminRow.role,targetRole))return res.status(403).json({error:'assignment_not_allowed'});const target=db.prepare('SELECT id,name,wethaq_id,birth_year FROM users WHERE wethaq_id=?').get(targetId);if(!target)return res.status(404).json({error:'user_not_found'});if(target.wethaq_id===OWNER_WETHAQ_ID||targetRole==='founder')return res.status(403).json({error:'founder_protected'});const existing=activeAdminRole(target.id);if(existing)return res.status(409).json({error:'already_admin',role:existing.role});const policy=ADMIN_POLICY[targetRole];if(policy.capacity!==null){const count=db.prepare('SELECT COUNT(*) n FROM admin_roles WHERE role=? AND active=1').get(targetRole).n;if(count>=policy.capacity)return res.status(409).json({error:'role_capacity_reached',capacity:policy.capacity})}if(req.adminRow.role==='deputy1'&&targetRole==='admin_member'){const count=db.prepare('SELECT COUNT(*) n FROM admin_roles WHERE role=? AND active=1 AND appointed_by=?').get('admin_member',req.adminRow.user_id).n;if(count>=3)return res.status(409).json({error:'deputy1_admin_member_quota_reached',capacity:3})}const code=newAdminCode(),expires=targetRole==='founder'?null:new Date(Date.now()+365*24*60*60*1000).toISOString();const tx=db.transaction(()=>{db.prepare(`INSERT INTO admin_roles(user_id,role,code_hash,subscription_expires_at,appointed_by,appointed_by_role,appointed_at,active,code_version) VALUES(?,?,?,?,?,?,?,?,1)`).run(target.id,targetRole,hashAdminCode(code),expires,req.adminRow.user_id,req.adminRow.role,now(),1);audit(req.adminRow.user_id,target.id,'assign',targetRole,`code_version=1`);});tx();const actor={id:req.adminRow.user_id,name:req.adminRow.name,role:req.adminRow.role};sendAdminAppointmentMessage(target,assignmentCard(target,targetRole,code,actor));res.status(201).json({ok:true,user:{name:target.name,wethaq_id:target.wethaq_id},role:targetRole,label:policy.label,adminCode:code,subscriptionExpiresAt:expires||''});});
app.post('/api/admin/remove-role',adminAuth,(req,res)=>{const targetId=String(req.body?.wethaqId||'').trim(),target=db.prepare('SELECT id,name,wethaq_id FROM users WHERE wethaq_id=?').get(targetId);if(!target)return res.status(404).json({error:'user_not_found'});const current=activeAdminRole(target.id);if(!current)return res.status(404).json({error:'admin_role_not_found'});if(!canManageTarget(req.adminRow.role,current.role))return res.status(403).json({error:'removal_not_allowed'});db.prepare('UPDATE admin_roles SET active=0 WHERE user_id=?').run(target.id);audit(req.adminRow.user_id,target.id,'remove_role',current.role,'');res.json({ok:true});});
app.post('/api/admin/rbac/ban',adminAuth,(req,res)=>{const targetId=String(req.body?.wethaqId||'').trim(),minutes=Math.max(0,Number(req.body?.minutes||0)),reason=safeMessage(req.body?.reason||'بقرار من إدارة وَثاق');const target=db.prepare('SELECT id,name,wethaq_id FROM users WHERE wethaq_id=?').get(targetId);if(!target)return res.status(404).json({error:'user_not_found'});if(target.wethaq_id===OWNER_WETHAQ_ID)return res.status(403).json({error:'cannot_ban_founder'});const tr=activeAdminRole(target.id);const targetRole=tr?.role||'user';if(!canManageTarget(req.adminRow.role,targetRole))return res.status(403).json({error:'ban_scope_denied'});if(req.adminRow.role==='admin_member'&&minutes===0)return res.status(403).json({error:'admin_member_temporary_only'});db.prepare('DELETE FROM bans WHERE user_id=?').run(target.id);const type=minutes>0?'temporary':'permanent',expires=minutes>0?new Date(Date.now()+minutes*60000).toISOString():null;db.prepare('INSERT INTO bans(user_id,ban_type,expires_at,reason,created_by) VALUES(?,?,?,?,?)').run(target.id,type,expires,reason,req.adminRow.user_id);audit(req.adminRow.user_id,target.id,'ban',req.adminRow.role,JSON.stringify({minutes,reason}));res.json({ok:true,ban_type:type,expires_at:expires});});
app.post('/api/admin/alert',adminAuth,(req,res)=>{const targetId=String(req.body?.wethaqId||'').trim(),message=safeMessage(req.body?.message||'تنبيه من إدارة وَثاق');const target=db.prepare('SELECT id,name,wethaq_id FROM users WHERE wethaq_id=?').get(targetId);if(!target)return res.status(404).json({error:'user_not_found'});const tr=activeAdminRole(target.id),targetRole=tr?.role||'user';if(!canManageTarget(req.adminRow.role,targetRole))return res.status(403).json({error:'alert_scope_denied'});const founder=db.prepare('SELECT id,wethaq_id,name FROM users WHERE wethaq_id=?').get(OWNER_WETHAQ_ID);const sender=db.prepare('SELECT id,wethaq_id,name FROM users WHERE id=?').get(req.adminRow.user_id);const body=`⚠️ تنبيه إداري من وَثاق\n\n${message}\n\nالمرسل: ${sender?.name||'إدارة وَثاق'} — ${ADMIN_POLICY[req.adminRow.role]?.label||req.adminRow.role}`;if(founder&&target.id===founder.id)return res.status(403).json({error:'founder_protected'});const z=db.prepare("INSERT INTO messages(sender_id,receiver_id,body,status,message_type) VALUES(?,?,?,?,'admin_alert')").run(sender.id,target.id,body,isOnline(target.id)?'delivered':'sent');const saved=db.prepare('SELECT * FROM messages WHERE id=?').get(z.lastInsertRowid);pushMessage(saved,sender,target);audit(req.adminRow.user_id,target.id,'alert',req.adminRow.role,message);res.status(201).json({ok:true});});
app.get('/api/admin/audit-log',adminAuth,(req,res)=>{const rows=db.prepare(`SELECT l.*,a.name actor_name,t.name target_name FROM admin_audit_log l LEFT JOIN users a ON a.id=l.actor_user_id LEFT JOIN users t ON t.id=l.target_user_id ORDER BY l.id DESC LIMIT 200`).all();res.json({logs:rows});});

server.listen(PORT,'0.0.0.0',()=>console.log(`Wethaq backend listening on ${PORT}`));
