plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wethaq.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wethaq.app'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '2.0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}
