package com.wethaq.finalapp;

import android.app.Activity;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.*;
import java.net.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    private static final String BASE="https://wethaq-backend-production.up.railway.app";
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private android.content.SharedPreferences prefs;
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);}
    private LinearLayout root(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(12),dp(16),dp(12));r.setBackgroundColor(Color.rgb(246,249,250));r.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return r;}
    private TextView label(String s,float size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(Color.rgb(18,38,48));v.setGravity(Gravity.CENTER_VERTICAL);v.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return v;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(16);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);e.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);return e;}
    private Button btn(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setOnClickListener(l);return b;}
    private void add(LinearLayout r,View v,int h){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(h));p.setMargins(0,dp(5),0,dp(5));r.addView(v,p);}
    private void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("wethaq",MODE_PRIVATE);home();}
    private void home(){LinearLayout r=root();TextView title=label("وَثاق",28);title.setTypeface(null,1);add(r,title,50);String id=prefs.getString("id","");String name=prefs.getString("name","");add(r,label(name.isEmpty()?"مرحبًا بك في وَثاق":"مرحبًا، "+name,19),44);if(!id.isEmpty())add(r,label("@"+id,17),40);EditText q=field("اسم المستخدم أو المعرف");add(r,q,54);add(r,btn("بحث",v->search(q.getText().toString())),52);add(r,btn("إنشاء هوية / تسجيل الدخول",v->identity()),52);add(r,btn("جهات الاتصال المحفوظة",v->contacts()),52);add(r,btn("ملفي",v->profile()),52);setContentView(r);}
    private void identity(){LinearLayout r=root();add(r,label("هوية وَثاق",27),52);EditText n=field("الاسم الثلاثي");EditText y=field("سنة الميلاد");y.setInputType(InputType.TYPE_CLASS_NUMBER);add(r,n,54);add(r,y,54);add(r,btn("إنشاء / تسجيل",v->{String name=n.getText().toString().trim();String year=y.getText().toString().trim();if(name.split("\\s+").length<3||year.length()!=4){toast("أدخل الاسم الثلاثي وسنة الميلاد");return;}JSONObject data=new JSONObject();try{data.put("name",name);data.put("birthYear",Integer.parseInt(year));data.put("deviceKey",deviceKey());}catch(Exception e){return;}request("POST","/api/identity",data,false,(ok,out)->{if(!ok){toast("تعذر إنشاء الهوية. حاول مرة أخرى.");return;}try{JSONObject u=out.optJSONObject("user");if(u==null)u=out;String id=u.optString("wethaq_id",u.optString("id"));String token=out.optString("token","");if(id.isEmpty()||token.isEmpty()){toast("استجابة الخادم غير مكتملة");return;}prefs.edit().putString("name",u.optString("name",name)).putString("id",id).putString("token",token).apply();runOnUiThread(this::home);}catch(Exception e){toast("تعذر حفظ الهوية");}});}),54);add(r,btn("رجوع",v->home()),50);setContentView(r);}
    private void search(String q){q=q.trim().replace("@","");if(q.length()<2){toast("اكتب اسمًا أو معرفًا");return;}String encoded;try{encoded=URLEncoder.encode(q,"UTF-8");}catch(Exception e){return;}request("GET","/api/search?q="+encoded,null,false,(ok,out)->{if(!ok){toast("تعذر البحث الآن");return;}runOnUiThread(()->results(out.optJSONArray("users")));});}
    private void results(JSONArray a){LinearLayout r=root();add(r,label("نتائج البحث",26),50);if(a==null||a.length()==0)add(r,label("لم يتم العثور على مستخدم.",16),60);for(int i=0;i<(a==null?0:a.length());i++){JSONObject u=a.optJSONObject(i);if(u==null)continue;String id=u.optString("wethaq_id",u.optString("id"));String name=u.optString("name","مستخدم وَثاق");add(r,label(name+"\n@"+id,16),70);if(!id.isEmpty())add(r,btn("حفظ ومراسلة",v->{saveContact(id,name);chat(id,name);}),50);}add(r,btn("رجوع",v->home()),50);setContentView(r);}
    private void saveContact(String id,String name){try{JSONArray a=new JSONArray(prefs.getString("contacts","[]"));boolean found=false;for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("id")))found=true;if(!found)a.put(new JSONObject().put("id",id).put("name",name));prefs.edit().putString("contacts",a.toString()).apply();}catch(Exception ignored){}}
    private void contacts(){LinearLayout r=root();add(r,label("جهات الاتصال",26),50);try{JSONArray a=new JSONArray(prefs.getString("contacts","[]"));if(a.length()==0)add(r,label("لا توجد جهات اتصال محفوظة.",16),60);for(int i=0;i<a.length();i++){JSONObject u=a.optJSONObject(i);String id=u.optString("id"),name=u.optString("name");add(r,label(name+"\n@"+id,16),65);add(r,btn("مراسلة",v->chat(id,name)),48);}}catch(Exception ignored){}add(r,btn("رجوع",v->home()),50);setContentView(r);}
    private void profile(){LinearLayout r=root();add(r,label("ملفي",26),50);add(r,label(prefs.getString("name","غير مسجل"),20),48);add(r,label("@"+prefs.getString("id",""),18),44);add(r,btn("نسخ المعرف",v->{ClipboardManager c=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("Wethaq ID",prefs.getString("id","")));toast("تم نسخ المعرف");}),52);add(r,btn("تسجيل الخروج",v->{prefs.edit().clear().apply();home();}),52);add(r,btn("رجوع",v->home()),50);setContentView(r);}
    private void chat(String id,String name){LinearLayout r=root();add(r,label(name+"  @"+id,22),54);LinearLayout messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(this);scroll.addView(messages);r.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));EditText input=field("اكتب رسالتك");add(r,input,54);add(r,btn("إرسال",v->{String body=input.getText().toString().trim();if(body.isEmpty())return;input.setText("");TextView m=label(body+"\nجاري الإرسال",15);add(messages,m,60);send(id,body,m);}),52);add(r,btn("رجوع",v->contacts()),48);setContentView(r);}
    private void send(String id,String body,TextView view){if(!hasNetwork()){queue(id,body);view.setText(body+"\nمحفوظة محليًا");return;}try{JSONObject d=new JSONObject().put("to",id).put("body",body);request("POST","/api/messages",d,true,(ok,o)->runOnUiThread(()->{if(ok)view.setText(body+"\nتم الإرسال");else{queue(id,body);view.setText(body+"\nمحفوظة محليًا");}}));}catch(Exception e){queue(id,body);}}
    private void queue(String id,String body){try{JSONArray a=new JSONArray(prefs.getString("pending","[]"));a.put(new JSONObject().put("to",id).put("body",body));prefs.edit().putString("pending",a.toString()).apply();}catch(Exception ignored){}}
    private boolean hasNetwork(){return ((android.net.ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE)).getActiveNetwork()!=null;}
    private String deviceKey(){String k=prefs.getString("deviceKey","");if(k.isEmpty()){k=java.util.UUID.randomUUID().toString().replace("-","");prefs.edit().putString("deviceKey",k).apply();}return k;}
    private interface Callback{void done(boolean ok,JSONObject out);}
    private void request(String method,String path,JSONObject data,boolean auth,Callback cb){io.execute(()->{HttpURLConnection c=null;try{URL u=new URL(BASE+path);c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(20000);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");if(auth&&!prefs.getString("token","").isEmpty())c.setRequestProperty("Authorization","Bearer "+prefs.getString("token",""));if("POST".equals(method)){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");byte[] bytes=data.toString().getBytes("UTF-8");c.getOutputStream().write(bytes);}int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();StringBuilder s=new StringBuilder();if(in!=null){BufferedReader br=new BufferedReader(new InputStreamReader(in,"UTF-8"));String line;while((line=br.readLine())!=null)s.append(line);}JSONObject out;try{out=new JSONObject(s.toString());}catch(Exception e){out=new JSONObject();}cb.done(code>=200&&code<300,out);}catch(Exception e){cb.done(false,new JSONObject());}finally{if(c!=null)c.disconnect();}});}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
