package com.wethaq.app;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.widget.*;
import android.content.SharedPreferences;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import org.json.*;

public final class AdminAccessActivity extends Activity {
    private static final String API="https://wethaq-backend-production.up.railway.app";
    private SharedPreferences prefs; private LinearLayout root,content;
    private String adminToken="", selectedId="", selectedRole="";
    private EditText targetName,targetBirth,targetPersonal; private TextView targetStatus;
    private int gold(){return Color.rgb(212,175,55);} private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(12),dp(10),dp(12),dp(10));return t;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setTextSize(17);e.setSingleLine(true);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setPadding(dp(14),0,dp(14),0);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(24,24,27));d.setCornerRadius(dp(14));d.setStroke(dp(2),Color.rgb(75,75,80));e.setBackground(d);e.setMinHeight(dp(62));return e;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(17);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setStateListAnimator(null);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(28,28,32));d.setCornerRadius(dp(14));d.setStroke(dp(2),gold());b.setBackground(d);b.setMinHeight(dp(62));return b;}
    private LinearLayout card(String title){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(14));GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(22,22,25));d.setCornerRadius(dp(18));d.setStroke(dp(2),gold());box.setBackground(d);TextView h=tv(title,20,gold());h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setGravity(Gravity.CENTER);box.addView(h,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);box.setLayoutParams(p);return box;}
    private void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(14));root.setBackgroundColor(Color.BLACK);TextView h=tv("👑 لوحة تحكم المؤسس — وَثاق",23,gold());h.setGravity(Gravity.CENTER);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(h,new LinearLayout.LayoutParams(-1,dp(68)));ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("wethaq",MODE_PRIVATE);adminToken=prefs.getString("admin_token","");if(isOwner()){founderSession();}else if(!adminToken.isEmpty()){loadRole();}else{showAdminLogin();}}
    private boolean isOwner(){return "Hatem_Hussin_Al_Haj_Ramadan1995".equals(prefs.getString("wethaq_id",""));}
    private void founderSession(){request("POST","/api/admin/founder-code",null,prefs.getString("token",""),r->{try{JSONObject z=new JSONObject(r);String code=z.getString("adminCode");JSONObject q=new JSONObject();q.put("name",prefs.getString("name",""));q.put("birthYear",Integer.parseInt(prefs.getString("birth_year","0")));q.put("adminCode",code);request("POST","/api/admin/login",q.toString(),null,login->{try{JSONObject a=new JSONObject(login);adminToken=a.getString("token");prefs.edit().putString("admin_token",adminToken).putString("admin_role","founder").apply();loadRole();}catch(Exception e){showAdminLogin();}});}catch(Exception e){showAdminLogin();}});}
    private void showAdminLogin(){base();content.addView(tv("دخول أصحاب المناصب بعد التعيين",19,Color.WHITE));EditText n=field("الاسم الثلاثي"),y=field("سنة الميلاد"),c=field("الرمز السري للمنصب");y.setInputType(InputType.TYPE_CLASS_NUMBER);c.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(n);content.addView(y);content.addView(c);Button l=btn("🔐 دخول لوحة المنصب"),back=btn("رجوع");content.addView(l);content.addView(back);l.setOnClickListener(v->adminLogin(n.getText().toString().trim(),y.getText().toString().trim(),c.getText().toString().trim()));back.setOnClickListener(v->finish());}
    private void adminLogin(String n,String y,String c){if(n.split("\\s+").length<3){toast("اكتب الاسم الثلاثي");return;}try{JSONObject q=new JSONObject();q.put("name",n);q.put("birthYear",Integer.parseInt(y));q.put("adminCode",c);request("POST","/api/admin/login",q.toString(),null,r->{try{JSONObject z=new JSONObject(r);adminToken=z.getString("token");prefs.edit().putString("admin_token",adminToken).putString("admin_role",z.optString("role")).apply();loadRole();}catch(Exception e){toast("بيانات الدخول غير صحيحة");}});}catch(Exception e){toast("سنة الميلاد غير صحيحة");}}
    private void loadRole(){request("GET","/api/admin/role",null,adminToken,r->{try{showPanel(new JSONObject(r));}catch(Exception e){prefs.edit().remove("admin_token").apply();adminToken="";if(isOwner())founderSession();else showAdminLogin();}});}
    private void showPanel(JSONObject role){base();String rk=role.optString("role");TextView status=tv("المنصب: "+role.optString("icon")+" "+role.optString("label")+"\nالصلاحيات: "+role.optJSONArray("permissions")+"\nانتهاء الصلاحية: "+(role.optString("subscriptionExpiresAt").isEmpty()?"بلا انتهاء":role.optString("subscriptionExpiresAt")),16,Color.WHITE);content.addView(status,new LinearLayout.LayoutParams(-1,-2));if("founder".equals(rk)){addUserControlCard();addAssignmentCard(role);addAuditCards();}else{addAssignmentCard(role);addAuditCards();}Button logout=btn("🚪 خروج من لوحة المنصب");content.addView(logout);logout.setOnClickListener(v->{prefs.edit().remove("admin_token").remove("admin_role").apply();adminToken="";if(isOwner())founderSession();else finish();});}
    private void addUserControlCard(){LinearLayout box=card("🛡 البطاقة الأولى — إدارة المستخدم");targetName=field("الاسم الثلاثي للمستخدم");targetBirth=field("المواليد / سنة الميلاد");targetBirth.setInputType(InputType.TYPE_CLASS_NUMBER);box.addView(targetName);box.addView(targetBirth);Button find=btn("🔎 بحث عن المستخدم");box.addView(find);targetStatus=tv("لم يتم اختيار مستخدم.",15,Color.WHITE);box.addView(targetStatus);LinearLayout row1=new LinearLayout(this);row1.setOrientation(LinearLayout.HORIZONTAL);Button ban=btn("حظر"),temp=btn("حظر مؤقت");row1.addView(ban,new LinearLayout.LayoutParams(0,dp(64),1));row1.addView(temp,new LinearLayout.LayoutParams(0,dp(64),1));box.addView(row1);LinearLayout row2=new LinearLayout(this);row2.setOrientation(LinearLayout.HORIZONTAL);Button warn=btn("تنبيه"),unban=btn("إزالة حظر");row2.addView(warn,new LinearLayout.LayoutParams(0,dp(64),1));row2.addView(unban,new LinearLayout.LayoutParams(0,dp(64),1));box.addView(row2);find.setOnClickListener(v->findTarget());ban.setOnClickListener(v->banTarget(0));temp.setOnClickListener(v->temporaryBanDialog());warn.setOnClickListener(v->warnTarget());unban.setOnClickListener(v->unbanTarget());content.addView(box);}
    private void findTarget(){String q=targetName.getText().toString().trim();if(q.length()<2){toast("أدخل الاسم الثلاثي ثم ابحث");return;}request("GET","/api/admin/users?q="+enc(q),null,adminToken,r->{try{JSONArray a=new JSONObject(r).optJSONArray("users");if(a==null||a.length()==0){targetStatus.setText("❌ لم يتم العثور على المستخدم");return;}JSONObject u=a.getJSONObject(0);selectedId=u.optString("wethaq_id");targetName.setText(u.optString("name"));targetBirth.setText(u.optString("birth_year"));JSONObject b=u.optJSONObject("ban");targetStatus.setText("👤 "+u.optString("name")+"\n🆔 "+selectedId+"\nالحالة: "+(b==null?"نشط":"محظور"));}catch(Exception e){toast("تعذر قراءة المستخدم");}});}
    private void temporaryBanDialog(){final EditText m=field("مدة الحظر بالدقائق");m.setInputType(InputType.TYPE_CLASS_NUMBER);new AlertDialog.Builder(this).setTitle("حظر مؤقت").setView(m).setPositiveButton("تنفيذ",(d,w)->{try{banTarget(Integer.parseInt(m.getText().toString().trim()));}catch(Exception e){toast("أدخل مدة صحيحة");}}).setNegativeButton("إلغاء",null).show();}
    private void banTarget(int minutes){if(selectedId.isEmpty()){toast("ابحث عن المستخدم أولًا");return;}try{JSONObject q=new JSONObject();q.put("wethaqId",selectedId);q.put("minutes",minutes);q.put("reason",minutes>0?"حظر مؤقت بقرار من المؤسس":"حظر دائم بقرار من المؤسس");request("POST","/api/admin/rbac/ban",q.toString(),adminToken,r->{targetStatus.setText("🚫 تم تنفيذ الحظر\n"+selectedId+(minutes>0?"\nالمدة: "+minutes+" دقيقة":"\nحظر دائم"));toast("تم تنفيذ الحظر ✓");});}catch(Exception e){toast("فشل الحظر");}}
    private void unbanTarget(){if(selectedId.isEmpty()){toast("اختر مستخدمًا أولًا");return;}try{JSONObject q=new JSONObject();q.put("wethaqId",selectedId);request("POST","/api/admin/unban",q.toString(),adminToken,r->{targetStatus.setText("✅ تم إزالة الحظر عن "+selectedId);toast("تمت إزالة الحظر ✓");});}catch(Exception e){}}
    private void warnTarget(){if(selectedId.isEmpty()){toast("اختر مستخدمًا أولًا");return;}final EditText msg=field("رسالة التنبيه");new AlertDialog.Builder(this).setTitle("تنبيه المستخدم").setView(msg).setPositiveButton("إرسال",(d,w)->{try{JSONObject q=new JSONObject();q.put("wethaqId",selectedId);q.put("message",msg.getText().toString().trim());request("POST","/api/admin/alert",q.toString(),adminToken,r->toast("تم إرسال التنبيه ✓"));}catch(Exception e){toast("فشل التنبيه");}}).setNegativeButton("إلغاء",null).show();}
    private void addAssignmentCard(JSONObject role){LinearLayout box=card("📋 البطاقة الثانية — التعيين الإداري");EditText name=field("الاسم الثلاثي للمستخدم");EditText birth=field("المواليد / سنة الميلاد");targetPersonal=field("الرقم الشخصي (6-12 أرقام)");birth.setInputType(InputType.TYPE_CLASS_NUMBER);targetPersonal.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);box.addView(name);box.addView(birth);box.addView(targetPersonal);Button find=btn("🔎 التحقق من المستخدم");box.addView(find);Spinner sp=new Spinner(this);java.util.ArrayList<String> labels=new java.util.ArrayList<>(),keys=new java.util.ArrayList<>();labels.add("اختر المنصب");keys.add("");JSONArray allowed=role.optJSONArray("appoints");String[][] all={{"executive","🏛 المدير التنفيذي"},{"deputy1","🥇 النائب الأول"},{"deputy2","🥈 النائب الثاني"},{"deputy3","🥉 النائب الثالث"},{"supervisor","🛡 المشرف"},{"admin_member","👥 عضو الإدارة"},{"premium","⭐ عضو مميز"}};for(String[] x:all){if(allowed!=null&&allowed.toString().contains("\""+x[0]+"\"")){keys.add(x[0]);labels.add(x[1]);}}ArrayAdapter<String> a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,labels){public android.view.View getView(int p,android.view.View v,android.view.ViewGroup g){TextView t=(TextView)super.getView(p,v,g);t.setTextColor(Color.WHITE);t.setGravity(Gravity.RIGHT);return t;}public android.view.View getDropDownView(int p,android.view.View v,android.view.ViewGroup g){TextView t=(TextView)super.getDropDownView(p,v,g);t.setTextColor(Color.WHITE);t.setBackgroundColor(Color.DKGRAY);return t;}};sp.setAdapter(a);box.addView(sp,new LinearLayout.LayoutParams(-1,dp(62)));sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,android.view.View v,int pos,long id){selectedRole=keys.get(pos);}public void onNothingSelected(android.widget.AdapterView<?> p){selectedRole="";}});Button confirm=btn("📌 تثبيت التعيين");box.addView(confirm);TextView result=tv("رمز المنصب سيُنشأ بعد التثبيت ويُرسل للمستخدم داخل وَثاق.\nالرمز لا يُعرض في السجل العام.",15,Color.WHITE);box.addView(result);find.setOnClickListener(v->findAssignmentUser(name,birth,targetPersonal,result));confirm.setOnClickListener(v->assign(name,birth,targetPersonal,result));content.addView(box);}
    private void findAssignmentUser(EditText n,EditText b,EditText p,TextView result){String q=n.getText().toString().trim();if(q.length()<2){toast("أدخل الاسم الثلاثي");return;}request("GET","/api/admin/users?q="+enc(q),null,adminToken,r->{try{JSONArray a=new JSONObject(r).optJSONArray("users");if(a==null||a.length()==0){result.setText("❌ المستخدم غير موجود");return;}JSONObject u=a.getJSONObject(0);selectedId=u.optString("wethaq_id");n.setText(u.optString("name"));b.setText(u.optString("birth_year"));result.setText("✅ تم التحقق\n👤 "+u.optString("name")+"\n🆔 "+selectedId+"\nالرقم الشخصي مطلوب للتثبيت ولا يتم عرضه لاحقًا.");}catch(Exception e){toast("تعذر التحقق");}});}
    private void assign(EditText n,EditText b,EditText p,TextView result){if(selectedId.isEmpty()||selectedRole.isEmpty()){toast("تحقق من المستخدم واختر المنصب");return;}try{JSONObject q=new JSONObject();q.put("wethaqId",selectedId);q.put("name",n.getText().toString().trim());q.put("birthYear",Integer.parseInt(b.getText().toString().trim()));q.put("personalCode",p.getText().toString().trim());q.put("role",selectedRole);request("POST","/api/admin/assign",q.toString(),adminToken,r->{try{JSONObject z=new JSONObject(r);String code=z.optString("adminCode");result.setText("✅ تم تثبيت التعيين رسميًا\n👤 "+z.optJSONObject("user").optString("name")+"\n🎖 "+z.optString("label")+"\n🔐 الرقم السري للمنصب: "+code+"\n\nأرسل هذا الرقم السري للمستخدم عبر وَثاق.\nالرقم الشخصي لا يتم إظهاره أو تخزينه كنص صريح.");new AlertDialog.Builder(this).setTitle("تم التعيين").setMessage("تم إنشاء رمز المنصب السري:\n\n"+code+"\n\nأرسله للمستخدم ليستخدمه مع اسمه ومواليده للدخول إلى لوحة منصبه.").setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل قراءة نتيجة التعيين");}});}catch(Exception e){toast("بيانات التعيين غير صحيحة");}}
    private void addAuditCards(){Button login=btn("👤 سجل دخول المستخدمين"),pos=btn("🏛 سجل المناصب والتعيينات"),structure=btn("📊 الهيكل الإداري العام");content.addView(login);content.addView(pos);content.addView(structure);login.setOnClickListener(v->history("/api/admin/login-history?limit=200","سجل دخول المستخدمين"));pos.setOnClickListener(v->history("/api/admin/position-history?limit=200","سجل المناصب والتعيينات"));structure.setOnClickListener(v->historyPublic());}
    private void history(String path,String title){request("GET",path,null,adminToken,r->showText(title,r));}
    private void historyPublic(){request("GET","/api/admin/structure",null,adminToken,r->showText("الهيكل الإداري",r));}
    private void showText(String title,String raw){try{JSONObject z=new JSONObject(raw);new AlertDialog.Builder(this).setTitle(title).setMessage(z.toString(2)).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("تعذر عرض السجل");}}
    private String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return "";}}
    private interface CB{void ok(String s);}private void request(String method,String path,String body,String token,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");if(token!=null&&!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(in!=null){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);in.close();}String s=new String(out.toByteArray(),StandardCharsets.UTF_8);runOnUiThread(()->{if(code>=200&&code<300)cb.ok(s);else toast("فشل: "+error(s));});}catch(Exception e){runOnUiThread(()->toast("تعذر الاتصال بالخادم"));}}).start();}
    private String error(String s){try{return new JSONObject(s).optString("error",s);}catch(Exception e){return "الطلب مرفوض";}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
