package com.wethaq.app;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import org.json.*;
public final class AdminActivity extends Activity{
 private static final String API="https://wethaq-backend-production.up.railway.app";private LinearLayout root;private EditText q,minutes,reason;private String token;
 private int gold(){return Color.rgb(212,175,55);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private Button b(String s){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(19);x.setAllCaps(false);x.setTypeface(Typeface.DEFAULT,1);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(28,28,28));d.setCornerRadius(dp(14));d.setStroke(dp(3),gold());x.setBackground(d);x.setMinHeight(dp(70));return x;}private EditText f(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setTextSize(18);e.setSingleLine(true);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(25,25,25));d.setCornerRadius(dp(14));d.setStroke(dp(2),Color.DKGRAY);e.setBackground(d);e.setPadding(dp(12),0,dp(12),0);return e;}
 public void onCreate(Bundle x){super.onCreate(x);token=getSharedPreferences("wethaq",MODE_PRIVATE).getString("token","");String id=getSharedPreferences("wethaq",MODE_PRIVATE).getString("wethaq_id","");if(!"Hatem_Hussin_Al_Haj_Ramadan1995".equals(id)){finish();return;}root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(16));root.setBackgroundColor(Color.BLACK);TextView t=new TextView(this);t.setText("🛡 لوحة تحكم المؤسس");t.setTextColor(gold());t.setTextSize(24);t.setGravity(17);root.addView(t,new LinearLayout.LayoutParams(-1,dp(70)));q=f("اسم المستخدم أو معرف وَثاق");minutes=f("مدة الحظر بالدقائق — 0 = نهائي");reason=f("سبب الحظر");root.addView(q,new LinearLayout.LayoutParams(-1,dp(64)));root.addView(minutes,new LinearLayout.LayoutParams(-1,dp(64)));root.addView(reason,new LinearLayout.LayoutParams(-1,dp(64)));Button stats=b("📊 حالة النظام والإحصائيات"),audit=b("🧾 سجل التدقيق الأمني"),search=b("بحث عن المستخدمين"),ban=b("حظر المدة المحددة"),perm=b("حظر نهائي"),unban=b("إلغاء الحظر"),complaints=b("عرض الشكاوى"),back=b("رجوع");root.addView(stats);root.addView(audit);root.addView(search);root.addView(ban);root.addView(perm);root.addView(unban);root.addView(complaints);root.addView(back);setContentView(root);stats.setOnClickListener(v->stats());audit.setOnClickListener(v->audit());search.setOnClickListener(v->users());ban.setOnClickListener(v->ban(false));perm.setOnClickListener(v->ban(true));unban.setOnClickListener(v->unban());complaints.setOnClickListener(v->complaints());back.setOnClickListener(v->finish());}
 private void stats(){req("GET","/api/admin/stats",null,r->{try{JSONObject s=new JSONObject(r);String text="المستخدمون: "+s.optInt("users")+"\nالنشطون آخر 5 دقائق: "+s.optInt("active")+"\nالرسائل: "+s.optInt("messages")+"\nإشارات المكالمات: "+s.optInt("calls")+"\nالشكاوى المفتوحة: "+s.optInt("open_complaints")+"\nالمحظورون: "+s.optInt("banned")+"\nاتصالات WebSocket النشطة: "+s.optInt("websocket_online")+"\nوقت الخادم: "+s.optString("server_time");new AlertDialog.Builder(this).setTitle("مؤشرات وَثاق").setMessage(text).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل قراءة الإحصائيات");}});}
 private void audit(){req("GET","/api/admin/audit-logs",null,r->{try{JSONArray a=new JSONObject(r).optJSONArray("logs");StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);s.append("#").append(x.optInt("id")).append(" — ").append(x.optString("action")).append("\nالفاعل: ").append(x.optInt("actor_user_id")).append(" الهدف: ").append(x.optInt("target_user_id")).append("\n").append(x.optString("created_at")).append("\n\n");}new AlertDialog.Builder(this).setTitle("سجل التدقيق").setMessage(s.length()==0?"لا توجد سجلات":s.toString()).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل قراءة سجل التدقيق");}});}
 private void users(){req("GET","/api/admin/users?q="+enc(q.getText().toString()),null,r->{try{JSONArray a=new JSONObject(r).optJSONArray("users");StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject u=a.getJSONObject(i);s.append(u.optString("name")).append("\n").append(u.optString("wethaq_id")).append("\n\n");}new AlertDialog.Builder(this).setTitle("المستخدمون").setMessage(s.length()==0?"لا توجد نتائج":s.toString()).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل القراءة");}});}
 private void ban(boolean permanent){String id=q.getText().toString().trim();if(id.isEmpty()){toast("أدخل المعرف");return;}String m=permanent?"0":minutes.getText().toString().trim();JSONObject o=new JSONObject();try{o.put("wethaqId",id);o.put("minutes",m.isEmpty()?0:Integer.parseInt(m));o.put("reason",reason.getText().toString().trim());}catch(Exception e){toast("المدة غير صحيحة");return;}req("POST","/api/admin/ban",o.toString(),r->toast("تم تنفيذ الحظر ✓"));}
 private void unban(){JSONObject o=new JSONObject();try{o.put("wethaqId",q.getText().toString().trim());}catch(Exception ignored){}req("POST","/api/admin/unban",o.toString(),r->toast("تم إلغاء الحظر ✓"));}
 private void complaints(){req("GET","/api/admin/complaints",null,r->{try{JSONArray a=new JSONObject(r).optJSONArray("complaints");StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject c=a.getJSONObject(i);s.append("👤 ").append(c.optString("from_name")).append("\n").append(c.optString("message")).append("\n\n");}new AlertDialog.Builder(this).setTitle("الشكاوى").setMessage(s.length()==0?"لا توجد شكاوى":s.toString()).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل قراءة الشكاوى");}});}
 private String enc(String s){try{return URLEncoder.encode(s==null?"":""+s,"UTF-8");}catch(Exception e){return"";}}private interface CB{void ok(String s);}private void req(String m,String p,String body,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(API+p).openConnection();c.setRequestMethod(m);c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("Accept","application/json");if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream o=new ByteArrayOutputStream();if(in!=null){byte[] z=new byte[4096];int n;while((n=in.read(z))!=-1)o.write(z,0,n);in.close();}String s=new String(o.toByteArray(),StandardCharsets.UTF_8);runOnUiThread(()->{if(code>=200&&code<300)cb.ok(s);else toast("فشل: "+s);});}catch(Exception e){runOnUiThread(()->toast("تعذر الاتصال بالخادم"));}}).start();}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
