package com.wethaq.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import org.json.*;

public final class AdminActivity extends Activity{
 private static final String API="https://wethaq-backend-production.up.railway.app";private LinearLayout root,body;private EditText target,minutes,reason;private String token,role="";private boolean verified;
 private int gold(){return Color.rgb(212,175,55);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 private Button b(String s){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(17);x.setAllCaps(false);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(28,28,28));d.setCornerRadius(dp(14));d.setStroke(dp(2),gold());x.setBackground(d);x.setMinHeight(dp(64));x.setPadding(dp(8),0,dp(8),0);return x;}
 private EditText f(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setTextSize(17);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(25,25,25));d.setCornerRadius(dp(12));d.setStroke(dp(2),Color.DKGRAY);e.setBackground(d);e.setMinHeight(dp(60));return e;}
 @Override public void onCreate(Bundle x){super.onCreate(x);token=getSharedPreferences("wethaq",MODE_PRIVATE).getString("token","");if(token.isEmpty()){finish();return;}showLoading();req("GET","/api/admin/role",null,r->{try{JSONObject o=new JSONObject(r);role=o.optString("role","");if("founder".equals(role)){verified=true;render();}else verifyCode();}catch(Exception e){toast("لا تملك صلاحية الإدارة");finish();}});}
 private void verifyCode(){final EditText code=f("الرمز الإداري");final AlertDialog d=new AlertDialog.Builder(this).setTitle("التحقق الإداري").setMessage("أدخل الرمز الذي سلمه لك المدير العام.").setView(code).setCancelable(false).setNegativeButton("إلغاء",(z,w)->finish()).setPositiveButton("تحقق",null).create();d.setOnShowListener(v->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(vv->{String c=code.getText().toString().trim();if(c.isEmpty()){code.setError("أدخل الرمز");return;}JSONObject q=new JSONObject();try{q.put("code",c);}catch(Exception ignored){}req("POST","/api/admin/verify-code",q.toString(),r->{verified=true;d.dismiss();render();});}));d.show();}
 private void render(){if(!verified){finish();return;}root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(14));root.setBackgroundColor(Color.BLACK);TextView title=new TextView(this);title.setText("🛡 الإدارة — "+label(role));title.setTextColor(gold());title.setTextSize(23);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setGravity(Gravity.CENTER);root.addView(title,new LinearLayout.LayoutParams(-1,dp(70)));ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);loadStructure();target=f("معرف وَثاق للمستخدم");minutes=f("مدة الحظر بالدقائق — 0 = نهائي");reason=f("السبب");if("founder".equals(role)||"deputy1".equals(role)||"deputy2".equals(role)||"deputy3".equals(role)){body.addView(target,lp(-1,60,8));body.addView(minutes,lp(-1,60,8));body.addView(reason,lp(-1,60,8));}if("founder".equals(role))addFounderControls();else if("deputy1".equals(role)||"deputy2".equals(role)||"deputy3".equals(role))addModerationControls();Button complaints=b("📨 الشكاوى والتوجيه"),back=b("رجوع");body.addView(complaints,lp(-1,68,8));body.addView(back,lp(-1,68,12));complaints.setOnClickListener(v->complaints());back.setOnClickListener(v->finish());}
 private void addFounderControls(){TextView h=heading("👑 الهيكل الإداري");body.addView(h,lp(-1,-2,6));EditText assign=f("معرف المستخدم للتعيين");Spinner roles=new Spinner(this);String[] values={"نائب أول","نائب ثانٍ","نائب ثالث","عضو إدارة"};roles.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,values));Button assignBtn=b("تعيين وإصدار رمز إداري"),remove=b("إزالة التعيين");body.addView(assign,lp(-1,60,6));body.addView(roles,lp(-1,60,6));body.addView(assignBtn,lp(-1,68,6));body.addView(remove,lp(-1,68,10));assignBtn.setOnClickListener(v->{int p=roles.getSelectedItemPosition();String r=p==0?"deputy1":p==1?"deputy2":p==2?"deputy3":"admin_member";JSONObject q=new JSONObject();try{q.put("wethaqId",assign.getText().toString().trim());q.put("role",r);}catch(Exception ignored){}req("POST","/api/admin/assign",q.toString(),res->{try{JSONObject o=new JSONObject(res);new AlertDialog.Builder(this).setTitle("تم التعيين ✓").setMessage("المنصب: "+o.optString("role_label")+"\nالرمز الإداري:\n"+o.optString("admin_code")+"\n\nاحفظ الرمز وسلمه للشخص المعين بطريقة آمنة.").setPositiveButton("إغلاق",null).show();loadStructure();}catch(Exception e){toast("تم التعيين");}});});remove.setOnClickListener(v->{JSONObject q=new JSONObject();try{q.put("wethaqId",assign.getText().toString().trim());}catch(Exception ignored){}confirm("إزالة التعيين","هل أنت متأكد؟",()->req("POST","/api/admin/remove-role",q.toString(),r->{toast("تمت إزالة التعيين ✓");loadStructure();}));});}
 private void addModerationControls(){Button ban=b("🚫 حظر حسب الصلاحية"),alert=b("⚠️ إرسال تنبيه");body.addView(ban,lp(-1,68,6));body.addView(alert,lp(-1,68,10));ban.setOnClickListener(v->{boolean permanent=minutes.getText().toString().trim().isEmpty()||"0".equals(minutes.getText().toString().trim());confirm(permanent?"حظر نهائي":"حظر مؤقت",permanent?"هل أنت متأكد من الحظر النهائي؟":"تنفيذ الحظر؟",()->moderateBan());});alert.setOnClickListener(v->{JSONObject q=new JSONObject();try{q.put("wethaqId",target.getText().toString().trim());q.put("reason",reason.getText().toString().trim());}catch(Exception ignored){}req("POST","/api/admin/alert",q.toString(),r->toast("تم إرسال التنبيه ✓"));});}
 private void moderateBan(){JSONObject q=new JSONObject();try{q.put("wethaqId",target.getText().toString().trim());q.put("minutes",minutes.getText().toString().trim().isEmpty()?0:Integer.parseInt(minutes.getText().toString().trim()));q.put("reason",reason.getText().toString().trim());}catch(Exception e){toast("المدة غير صحيحة");return;}req("POST","/api/admin/rbac/ban",q.toString(),r->toast("تم تنفيذ الحظر ✓"));}
 private void loadStructure(){req("GET","/api/admin/structure",null,r->{try{JSONObject o=new JSONObject(r);StringBuilder s=new StringBuilder();JSONObject f=o.optJSONObject("founder");if(f!=null)s.append("👑 ").append(f.optString("name")).append(" — المؤسس\n\n");JSONObject d=o.optJSONObject("deputies");if(d!=null){s.append("النائب الأول: ").append(nameOf(d.optJSONObject("deputy1"))).append("\n");s.append("النائب الثاني: ").append(nameOf(d.optJSONObject("deputy2"))).append("\n");s.append("النائب الثالث: ").append(nameOf(d.optJSONObject("deputy3"))).append("\n\n");}JSONArray a=o.optJSONArray("members");s.append("👥 أعضاء الإدارة: ").append(a==null?0:a.length()).append("/10\n");if(a!=null)for(int i=0;i<a.length();i++)s.append(i+1).append(". ").append(a.optJSONObject(i).optString("name")).append("\n");TextView view=heading(s.toString());body.addView(view,1,lp(-1,-2,12));}catch(Exception ignored){}});}
 private String nameOf(JSONObject o){return o==null?"غير معين":o.optString("name","غير معروف");}
 private void complaints(){req("GET","/api/admin/complaints/rbac",null,r->{try{JSONArray a=new JSONObject(r).optJSONArray("complaints");StringBuilder s=new StringBuilder();if(a!=null)for(int i=0;i<a.length();i++){JSONObject c=a.getJSONObject(i);s.append("#").append(c.optInt("id")).append(" — ").append(c.optString("from_name")).append("\n").append(c.optString("message")).append("\nموجهة إلى: ").append(c.optString("assigned_name","غير موجهة")).append("\n\n");}new AlertDialog.Builder(this).setTitle("الشكاوى").setMessage(s.length()==0?"لا توجد شكاوى":s.toString()).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل قراءة الشكاوى");}});}
 private TextView heading(String s){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(17);t.setGravity(Gravity.RIGHT);t.setPadding(dp(8),dp(10),dp(8),dp(10));return t;}
 private LinearLayout.LayoutParams lp(int w,int h,int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.bottomMargin=dp(m);return p;}
 private String label(String r){return "founder".equals(r)?"المؤسس":"deputy1".equals(r)?"النائب الأول":"deputy2".equals(r)?"النائب الثاني":"deputy3".equals(r)?"النائب الثالث":"عضو الإدارة";}
 private void confirm(String title,String msg,Runnable action){new AlertDialog.Builder(this).setTitle(title).setMessage(msg).setNegativeButton("إلغاء",null).setPositiveButton("تأكيد",(d,w)->action.run()).show();}
 private void showLoading(){TextView t=new TextView(this);t.setText("جارٍ التحقق من الصلاحيات…");t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);setContentView(t);}
 private void setBusy(boolean busy){if(root==null)return;setBusyView(root,busy);}
 private void setBusyView(View v,boolean busy){if(v instanceof Button)v.setEnabled(!busy);if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)setBusyView(g.getChildAt(i),busy);}}
 private interface CB{void ok(String s);}private void req(String m,String p,String body,CB cb){runOnUiThread(()->setBusy(true));new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(API+p).openConnection();c.setRequestMethod(m);c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("Accept","application/json");if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream o=new ByteArrayOutputStream();if(in!=null){byte[] z=new byte[4096];int n;while((n=in.read(z))!=-1)o.write(z,0,n);in.close();}String s=new String(o.toByteArray(),StandardCharsets.UTF_8);runOnUiThread(()->{setBusy(false);if(code>=200&&code<300)cb.ok(s);else toast(error(code,s));});}catch(Exception e){runOnUiThread(()->{setBusy(false);toast("تعذر الاتصال بالخادم");});}}).start();}
 private String error(int code,String body){try{String x=new JSONObject(body).optString("error");if(!x.isEmpty())return "فشل: "+x;}catch(Exception ignored){}return "فشل HTTP "+code;}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
