package com.wethaq.app;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.ArrayAdapter;
import android.widget.TextView;
import android.widget.AdapterView;
import android.content.SharedPreferences;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import org.json.JSONArray;
import org.json.JSONObject;

public final class AdminAccessActivity extends Activity {
    private static final String API="https://wethaq-backend-production.up.railway.app";
    private SharedPreferences prefs;
    private LinearLayout root;
    private String adminToken="";
    private String selectedRole="";
    private int gold(){return Color.rgb(212,175,55);}
    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private TextView label(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.RIGHT);t.setPadding(dp(14),dp(12),dp(14),dp(12));return t;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setTextSize(18);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(24,24,26));d.setCornerRadius(dp(14));d.setStroke(dp(2),Color.rgb(70,70,75));e.setBackground(d);return e;}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(17);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(28,28,30));d.setCornerRadius(dp(14));d.setStroke(dp(2),gold());b.setBackground(d);b.setMinHeight(dp(62));return b;}
    private TextView card(String s,boolean important){TextView t=label(s,important?18:16,Color.WHITE);GradientDrawable d=new GradientDrawable();d.setColor(important?Color.rgb(45,36,12):Color.rgb(24,24,28));d.setCornerRadius(dp(16));d.setStroke(dp(2),important?gold():Color.rgb(70,70,75));t.setBackground(d);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(10);t.setLayoutParams(p);return t;}
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("wethaq",MODE_PRIVATE);adminToken=prefs.getString("admin_token","");if(adminToken.isEmpty())showLogin();else loadRole();}
    private void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(14));root.setBackgroundColor(Color.BLACK);setContentView(root);}
    private void showLogin(){base();TextView title=label("🔐 الدخول الإداري الآمن",24,gold());title.setGravity(Gravity.CENTER);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title,new LinearLayout.LayoutParams(-1,dp(72)));root.addView(label("بعد التعيين، لا تستخدم الرمز الشخصي للدخول إلى لوحة المنصب. استخدم الاسم الثلاثي + سنة الميلاد + الرمز السري الذي صدر لك.",16,Color.WHITE));EditText name=field("الاسم الثلاثي كما هو مسجل في وَثاق");EditText year=field("سنة الميلاد");EditText code=field("الرمز السري للمنصب");code.setInputType(0x00000081);root.addView(name,new LinearLayout.LayoutParams(-1,dp(64)));root.addView(year,new LinearLayout.LayoutParams(-1,dp(64)));root.addView(code,new LinearLayout.LayoutParams(-1,dp(64)));Button login=button("دخول وتسجيل الخروج من الحساب الشخصي");Button back=button("رجوع");root.addView(login,new LinearLayout.LayoutParams(-1,dp(68)));root.addView(back,new LinearLayout.LayoutParams(-1,dp(64)));login.setOnClickListener(v->login(name.getText().toString().trim(),year.getText().toString().trim(),code.getText().toString().trim()));back.setOnClickListener(v->finish());}
    private void login(String name,String year,String code){if(name.split("\\s+").length<3){toast("اكتب الاسم الثلاثي");return;}JSONObject o=new JSONObject();try{o.put("name",name);o.put("birthYear",Integer.parseInt(year));o.put("adminCode",code);}catch(Exception e){toast("سنة الميلاد أو الرمز غير صحيح");return;}request("POST","/api/admin/login",o.toString(),r->{try{JSONObject z=new JSONObject(r);adminToken=z.getString("token");String role=z.optString("role");prefs.edit().remove("token").remove("wethaq_id").putString("admin_token",adminToken).putString("admin_role",role).apply();toast("تم تسجيل الدخول الإداري ✓");loadRole();}catch(Exception e){toast("بيانات الدخول الإداري غير صحيحة");}});}
    private void loadRole(){request("GET","/api/admin/role",null,r->{try{showPanel(new JSONObject(r));}catch(Exception e){prefs.edit().remove("admin_token").remove("admin_role").apply();adminToken="";showLogin();}});}
    private void showPanel(JSONObject role){base();TextView title=label("🛡 لوحة التحكم الإدارية",24,gold());title.setGravity(Gravity.CENTER);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title,new LinearLayout.LayoutParams(-1,dp(70)));
        String roleKey=role.optString("role","");String roleLabel=role.optString("label",roleKey);String expiry=role.optString("subscriptionExpiresAt","");
        root.addView(card("المنصب الحالي\n"+role.optString("icon","")+" "+roleLabel+"\nالصلاحيات الفعلية يحددها الخادم فقط.\nانتهاء الصلاحية: "+(expiry.isEmpty()?"غير محدد / بلا انتهاء":expiry),true));
        if(!"premium".equals(roleKey)&&!"admin_member".equals(roleKey)){addAssignmentCard(role);} else {root.addView(card("🔒 التعيين الإداري غير متاح لهذه الرتبة وفق سياسة الخادم.",false));}
        addRecordButtons();
        Button structure=button("👥 عرض الهيكل الإداري الحالي");Button logout=button("🚪 تسجيل الخروج الإداري");root.addView(structure);root.addView(logout);structure.setOnClickListener(v->loadStructure());logout.setOnClickListener(v->{prefs.edit().remove("admin_token").remove("admin_role").apply();adminToken="";showLogin();});
    }
    private void addAssignmentCard(JSONObject role){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(14),dp(14),dp(14));GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(45,36,12));bg.setCornerRadius(dp(16));bg.setStroke(dp(2),gold());box.setBackground(bg);TextView title=label("📋 بطاقة التعيين الإداري",21,Color.WHITE);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setGravity(Gravity.CENTER);box.addView(title,new LinearLayout.LayoutParams(-1,dp(58)));
        EditText user=field("اسم المستخدم أو معرف وَثاق");box.addView(user,new LinearLayout.LayoutParams(-1,dp(62)));Button find=button("🔎 بحث عن المستخدم");box.addView(find,new LinearLayout.LayoutParams(-1,dp(60)));
        TextView result=label("لم يتم اختيار مستخدم بعد.",16,Color.WHITE);box.addView(result,new LinearLayout.LayoutParams(-1,dp(74)));
        Spinner roles=new Spinner(this);roles.setBackgroundColor(Color.rgb(24,24,26));String[] labels={"اختر المنصب","🏛 المدير التنفيذي","🥇 النائب الأول","🥈 النائب الثاني","🥉 النائب الثالث","🛡 المشرف","👥 عضو الإدارة","⭐ عضو مميز"};String[] keys={"","executive","deputy1","deputy2","deputy3","supervisor","admin_member","premium"};ArrayAdapter<String> adapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,labels){@Override public android.view.View getView(int p,android.view.View v,android.view.ViewGroup parent){TextView t=(TextView)super.getView(p,v,parent);t.setTextColor(Color.WHITE);t.setTextSize(17);t.setGravity(Gravity.RIGHT);t.setPadding(dp(8),dp(8),dp(8),dp(8));return t;}@Override public android.view.View getDropDownView(int p,android.view.View v,android.view.ViewGroup parent){TextView t=(TextView)super.getDropDownView(p,v,parent);t.setTextColor(Color.WHITE);t.setTextSize(17);t.setGravity(Gravity.RIGHT);t.setBackgroundColor(Color.rgb(24,24,26));t.setPadding(dp(12),dp(10),dp(12),dp(10));return t;}};adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);roles.setAdapter(adapter);box.addView(roles,new LinearLayout.LayoutParams(-1,dp(62)));roles.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,android.view.View v,int pos,long id){selectedRole=keys[pos];}public void onNothingSelected(AdapterView<?> p){selectedRole="";}});
        Button assign=button("✅ تنفيذ التعيين وإصدار رمز المنصب");box.addView(assign,new LinearLayout.LayoutParams(-1,dp(68)));assign.setOnClickListener(v->assignUser(user.getText().toString().trim(),result));find.setOnClickListener(v->findUser(user.getText().toString().trim(),result));root.addView(box,new LinearLayout.LayoutParams(-1,-2));LinearLayout.LayoutParams pp=(LinearLayout.LayoutParams)box.getLayoutParams();pp.bottomMargin=dp(12);box.setLayoutParams(pp);
    }
    private void findUser(String q,TextView result){if(q.length()<2){result.setText("أدخل اسمًا أو معرفًا لا يقل عن حرفين.");return;}request("GET","/api/admin/users?q="+enc(q),null,r->{try{JSONArray a=new JSONObject(r).optJSONArray("users");if(a==null||a.length()==0){result.setText("❌ لم يتم العثور على المستخدم.");return;}JSONObject u=a.getJSONObject(0);result.setText("👤 "+u.optString("name")+"\n🆔 "+u.optString("wethaq_id")+"\nالحالة: "+(u.optJSONObject("ban")==null?"نشط":"محظور"));userSelection.put("id",u.optString("wethaq_id"));}catch(Exception e){result.setText("تعذر قراءة المستخدم.");}});}
    private JSONObject userSelection=new JSONObject();
    private void assignUser(String fallback,TextView result){String id=userSelection.optString("id","");if(id.isEmpty())id=fallback;if(id.isEmpty()||selectedRole.isEmpty()){toast("اختر المستخدم والمنصب أولًا");return;}JSONObject o=new JSONObject();try{o.put("wethaqId",id);o.put("role",selectedRole);}catch(Exception ignored){}request("POST","/api/admin/assign",o.toString(),r->{try{JSONObject z=new JSONObject(r);result.setText("✅ تم التعيين رسميًا\n👤 "+z.optJSONObject("user").optString("name")+"\n🆔 "+z.optJSONObject("user").optString("wethaq_id")+"\n🎖 "+z.optString("label")+"\n🔐 رمز المنصب: "+z.optString("adminCode")+"\n📅 انتهاء الصلاحية: "+z.optString("subscriptionExpiresAt","غير محدد") );new AlertDialog.Builder(this).setTitle("بطاقة التعيين").setMessage(appointmentMessage(z)).setPositiveButton("إغلاق",null).show();}catch(Exception e){toast("فشل تنفيذ التعيين");}});}
    private String appointmentMessage(JSONObject z){JSONObject u=z.optJSONObject("user");return "🎉 تهانينا "+(u==null?"":u.optString("name"))+"\n\nتم التعيين رسميًا في منصب: "+z.optString("label")+"\n\n🆔 معرف وَثاق: "+(u==null?"":u.optString("wethaq_id"))+"\n🔐 رمز المنصب السري: "+z.optString("adminCode")+"\n\n📅 ينتهي في: "+z.optString("subscriptionExpiresAt","بلا انتهاء")+"\n\nسيتم إرسال بطاقة التعيين إلى حساب المستخدم داخل وَثاق.";}
    private void addRecordButtons(){TextView h=label("📚 السجلات الإدارية",20,gold());h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(h);Button users=button("👤 سجل دخول المستخدمين");Button positions=button("🏛 سجل المناصب والتعيينات");root.addView(users);root.addView(positions);users.setOnClickListener(v->loadLoginHistory());positions.setOnClickListener(v->loadPositionHistory());}
    private void loadLoginHistory(){request("GET","/api/admin/login-history?limit=200",null,r->{try{JSONArray a=new JSONObject(r).optJSONArray("entries");StringBuilder s=new StringBuilder();if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);s.append("👤 ").append(x.optString("name")).append("\n🆔 ").append(x.optString("wethaq_id")).append("\n🕒 ").append(x.optString("created_at")).append("\n🔑 ").append(x.optString("login_type")).append("\n\n");}showLong("سجل دخول المستخدمين",s.length()==0?"لا توجد عمليات دخول مسجلة حتى الآن.":s.toString());}catch(Exception e){toast("تعذر تحميل سجل الدخول");}});}
    private void loadPositionHistory(){request("GET","/api/admin/position-history?limit=200",null,r->{try{JSONArray a=new JSONObject(r).optJSONArray("entries");StringBuilder s=new StringBuilder();if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);s.append(x.optString("icon","👤")).append(" ").append(x.optString("role_label")).append("\n👤 ").append(x.optString("name")).append("\n🆔 ").append(x.optString("wethaq_id")).append("\n🔢 إصدار الرمز: ").append(x.optInt("code_version",1)).append("\n👑 عيّنه: ").append(x.optString("appointed_by_name","غير محدد")).append("\n🕒 تولى: ").append(x.optString("appointed_at","غير محدد")).append("\n⏳ ينتهي: ").append(x.optString("expires_at","بلا انتهاء")).append("\n🛑 انتهى: ").append(x.optString("ended_at","مستمر")).append("\n🔐 الرمز الشخصي: محمي ولا يُعرض في السجل.\n\n");}showLong("سجل المناصب والتعيينات",s.length()==0?"لا توجد تعيينات مسجلة.":s.toString());}catch(Exception e){toast("تعذر تحميل سجل المناصب");}});}
    private void showLong(String title,String text){TextView t=label(text,16,Color.WHITE);ScrollView sc=new ScrollView(this);sc.addView(t);new AlertDialog.Builder(this).setTitle(title).setView(sc).setPositiveButton("إغلاق",null).show();}
    private void loadStructure(){request("GET","/api/admin/structure",null,r->{try{JSONObject z=new JSONObject(r);JSONArray roles=z.optJSONArray("roles");StringBuilder s=new StringBuilder("👥 الهيكل الإداري الحالي\n\n");if(roles!=null)for(int i=0;i<roles.length();i++){JSONObject x=roles.getJSONObject(i);s.append(x.optString("icon")).append(' ').append(x.optString("label")).append(" — ").append(x.optInt("activeCount")).append('/').append(x.optInt("capacity")).append('\n');JSONArray members=x.optJSONArray("members");if(members!=null)for(int j=0;j<members.length();j++){JSONObject m=members.getJSONObject(j);s.append("  • ").append(m.optString("name")).append(" — ").append(m.optString("wethaq_id")).append("\n    ").append(m.optString("appointedBy","")).append("\n    تولى: ").append(m.optString("appointedAt","")).append('\n');}s.append('\n');}showLong("وَثاق — الإدارة",s.toString());}catch(Exception e){toast("تعذر تحميل الهيكل");}});}
    private String enc(String s){try{return java.net.URLEncoder.encode(s==null?"":"".equals(s)?"":s,"UTF-8");}catch(Exception e){return"";}}
    private interface CB{void ok(String s);}private void request(String method,String path,String body,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("Accept","application/json");if(!adminToken.isEmpty())c.setRequestProperty("Authorization","Bearer "+adminToken);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(in!=null){byte[] buf=new byte[4096];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();}String text=new String(out.toByteArray(),StandardCharsets.UTF_8);runOnUiThread(()->{if(code>=200&&code<300)cb.ok(text);else toast(errorText(text));});}catch(Exception e){runOnUiThread(()->toast("تعذر الاتصال بالخادم"));}}).start();}
    private String errorText(String s){try{return "فشل: "+new JSONObject(s).optString("error",s);}catch(Exception e){return "فشل الطلب";}}
    private void toast(String s){android.widget.Toast.makeText(this,s,android.widget.Toast.LENGTH_SHORT).show();}
}
