package com.wethaq.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.*;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public final class FinalMainActivity extends Activity {
    private static final String API="https://wethaq-backend-production.up.railway.app";
    private static final String PREF="wethaq", TOKEN="token", ID="wethaq_id", NAME="name", YEAR="birth_year", CONTACTS="contacts_v2";
    private final ExecutorService io=Executors.newSingleThreadExecutor(); private final Handler main=new Handler(Looper.getMainLooper());
    private SharedPreferences p; private LinearLayout root,content,messages; private EditText input; private String activeId,activeName; private ImageView imageDraft; private Uri pendingImage; private File pendingAudio; private MediaRecorder recorder; private boolean recording;
    private int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} private int gold(){return Color.rgb(212,175,55);}
    private boolean logged(){return p.getString(TOKEN,"").length()>10;}
    @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences(PREF,MODE_PRIVATE);if(logged())home();else login();}
    @Override protected void onDestroy(){stopRecording(false);io.shutdownNow();super.onDestroy();}
    private TextView text(String s,float size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(14),dp(10),dp(14),dp(10));return v;}
    private EditText edit(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setTextSize(18);e.setSingleLine(true);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setPadding(dp(14),0,dp(14),0);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(24,24,24));d.setCornerRadius(dp(14));d.setStroke(dp(2),Color.DKGRAY);e.setBackground(d);e.setMinHeight(dp(64));return e;}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(19);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setMinHeight(dp(72));b.setMinimumHeight(dp(72));b.setStateListAnimator(null);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(25,25,25));d.setCornerRadius(dp(14));d.setStroke(dp(2),gold());b.setBackground(d);return b;}
    private LinearLayout.LayoutParams lp(int h,int m){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,h);x.bottomMargin=dp(m);return x;}
    private void page(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(10),dp(12),dp(12));root.setBackgroundColor(Color.BLACK);TextView t=text(title,23,gold());t.setGravity(Gravity.CENTER);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(t,lp(dp(64),8));ScrollView s=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void login(){page("وَثاق — تواصل آمن");TextView h=text("تسجيل الدخول إلى هويتك",24,Color.WHITE);h.setGravity(Gravity.CENTER);content.addView(h,lp(-2,18));EditText n=edit("الاسم الثلاثي"),y=edit("سنة الميلاد");y.setInputType(InputType.TYPE_CLASS_NUMBER);content.addView(n,lp(64,10));content.addView(y,lp(64,16));Button in=button("تسجيل الدخول"),create=button("إنشاء هوية جديدة");content.addView(in,lp(74,10));content.addView(create,lp(74,16));TextView owner=text("المؤسس: حاتم حسين الحاج رمضان",16,gold());owner.setGravity(Gravity.CENTER);content.addView(owner);in.setOnClickListener(v->auth(n.getText().toString(),y.getText().toString(),false));create.setOnClickListener(v->auth(n.getText().toString(),y.getText().toString(),true));}
    private void auth(String name,String year,boolean create){String n=name.trim(),y=year.trim();if(n.split("\\s+").length<3||!y.matches("\\d{4}")){toast("أدخل الاسم الثلاثي وسنة الميلاد");return;}io.execute(()->{try{JSONObject q=new JSONObject();q.put("name",n);q.put("birthYear",Integer.parseInt(y));q.put("deviceKey",deviceKey());Http r=request("POST",create?"/api/identity":"/api/login",q.toString());if(r.code>=200&&r.code<300){JSONObject o=new JSONObject(r.body),u=o.getJSONObject("user");p.edit().putString(TOKEN,o.getString("token")).putString(ID,u.optString("wethaq_id")).putString(NAME,u.optString("name",n)).putString(YEAR,y).apply();main.post(this::home);}else main.post(()->toast(error(r)));}catch(Exception e){main.post(()->toast("تعذر الاتصال بالخادم"));}});}
    private void home(){page("وَثاق | المؤسس: حاتم حسين الحاج رمضان");TextView me=text("👤 "+p.getString(NAME,"")+"\nمعرّف وَثاق: "+p.getString(ID,""),18,Color.WHITE);me.setGravity(Gravity.CENTER);content.addView(me,lp(-2,12));menu("🔎 البحث عن مستخدم",this::searchPage);menu("👥 جهات الاتصال",this::contactsPage);menu("⚠ الشكاوى",this::complaintPage);menu("👤 ملفي الشخصي",this::profilePage);Button out=button("تسجيل الخروج");content.addView(out,lp(74,8));out.setOnClickListener(v->{p.edit().remove(TOKEN).apply();login();});}
    private void menu(String s,Runnable r){Button b=button(s);content.addView(b,lp(74,8));b.setOnClickListener(v->r.run());}
    private void searchPage(){page("البحث عن مستخدم");EditText q=edit("الاسم أو معرف وَثاق");Button go=button("بحث"),back=button("رجوع");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(q,lp(64,8));content.addView(go,lp(74,8));content.addView(list,lp(-2,8));content.addView(back,lp(74,8));go.setOnClickListener(v->search(q.getText().toString().trim(),list));back.setOnClickListener(v->home());}
    private void search(String q,LinearLayout list){if(q.length()<2){toast("أدخل حرفين على الأقل");return;}io.execute(()->{try{Http r=request("GET","/api/search?q="+URLEncoder.encode(q,"UTF-8"),null);if(r.code!=200){main.post(()->toast(error(r)));return;}JSONArray a=new JSONObject(r.body).optJSONArray("users");main.post(()->{list.removeAllViews();if(a==null||a.length()==0){list.addView(text("لا توجد نتائج",17,Color.GRAY));return;}for(int i=0;i<a.length();i++){JSONObject u=a.optJSONObject(i);String id=u.optString("wethaq_id"),name=u.optString("name");Button open=button("👤 "+name+"\n"+id);list.addView(open,lp(76,8));open.setOnClickListener(v->{saveContact(id,name);conversation(id,name);});}});}catch(Exception e){main.post(()->toast("فشل البحث"));}});}
    private JSONArray contacts(){try{return new JSONArray(p.getString(CONTACTS,"[]"));}catch(Exception e){return new JSONArray();}}
    private void saveContact(String id,String name){try{JSONArray a=contacts();for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("id")))return;JSONObject o=new JSONObject();o.put("id",id);o.put("name",name);a.put(o);p.edit().putString(CONTACTS,a.toString()).apply();}catch(Exception ignored){}}
    private void contactsPage(){page("جهات الاتصال");JSONArray a=contacts();if(a.length()==0)content.addView(text("سيظهر الشخص تلقائيًا عند أول تواصل",17,Color.GRAY));for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);String id=o.optString("id"),name=o.optString("name");Button b=button("👤 "+name);content.addView(b,lp(74,8));b.setOnClickListener(v->conversation(id,name));}Button back=button("رجوع");content.addView(back,lp(74,8));back.setOnClickListener(v->home());}
    private void conversation(String id,String name){activeId=id;activeName=name;page("💬 "+name);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);ImageView av=new ImageView(this);av.setImageResource(com.wethaq.app.R.drawable.ic_wethaq);head.addView(av,new LinearLayout.LayoutParams(dp(56),dp(56)));TextView nt=text(name+"\n"+id,18,Color.WHITE);head.addView(nt,new LinearLayout.LayoutParams(0,-2,1));content.addView(head,lp(70,6));Button call=button("📹 مكالمة فيديو");content.addView(call,lp(72,6));call.setOnClickListener(v->startActivity(new Intent(this,VideoCallActivity.class).putExtra("target",activeId)));
        messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(messages);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        imageDraft=new ImageView(this);imageDraft.setVisibility(View.GONE);imageDraft.setAdjustViewBounds(true);imageDraft.setMaxHeight(dp(180));content.addView(imageDraft,lp(-2,4));
        LinearLayout bar=new LinearLayout(this);Button mic=button("🎙"),pic=button("🖼"),send=button("إرسال");input=edit("اكتب رسالتك…");bar.addView(mic,new LinearLayout.LayoutParams(dp(62),dp(72)));bar.addView(pic,new LinearLayout.LayoutParams(dp(62),dp(72)));bar.addView(input,new LinearLayout.LayoutParams(0,dp(72),1));bar.addView(send,new LinearLayout.LayoutParams(dp(88),dp(72)));root.addView(bar);Button back=button("‹ رجوع");root.addView(back,new LinearLayout.LayoutParams(-1,dp(72)));back.setOnClickListener(v->contactsPage());mic.setOnClickListener(v->{if(recording)stopRecording(true);else startRecording();});pic.setOnClickListener(v->pickImage());send.setOnClickListener(v->send());loadMessages();}
    private void loadMessages(){io.execute(()->{try{Http r=request("GET","/api/messages/"+URLEncoder.encode(activeId,"UTF-8"),null);if(r.code==200){JSONArray a=new JSONObject(r.body).optJSONArray("messages");main.post(()->render(a));}}catch(Exception ignored){}});}
    private void render(JSONArray a){if(messages==null)return;messages.removeAllViews();String me=p.getString(ID,"");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);String sender=m.optString("sender_wethaq_id"),senderName=m.optString("sender_name","مستخدم");boolean mine=me.equals(sender);LinearLayout row=new LinearLayout(this);row.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);TextView b;textView: {String type=m.optString("message_type","text");if("audio".equals(type))b=text("🎙 رسالة صوتية",20,Color.WHITE);else if("image".equals(type))b=text("🖼 صورة",20,Color.WHITE);else b=text(m.optString("body"),20,mine?Color.BLACK:Color.WHITE);b.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);GradientDrawable d=new GradientDrawable();d.setColor(mine?gold():Color.rgb(35,35,35));d.setCornerRadius(dp(14));b.setBackground(d);b.setPadding(dp(14),dp(12),dp(14),dp(12));row.addView(b,new LinearLayout.LayoutParams(-2,-2));}TextView who=text(mine?"أنت":senderName,15,mine?gold():Color.LTGRAY);who.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);box.addView(who);box.addView(row);messages.addView(box,lp(-2,7));}}
    private void send(){if(activeId==null)return;if(pendingImage!=null){sendImage();return;}if(pendingAudio!=null){sendAudio();return;}String s=input==null?"":input.getText().toString().trim();if(s.isEmpty())return;saveContact(activeId,activeName);io.execute(()->{try{JSONObject q=new JSONObject().put("to",activeId).put("body",s);Http r=request("POST","/api/messages",q.toString());main.post(()->{if(r.code>=200&&r.code<300){input.setText("");loadMessages();}else toast(error(r));});}catch(Exception e){main.post(()->toast("فشل الإرسال"));}});}
    private void pickImage(){Intent i=new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI);startActivityForResult(i,700);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==700&&c==RESULT_OK&&d!=null){pendingImage=d.getData();try{imageDraft.setImageURI(pendingImage);imageDraft.setVisibility(View.VISIBLE);toast("الصورة جاهزة كمسودة — اضغط إرسال");}catch(Exception e){pendingImage=null;}}}
    private void sendImage(){try{byte[] z=readUri(pendingImage);String b=Base64.getEncoder().encodeToString(z);io.execute(()->{try{JSONObject q=new JSONObject().put("to",activeId).put("imageBase64",b).put("mimeType","image/jpeg");Http r=request("POST","/api/messages/image",q.toString());main.post(()->{if(r.code>=200&&r.code<300){pendingImage=null;imageDraft.setVisibility(View.GONE);loadMessages();}else toast(error(r));});}catch(Exception e){main.post(()->toast("فشل إرسال الصورة"));}});}catch(Exception e){toast("تعذر تجهيز الصورة");}}
    private void startRecording(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},701);return;}try{pendingAudio=new File(getCacheDir(),"wethaq_voice.m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(pendingAudio.getAbsolutePath());recorder.prepare();recorder.start();recording=true;toast("جارٍ التسجيل… اضغط 🎙 مجددًا لتجهيز المسودة");}catch(Exception e){pendingAudio=null;toast("تعذر بدء التسجيل");}}
    private void stopRecording(boolean draft){if(recorder==null)return;try{recorder.stop();}catch(Exception ignored){}recorder.release();recorder=null;recording=false;if(draft&&pendingAudio!=null){toast("التسجيل جاهز كمسودة — اضغط إرسال");}else pendingAudio=null;}
    private void sendAudio(){if(pendingAudio==null||!pendingAudio.exists()){pendingAudio=null;return;}io.execute(()->{try{byte[] z=readFile(pendingAudio);String b=Base64.getEncoder().encodeToString(z);JSONObject q=new JSONObject().put("to",activeId).put("audioBase64",b).put("mimeType","audio/mp4");Http r=request("POST","/api/messages/audio",q.toString());main.post(()->{if(r.code>=200&&r.code<300){pendingAudio.delete();pendingAudio=null;loadMessages();}else toast(error(r));});}catch(Exception e){main.post(()->toast("فشل إرسال الصوت"));}});}
    private void complaintPage(){page("⚠ الشكاوى");EditText msg=edit("اكتب الشكوى أو البلاغ");msg.setSingleLine(false);msg.setMinHeight(dp(150));Button send=button("إرسال الشكوى"),back=button("رجوع");content.addView(msg,lp(160,10));content.addView(send,lp(74,8));content.addView(back,lp(74,8));send.setOnClickListener(v->sendComplaint(msg.getText().toString().trim()));back.setOnClickListener(v->home());}
    private void sendComplaint(String s){if(s.isEmpty()){toast("اكتب الشكوى أولًا");return;}io.execute(()->{try{Http r=request("POST","/api/complaints",new JSONObject().put("message",s).toString());main.post(()->{if(r.code>=200&&r.code<300){toast("تم إرسال الشكوى إلى الإدارة");complaintPage();}else toast(error(r));});}catch(Exception e){main.post(()->toast("فشل إرسال الشكوى"));}});}
    private void profilePage(){page("الملف الشخصي");TextView t=text("👤 "+p.getString(NAME,"")+"\nمعرف وَثاق: "+p.getString(ID,"")+"\nالصورة الشخصية مرتبطة بالحساب",19,Color.WHITE);t.setGravity(Gravity.CENTER);content.addView(t,lp(-2,20));Button back=button("رجوع");content.addView(back,lp(74,8));back.setOnClickListener(v->home());}
    private String deviceKey(){return Build.MODEL+"-"+Build.VERSION.RELEASE+"-"+Build.FINGERPRINT;}
    private byte[] readUri(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toByteArray();}
    private byte[] readFile(File f)throws Exception{FileInputStream in=new FileInputStream(f);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toByteArray();}
    private String authHeader(){return "Bearer "+p.getString(TOKEN,"");}
    private Http request(String method,String path,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestProperty("Authorization",authHeader());c.setRequestProperty("Content-Type","application/json");if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();if(in==null)in=new ByteArrayInputStream(new byte[0]);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();c.disconnect();return new Http(code,new String(o.toByteArray(),StandardCharsets.UTF_8));}
    private String error(Http r){try{JSONObject o=new JSONObject(r.body);String e=o.optString("error");if("user_not_found".equals(e))return "المستخدم غير موجود";if("user_banned".equals(e))return "تم حظرك: "+o.optString("reason","بدون سبب");if("unauthorized".equals(e)||"invalid_token".equals(e))return "انتهت جلسة الدخول، سجّل الدخول مجددًا";return e.isEmpty()?"حدث خطأ ("+r.code+")":e;}catch(Exception e){return "حدث خطأ ("+r.code+")";}}
    private void toast(String s){main.post(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}
    private static final class Http{final int code;final String body;Http(int c,String b){code=c;body=b;}}
}
