package com.wethaq.app;

import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputType;
import android.view.Gravity;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URLEncoder;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class MainActivity extends Activity {
    private static final String API="https://wethaq-backend-production.up.railway.app";
    private static final String PREFS="wethaq",TOKEN="token",USER_ID="wethaq_id",NAME="name",CONTACTS="saved_contacts";
    private final ExecutorService io=Executors.newSingleThreadExecutor(); private final Handler main=new Handler(Looper.getMainLooper());
    private SharedPreferences prefs; private LinearLayout root,content,messages; private EditText input; private String activeId,activeName; private Runnable poller; private TextView chatStatus;
    @Override protected void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);if(hasToken())home();else login();}
    @Override protected void onResume(){super.onResume();if(hasToken())startPolling();}
    @Override protected void onPause(){stopPolling();super.onPause();}
    @Override protected void onDestroy(){stopPolling();io.shutdownNow();super.onDestroy();}
    private boolean hasToken(){return prefs.getString(TOKEN,"").length()>10;}
    private void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);root.setBackgroundColor(Color.rgb(7,15,27));TextView h=tv(title,22,Color.WHITE);h.setGravity(Gravity.CENTER);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(h,lp(-1,-2,0,12));ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private TextView tv(String text,float size,int color){TextView t=new TextView(this);t.setText(text);t.setTextSize(size);t.setTextColor(color);t.setPadding(10,10,10,10);return t;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.LTGRAY);e.setPadding(14,10,14,10);return e;}
    private Button btn(String text){Button b=new Button(this);b.setText(text);return b;}
    private LinearLayout.LayoutParams lp(int width,int height,int left,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(width,height);p.leftMargin=left;p.bottomMargin=bottom;return p;}
    private void login(){base("وَثاق");TextView title=tv("هويتك الرقمية الآمنة",24,Color.WHITE);title.setGravity(Gravity.CENTER);content.addView(title);EditText name=field("الاسم الثلاثي"),year=field("سنة الميلاد");year.setInputType(InputType.TYPE_CLASS_NUMBER);content.addView(name,lp(-1,-2,0,8));content.addView(year,lp(-1,-2,0,8));Button login=btn("دخول"),create=btn("إنشاء هوية جديدة");content.addView(login);content.addView(create);TextView founder=tv("المؤسس: حاتم حسين الحاج رمضان",14,Color.LTGRAY);founder.setGravity(Gravity.CENTER);content.addView(founder,lp(-1,-2,0,12));login.setOnClickListener(v->authenticate(name.getText().toString().trim(),year.getText().toString().trim(),false));create.setOnClickListener(v->authenticate(name.getText().toString().trim(),year.getText().toString().trim(),true));}
    private boolean validIdentity(String name,String year){return name.split("\\s+").length>=3&&year.matches("\\d{4}");}
    private void authenticate(String name,String year,boolean create){if(!validIdentity(name,year)){toast("أدخل الاسم الثلاثي وسنة الميلاد");return;}io.execute(()->{try{JSONObject body=new JSONObject();body.put("name",name);body.put("birthYear",Integer.parseInt(year));body.put("deviceKey",deviceKey());HttpResult r=request("POST",create?"/api/identity":"/api/login",body.toString(),null);if(!create&&r.code==404)r=request("POST","/api/identity",body.toString(),null);if(r.code>=200&&r.code<300){JSONObject response=new JSONObject(r.body),user=response.getJSONObject("user");prefs.edit().putString(TOKEN,response.getString("token")).putString(USER_ID,user.getString("wethaq_id")).putString(NAME,user.getString("name")).putString("numeric_id",String.valueOf(user.optInt("id",-1))).apply();main.post(this::home);}else{String m=error(r);main.post(()->toast(m));}}catch(Exception e){main.post(()->toast("تعذر الاتصال بالخادم"));}});}
    private void home(){stopPolling();activeId=null;base("برنامج وثاق للتواصل الاجتماعي");TextView date=tv("تم بناؤه بتاريخ 2026/8/23\nالمؤسس وقائد العمل\nحاتم حسين الحاج رمضان",14,Color.rgb(212,175,55));date.setGravity(Gravity.CENTER);content.addView(date,lp(-1,-2,0,12));TextView name=tv(prefs.getString(NAME,"مستخدم وَثاق"),20,Color.WHITE),id=tv(prefs.getString(USER_ID,""),14,Color.LTGRAY);name.setGravity(Gravity.CENTER);id.setGravity(Gravity.CENTER);content.addView(name);content.addView(id);Button search=btn("البحث عن مستخدم"),contacts=btn("جهات الاتصال"),logout=btn("تسجيل الخروج");content.addView(search);content.addView(contacts);content.addView(logout);search.setOnClickListener(v->searchScreen());contacts.setOnClickListener(v->contactsScreen());logout.setOnClickListener(v->{prefs.edit().clear().apply();stopPolling();login();});startPolling();}
    private void searchScreen(){base("البحث");Button back=btn("العودة");EditText query=field("الاسم أو معرف وَثاق");Button go=btn("بحث");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(back);content.addView(query);content.addView(go);content.addView(list);back.setOnClickListener(v->home());go.setOnClickListener(v->search(query.getText().toString().trim(),list));}
    private void search(String query,LinearLayout list){if(query.length()<2){toast("أدخل حرفين على الأقل");return;}io.execute(()->{try{HttpResult r=request("GET","/api/search?q="+URLEncoder.encode(query,"UTF-8"),null,null);if(r.code==200){JSONArray users=new JSONObject(r.body).optJSONArray("users");main.post(()->{list.removeAllViews();if(users==null||users.length()==0){list.addView(tv("لا توجد نتائج",16,Color.LTGRAY));return;}for(int i=0;i<users.length();i++){JSONObject u=users.optJSONObject(i);if(u!=null)addResult(list,u);}});}else{String m=error(r);main.post(()->toast(m));}}catch(Exception e){main.post(()->toast("فشل البحث"));}});}
    private void addResult(LinearLayout list,JSONObject user){String id=user.optString("wethaq_id"),name=user.optString("name");list.addView(tv(name+"\n"+id,18,Color.WHITE));Button save=btn("حفظ في جهات الاتصال");list.addView(save);save.setOnClickListener(v->saveContact(id,name));}
    private void saveContact(String id,String name){if(id==null||id.trim().isEmpty())return;io.execute(()->{try{JSONObject body=new JSONObject();body.put("wethaqId",id);body.put("receiver_id",id);HttpResult r=request("POST","/api/contacts",body.toString(),auth());if(r.code>=200&&r.code<300){saveLocal(id,name);main.post(()->toast("تم الحفظ ✓"));}else{String m=error(r);main.post(()->toast(m));}}catch(Exception e){main.post(()->toast("تعذر حفظ جهة الاتصال"));}});}
    private void contactsScreen(){base("جهات الاتصال");Button back=btn("العودة");content.addView(back);back.setOnClickListener(v->home());JSONArray contacts=localContacts();if(contacts.length()==0){content.addView(tv("لا توجد جهات اتصال محفوظة",16,Color.LTGRAY));return;}for(int i=0;i<contacts.length();i++){JSONObject u=contacts.optJSONObject(i);if(u==null)continue;String id=u.optString("wethaq_id"),name=u.optString("name");Button c=btn(name+"\n"+id);content.addView(c);c.setOnClickListener(v->conversation(id,name));}}
    private void conversation(String id,String name){stopPolling();activeId=id;activeName=name;base("محادثة مع "+name);chatStatus=tv("● جاري التحقق من الحالة...",13,Color.LTGRAY);chatStatus.setGravity(Gravity.CENTER);content.addView(chatStatus,lp(-1,-2,0,4));Button back=btn("جهات الاتصال");content.addView(back);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(4,8,4,8);ScrollView scroll=new ScrollView(this);scroll.addView(messages);content.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);input=field("اكتب رسالة…");Button send=btn("إرسال");bar.addView(input,new LinearLayout.LayoutParams(0,-2,1));bar.addView(send,new LinearLayout.LayoutParams(-2,-2));root.addView(bar,new LinearLayout.LayoutParams(-1,-2));back.setOnClickListener(v->contactsScreen());send.setOnClickListener(v->sendMessage());loadMessages();updateChatStatus();startPolling();}
    private void updateChatStatus(){if(chatStatus==null||activeId==null)return;final String target=activeId;io.execute(()->{try{HttpResult r=request("GET","/api/search?q="+URLEncoder.encode(target,"UTF-8"),null,null);boolean online=false;if(r.code==200){JSONArray a=new JSONObject(r.body).optJSONArray("users");if(a!=null&&a.length()>0){JSONObject u=a.optJSONObject(0);if(u!=null)online=u.optBoolean("online",false);}}final boolean state=online;main.post(()->{if(chatStatus!=null&&target.equals(activeId)){chatStatus.setText(state?"● متصل الآن":"● غير متصل");chatStatus.setTextColor(state?Color.rgb(90,210,150):Color.LTGRAY);}});}catch(Exception e){main.post(()->{if(chatStatus!=null&&target.equals(activeId)){chatStatus.setText("● غير متصل");chatStatus.setTextColor(Color.LTGRAY);}});}});}
    private void loadMessages(){if(activeId==null||activeId.isEmpty())return;final String target=activeId;io.execute(()->{try{HttpResult r=request("GET","/api/messages/"+URLEncoder.encode(target,"UTF-8"),null,auth());if(r.code==200){JSONArray data=new JSONObject(r.body).optJSONArray("messages");main.post(()->{if(target.equals(activeId))renderMessages(data);});}}catch(Exception ignored){}});}
    private void renderMessages(JSONArray data){if(messages==null)return;messages.removeAllViews();if(data==null||data.length()==0){TextView empty=tv("ابدأ المحادثة برسالة جديدة.",16,Color.LTGRAY);empty.setGravity(Gravity.CENTER);messages.addView(empty);return;}for(int i=0;i<data.length();i++){JSONObject m=data.optJSONObject(i);if(m==null)continue;int sender=m.optInt("sender_id",Integer.MIN_VALUE);boolean mine=sender==Integer.parseInt(prefs.getString("numeric_id","-1"));LinearLayout row=new LinearLayout(this);row.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.bottomMargin=8;TextView bubble=tv(m.optString("body"),16,Color.WHITE);bubble.setPadding(18,12,18,12);bubble.setBackgroundColor(mine?Color.rgb(37,67,70):Color.rgb(25,45,67));bubble.setTypeface(Typeface.DEFAULT,Typeface.NORMAL);row.addView(bubble,new LinearLayout.LayoutParams(-2,-2));messages.addView(row,rp);}}
    private void sendMessage(){if(input==null)return;final String text=input.getText().toString().trim(),target=activeId;if(text.isEmpty()||target==null||target.isEmpty())return;if(target.equals(prefs.getString(USER_ID,""))){toast("لا يمكن الإرسال إلى نفسك");return;}input.setEnabled(false);io.execute(()->{try{JSONObject body=new JSONObject();body.put("receiver_id",target);body.put("to",target);body.put("body",text);HttpResult r=request("POST","/api/messages",body.toString(),auth());main.post(()->{input.setEnabled(true);if(r.code>=200&&r.code<300){input.setText("");loadMessages();toast("تم إرسال الرسالة ✓");}else toast(error(r));});}catch(Exception e){main.post(()->{input.setEnabled(true);toast("فشل الإرسال");});}});}
    private void startPolling(){stopPolling();poller=()->{if(activeId!=null){loadMessages();updateChatStatus();}pollInbox();if(hasToken())main.postDelayed(poller,2500);};main.postDelayed(poller,500);}
    private void stopPolling(){if(poller!=null)main.removeCallbacks(poller);poller=null;}
    private void pollInbox(){if(!hasToken())return;io.execute(()->{try{request("GET","/api/messages/inbox",null,auth());}catch(Exception ignored){}});}
    private JSONArray localContacts(){try{return new JSONArray(prefs.getString(CONTACTS,"[]"));}catch(Exception e){return new JSONArray();}}
    private void saveLocal(String id,String name){try{JSONArray c=localContacts();for(int i=0;i<c.length();i++){JSONObject o=c.optJSONObject(i);if(o!=null&&id.equals(o.optString("wethaq_id")))return;}JSONObject n=new JSONObject();n.put("wethaq_id",id);n.put("name",name);c.put(n);prefs.edit().putString(CONTACTS,c.toString()).apply();}catch(Exception ignored){}}
    private String deviceKey(){String k=prefs.getString("device_key","");if(k.length()>20)return k;k="wethaq-"+UUID.randomUUID();prefs.edit().putString("device_key",k).apply();return k;}
    private String auth(){return "Bearer "+prefs.getString(TOKEN,"");}
    private void toast(String text){Toast.makeText(this,text,Toast.LENGTH_SHORT).show();}
    private String error(HttpResult r){try{JSONObject o=new JSONObject(r.body);String v=o.optString("error");if(!v.isEmpty())return v;v=o.optString("message");if(!v.isEmpty())return v;}catch(Exception ignored){}return "HTTP "+r.code;}
    private HttpResult request(String method,String path,String body,String authorization)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(15000);c.setRequestProperty("Accept","application/json");if(authorization!=null)c.setRequestProperty("Authorization",authorization);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");byte[] b=body.getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(b.length);try(OutputStream o=c.getOutputStream()){o.write(b);}}int code=c.getResponseCode();InputStream in=code>=200&&code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(in!=null){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);in.close();}c.disconnect();return new HttpResult(code,new String(out.toByteArray(),StandardCharsets.UTF_8));}
    private static final class HttpResult{final int code;final String body;HttpResult(int code,String body){this.code=code;this.body=body;}}
}
