package com.wethaq.app;

import android.Manifest;
import android.app.Activity;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.media.MediaRecorder;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.MediaStore;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private static final String API="https://wethaq-backend-production.up.railway.app",P="wethaq",T="token",ID="wethaq_id",NAME="name",YEAR="birth_year",CONTACTS="saved_contacts";
 private final ExecutorService io=Executors.newSingleThreadExecutor();
 private final Handler h=new Handler(Looper.getMainLooper());
 private SharedPreferences prefs;
 private LinearLayout root,content,messages;
 private EditText input;
 private String activeId,activeName;
 private Runnable poller;
 private MediaRecorder recorder;
 private boolean recording;

 @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences(P,MODE_PRIVATE);if(hasToken())home();else login();}
 @Override protected void onDestroy(){stopPolling();stopRecording(false);io.shutdownNow();super.onDestroy();}
 private boolean hasToken(){return prefs.getString(T,"").length()>10;}
 private int gold(){return Color.rgb(212,175,55);}
 private int panel(){return Color.rgb(24,24,24);}
 private TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(16,12,16,12);return t;}
 private EditText field(String s){EditText e=new EditText(this);e.setHint(s);e.setHintTextColor(Color.rgb(145,145,145));e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setTextSize(17);e.setPadding(18,8,18,8);e.setBackgroundColor(panel());return e;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(gold());b.setTextSize(16);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackgroundColor(panel());return b;}
 private LinearLayout.LayoutParams lp(int w,int h,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.bottomMargin=b;return p;}
 private void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(10,10,10,10);root.setBackgroundColor(Color.BLACK);TextView top=tv(title,22,gold());top.setTypeface(Typeface.DEFAULT_BOLD);top.setGravity(Gravity.CENTER);root.addView(top,lp(-1,58,8));ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private void login(){base("وَثاق");TextView x=tv("هوية رقمية آمنة",27,Color.WHITE);x.setGravity(Gravity.CENTER);x.setTypeface(Typeface.DEFAULT_BOLD);content.addView(x,lp(-1,-2,18));EditText n=field("الاسم الثلاثي"),y=field("سنة الميلاد");y.setInputType(InputType.TYPE_CLASS_NUMBER);content.addView(n,lp(-1,58,8));content.addView(y,lp(-1,58,14));Button l=btn("دخول"),c=btn("إنشاء هوية جديدة");content.addView(l,lp(-1,58,8));content.addView(c,lp(-1,58,18));TextView founder=tv("المؤسس: حاتم حسين الحاج رمضان",15,gold());founder.setGravity(Gravity.CENTER);content.addView(founder);l.setOnClickListener(v->auth(n.getText().toString().trim(),y.getText().toString().trim(),false));c.setOnClickListener(v->auth(n.getText().toString().trim(),y.getText().toString().trim(),true));}
 private void auth(String n,String y,boolean create){final String name=n.trim(),year=y.trim();if(name.split("\\s+").length<3||!year.matches("\\d{4}")){toast("أدخل الاسم الثلاثي وسنة الميلاد");return;}io.execute(()->{try{JSONObject q=new JSONObject();q.put("name",name);q.put("birthYear",Integer.parseInt(year));q.put("deviceKey",deviceKey());HttpResult r=request("POST",create?"/api/identity":"/api/login",q.toString(),null);if(!create&&r.code==404)r=request("POST","/api/identity",q.toString(),null);if(r.code>=200&&r.code<300){JSONObject o=new JSONObject(r.body),u=o.getJSONObject("user");prefs.edit().putString(T,o.getString("token")).putString(ID,u.optString("wethaq_id")).putString(NAME,u.optString("name",name)).putString(YEAR,year).apply();h.post(this::home);}else{final HttpResult result=r;h.post(()->toast(error(result)));}}catch(Exception e){h.post(()->toast("تعذر الاتصال بالخادم"));}});}
 private void home(){stopPolling();base("المؤسس: حاتم حسين الحاج رمضان");String name=prefs.getString(NAME,"");String id=prefs.getString(ID,"");TextView me=tv(name+"\n"+id,18,Color.WHITE);me.setGravity(Gravity.CENTER);me.setTypeface(Typeface.DEFAULT_BOLD);me.setBackgroundColor(Color.rgb(10,10,10));content.addView(me,lp(-1,-2,14));TextView status=tv("● متصل بالخادم",13,Color.rgb(120,200,120));status.setGravity(Gravity.CENTER);content.addView(status,lp(-1,-2,12));menu("⌕   البحث عن مستخدم",this::searchScreen);menu("◉   جهات الاتصال",this::contactsScreen);menu("⚙   الإعدادات",this::settingsScreen);menu("♙   المعلومات الشخصية",this::profileScreen);menu("▣   المحفوظات",this::archiveScreen);Button out=btn("تسجيل الخروج");content.addView(out,lp(-1,58,8));out.setOnClickListener(v->{prefs.edit().clear().apply();login();});startPolling();}
 private void menu(String s,Runnable r){TextView row=tv(s,18,gold());row.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);row.setTypeface(Typeface.DEFAULT_BOLD);row.setBackgroundColor(panel());row.setClickable(true);row.setFocusable(true);row.setPadding(22,0,22,0);content.addView(row,lp(-1,64,8));row.setOnClickListener(v->r.run());}
 private void searchScreen(){base("البحث عن مستخدم");EditText q=field("الاسم أو معرف وَثاق");Button go=btn("بحث"),back=btn("رجوع");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(q,lp(-1,58,8));content.addView(go,lp(-1,58,8));content.addView(tv("احفظ الشخص بعد العثور عليه ليظهر في جهات الاتصال.",14,gold()),lp(-1,-2,8));content.addView(list);content.addView(back,lp(-1,58,8));go.setOnClickListener(v->search(q.getText().toString().trim(),list));back.setOnClickListener(v->home());}
 private void search(String q,LinearLayout list){if(q.length()<2){toast("أدخل حرفين على الأقل");return;}io.execute(()->{try{HttpResult r=request("GET","/api/search?q="+URLEncoder.encode(q,"UTF-8"),null,null);if(r.code==200){JSONArray a=new JSONObject(r.body).optJSONArray("users");h.post(()->{list.removeAllViews();if(a==null||a.length()==0){list.addView(tv("لا توجد نتائج",16,Color.GRAY));return;}for(int i=0;i<a.length();i++){JSONObject u=a.optJSONObject(i);if(u==null)continue;String id=u.optString("wethaq_id"),n=u.optString("name");TextView user=tv("👤 "+n+"\n"+id,17,Color.WHITE);user.setBackgroundColor(panel());list.addView(user,lp(-1,-2,6));Button save=btn("حفظ جهة الاتصال");list.addView(save,lp(-1,52,12));save.setOnClickListener(v->saveContact(id,n));}});}else{final HttpResult result=r;h.post(()->toast(error(result)));}}catch(Exception e){h.post(()->toast("فشل البحث"));}});}
 private void saveContact(String id,String n){try{JSONArray a=contacts();for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("wethaq_id"))){toast("محفوظ مسبقًا");return;}JSONObject o=new JSONObject();o.put("wethaq_id",id);o.put("name",n);a.put(o);prefs.edit().putString(CONTACTS,a.toString()).apply();toast("تم الحفظ ✓");}catch(Exception e){toast("فشل الحفظ");}}
 private void contactsScreen(){base("جهات الاتصال");Button back=btn("رجوع");content.addView(back,lp(-1,58,8));back.setOnClickListener(v->home());JSONArray a=contacts();if(a.length()==0){content.addView(tv("لا توجد جهات اتصال محفوظة",16,Color.GRAY));return;}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String id=o.optString("wethaq_id"),n=o.optString("name");Button b=btn("👤 "+n+"\n"+id);content.addView(b,lp(-1,-2,8));b.setOnClickListener(v->conversation(id,n));}}
 private void conversation(String id,String n){stopPolling();activeId=id;activeName=n;base(n);TextView sub=tv("محادثة آمنة",13,gold());sub.setGravity(Gravity.CENTER);content.addView(sub);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(messages);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);Button mic=btn("🎙"),gallery=btn("▧"),send=btn("إرسال");input=field("اكتب رسالة…");bar.addView(mic,new LinearLayout.LayoutParams(52,58));bar.addView(gallery,new LinearLayout.LayoutParams(52,58));bar.addView(input,new LinearLayout.LayoutParams(0,58,1));bar.addView(send,new LinearLayout.LayoutParams(72,58));root.addView(bar);Button back=btn("‹ جهات الاتصال");root.addView(back,new LinearLayout.LayoutParams(-1,55));back.setOnClickListener(v->contactsScreen());send.setOnClickListener(v->send());mic.setOnClickListener(v->{if(recording)stopRecording(true);else startRecording();});gallery.setOnClickListener(v->pickImage());loadMessages();startPolling();}
 private void loadMessages(){final String target=activeId;if(target==null)return;io.execute(()->{try{HttpResult r=request("GET","/api/messages/"+URLEncoder.encode(target,"UTF-8"),null,auth());if(r.code==200){JSONArray a=new JSONObject(r.body).optJSONArray("messages");h.post(()->{if(target.equals(activeId))render(a);});}}catch(Exception ignored){}});}
 private void render(JSONArray a){if(messages==null)return;messages.removeAllViews();if(a==null||a.length()==0){messages.addView(tv("ابدأ المحادثة الآن",15,Color.GRAY));return;}String me=prefs.getString(ID,"");for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;String s=m.optString("sender_id");if(s.isEmpty())s=m.optString("senderId");boolean mine=me.equals(s);TextView b=tv(m.optString("body",m.optString("text"))+"\n"+(mine?"✓✓":"✓"),16,mine?Color.BLACK:Color.WHITE);b.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);b.setBackgroundColor(mine?gold():Color.rgb(32,32,32));LinearLayout line=new LinearLayout(this);line.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);line.addView(b,new LinearLayout.LayoutParams(-2,-2));messages.addView(line,lp(-1,-2,8));}}
 private void send(){String text=input==null?"":input.getText().toString().trim();if(text.isEmpty()||activeId==null)return;io.execute(()->{try{JSONObject q=new JSONObject();q.put("receiver_id",activeId);q.put("to",activeId);q.put("body",text);HttpResult r=request("POST","/api/messages",q.toString(),auth());h.post(()->{if(r.code>=200&&r.code<300){input.setText("");loadMessages();}else{final HttpResult result=r;toast(error(result));}});}catch(Exception e){h.post(()->toast("فشل الإرسال"));}});}
 private void settingsScreen(){base("الإعدادات");Button n=btn("🔔 الإشعارات"),sound=btn("🔊 صوت النقر"),pic=btn("🖼 الصورة الشخصية"),save=btn("حفظ"),back=btn("رجوع");EditText name=field("الاسم الثلاثي"),year=field("المواليد");name.setText(prefs.getString(NAME,""));year.setText(prefs.getString(YEAR,""));year.setInputType(InputType.TYPE_CLASS_NUMBER);content.addView(n,lp(-1,58,6));content.addView(sound,lp(-1,58,10));content.addView(tv("الاسم الشخصي",14,gold()));content.addView(name,lp(-1,58,8));content.addView(tv("المواليد",14,gold()));content.addView(year,lp(-1,58,8));content.addView(tv("المعرف الشخصي تلقائيًا",14,gold()));content.addView(tv(prefs.getString(ID,""),18,Color.WHITE),lp(-1,-2,8));content.addView(pic,lp(-1,58,6));content.addView(save,lp(-1,58,6));content.addView(back,lp(-1,58,8));n.setOnClickListener(v->toast("الإشعارات مفعلة"));sound.setOnClickListener(v->toast("صوت النقر مفعّل"));pic.setOnClickListener(v->pickImage());save.setOnClickListener(v->{prefs.edit().putString(NAME,name.getText().toString().trim()).putString(YEAR,year.getText().toString().trim()).apply();toast("تم حفظ الإعدادات ✓");});back.setOnClickListener(v->home());}
 private void profileScreen(){base("المعلومات الشخصية");content.addView(tv("المعرف الشخصي\n"+prefs.getString(ID,""),18,gold()),lp(-1,-2,8));content.addView(tv("الاسم الثلاثي\n"+prefs.getString(NAME,""),18,Color.WHITE),lp(-1,-2,8));content.addView(tv("المواليد\n"+prefs.getString(YEAR,""),18,Color.WHITE),lp(-1,-2,8));Button b=btn("رجوع");content.addView(b);b.setOnClickListener(v->home());}
 private void archiveScreen(){base("المحفوظات");content.addView(tv("الوسائط المحفوظة",20,gold()));content.addView(tv("سيتم عرض الصور والمقاطع المرسلة والمستلمة هنا.",16,Color.WHITE));Button b=btn("رجوع");content.addView(b);b.setOnClickListener(v->home());}
 private void pickImage(){startActivityForResult(new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI),702);}
 private void startRecording(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},701);return;}try{File f=new File(getCacheDir(),"wethaq_"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(f.getAbsolutePath());recorder.prepare();recorder.start();recording=true;toast("جارٍ تسجيل الصوت… اضغط 🎙 للإيقاف");}catch(Exception e){stopRecording(false);toast("تعذر تشغيل الميكروفون");}}
 private void stopRecording(boolean notify){if(recorder!=null){try{recorder.stop();}catch(Exception ignored){}try{recorder.release();}catch(Exception ignored){}recorder=null;}recording=false;if(notify)toast("تم تسجيل المقطع الصوتي ✓");}
 private JSONArray contacts(){try{return new JSONArray(prefs.getString(CONTACTS,"[]"));}catch(Exception e){return new JSONArray();}}
 private void startPolling(){stopPolling();poller=()->{if(activeId!=null)loadMessages();if(hasToken())h.postDelayed(poller,2500);};h.postDelayed(poller,1000);}
 private void stopPolling(){if(poller!=null)h.removeCallbacks(poller);poller=null;}
 private String deviceKey(){String k=prefs.getString("device_key","");if(k.length()>20)return k;k="wethaq-"+UUID.randomUUID();prefs.edit().putString("device_key",k).apply();return k;}
 private String auth(){return "Bearer "+prefs.getString(T,"");}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 private String error(HttpResult r){try{JSONObject o=new JSONObject(r.body);String x=o.optString("error");if(!x.isEmpty())return x;x=o.optString("message");if(!x.isEmpty())return x;}catch(Exception ignored){}return "HTTP "+r.code;}
 private HttpResult request(String method,String path,String body,String authorization)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(15000);c.setRequestProperty("Accept","application/json");if(authorization!=null)c.setRequestProperty("Authorization",authorization);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");byte[] z=body.getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(z.length);try(OutputStream o=c.getOutputStream()){o.write(z);}}int code=c.getResponseCode();InputStream in=code>=200&&code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(in!=null){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);in.close();}c.disconnect();return new HttpResult(code,new String(out.toByteArray(),StandardCharsets.UTF_8));}
 private static final class HttpResult{final int code;final String body;HttpResult(int c,String b){code=c;body=b;}}
}
