package com.wethaq.app

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.security.SecureRandom
import java.util.Calendar
import java.util.concurrent.TimeUnit

class MainActivity : AppCompatActivity() {
    private val prefs by lazy { getSharedPreferences("wethaq_v6", Context.MODE_PRIVATE) }
    private val http = OkHttpClient.Builder().connectTimeout(8, TimeUnit.SECONDS).readTimeout(12, TimeUnit.SECONDS).writeTimeout(12, TimeUnit.SECONDS).build()
    private val apiBase = "https://wethaq-backend-production.up.railway.app"
    private val teal = Color.rgb(0,137,123); private val navy = Color.rgb(17,38,54); private val bgc = Color.rgb(247,249,250); private val line = Color.rgb(220,228,231); private val gray = Color.rgb(98,112,122)
    private val myName get() = prefs.getString("name","") ?: ""
    private val myYear get() = prefs.getInt("year",0)
    private val myId get() = prefs.getString("id","") ?: ""
    private val token get() = prefs.getString("token","") ?: ""

    override fun onCreate(state: Bundle?) { super.onCreate(state); window.statusBarColor=Color.WHITE; window.navigationBarColor=bgc; window.decorView.systemUiVisibility=View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR; if(myName.isBlank()||myId.isBlank()) welcome() else home() }
    override fun onResume(){ super.onResume(); if(myId.isNotBlank()) flushPendingMessages() }
    private fun dp(n:Int)=(n*resources.displayMetrics.density).toInt()
    private fun box(c:Int,r:Int=18,stroke:Int?=null)=android.graphics.drawable.GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat();if(stroke!=null)setStroke(dp(1),stroke)}
    private fun root()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bgc);layoutDirection=View.LAYOUT_DIRECTION_RTL}
    private fun text(s:String,size:Float=16f,c:Int=navy,bold:Boolean=false)=TextView(this).apply{text=s;textSize=size;setTextColor(c);gravity=Gravity.CENTER_VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;textAlignment=View.TEXT_ALIGNMENT_VIEW_START;if(bold)typeface=Typeface.DEFAULT_BOLD}
    private fun center(s:String,size:Float=16f,c:Int=navy,bold:Boolean=false)=text(s,size,c,bold).apply{gravity=Gravity.CENTER;textAlignment=View.TEXT_ALIGNMENT_CENTER}
    private fun btn(s:String,a:()->Unit,c:Int=teal)=TextView(this).apply{text=s;textSize=15f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD;background=box(c,16);setPadding(dp(12),dp(8),dp(12),dp(8));setOnClickListener{a()}}
    private fun outline(s:String,a:()->Unit)=TextView(this).apply{text=s;textSize=14f;setTextColor(navy);gravity=Gravity.CENTER;typeface=Typeface.DEFAULT_BOLD;background=box(Color.WHITE,16,line);setOnClickListener{a()}}
    private fun edit(h:String,num:Boolean=false)=EditText(this).apply{hint=h;textSize=16f;setTextColor(navy);setHintTextColor(gray);setSingleLine(true);inputType=if(num)InputType.TYPE_CLASS_NUMBER else InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_FLAG_CAP_SENTENCES;background=box(Color.WHITE,16,line);setPadding(dp(15),0,dp(15),0);gravity=Gravity.CENTER_VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL}
    private fun add(p:LinearLayout,v:View,h:Int=-2,w:Float=0f,m:Int=0){val lp=LinearLayout.LayoutParams(-1,if(h==-2)-2 else dp(h),w);if(m>0)lp.setMargins(dp(m),dp(m),dp(m),dp(m));p.addView(v,lp)}
    private fun avatar(size:Int=70)=ImageView(this).apply{setImageResource(R.drawable.profile_photo);scaleType=ImageView.ScaleType.CENTER_CROP;background=box(Color.WHITE,100,teal);setPadding(dp(2),dp(2),dp(2),dp(2))}
    private fun header(t:String,s:String="",back:(()->Unit)?=null)=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(14),dp(8),dp(14),dp(8));val x=LinearLayout(this@MainActivity).apply{orientation=LinearLayout.VERTICAL};add(x,text(t,22f,navy,true),30);if(s.isNotBlank())add(x,text(s,12f,gray),22);add(this,x,0,1f);if(back!=null)addView(outline("‹ رجوع",back),LinearLayout.LayoutParams(dp(82),dp(44)))}
    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()

    private fun welcome(){val r=root();val sc=ScrollView(this);val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(22),dp(28),dp(22),dp(28))};add(c,avatar(128),128,0f,4);add(c,center("وَثاق",40f,navy,true),54);add(c,center("هوية وتواصل عربي مستقل",18f,gray,true),32);add(c,center("المعرف يُحفظ على الخادم ليظهر من أي هاتف، وتبقى بياناتك المهمة متاحة دون إنترنت.",14f,gray),55);add(c,btn("⌁  تسجيل الدخول",{login()}),58,0f,5);add(c,btn("＋  إنشاء هوية جديدة",{register()},Color.rgb(28,71,91)),58,0f,5);sc.addView(c);add(r,sc,0,1f);setContentView(r)}

    private fun login(){identityForm("تسجيل الدخول","الاسم الثلاثي + سنة الميلاد فقط","دخول إلى وَثاق"){n,y->if(myName==n&&myYear==y&&myId.isNotBlank()){home();return@identityForm};request("POST","/api/login",JSONObject().put("name",n).put("birthYear",y).put("deviceKey",deviceKey()),false){ok,b->runOnUiThread{if(ok){saveServer(b);home()}else toast("تعذر الوصول إلى الخادم. تحقق من الإنترنت ثم أعد المحاولة.")}}}}
    private fun register(){identityForm("إنشاء هوية وَثاق","المعرف يُنشر على الخادم ليجده الآخرون","إنشاء المعرف والدخول"){n,y->request("POST","/api/identity",JSONObject().put("name",n).put("birthYear",y).put("deviceKey",deviceKey()),false){ok,b->runOnUiThread{if(ok){saveServer(b);home()}else{saveLocal(n,y);toast("تم إنشاء هوية محلية. ستُزامن وتصبح قابلة للعثور عند عودة الإنترنت.");home()}}}}}
    private fun identityForm(title:String,sub:String,action:String,submit:(String,Int)->Unit){val r=root();val sc=ScrollView(this);val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(20),dp(10),dp(20),dp(24))};add(c,header(title,sub,{welcome()}));add(c,avatar(96),96,0f,8);add(c,text("الاسم الثلاثي",14f,navy,true),30,0f,2);val n=edit("مثال: حاتم حسين الحاج رمضان");add(c,n,56,0f,2);add(c,text("سنة الميلاد",14f,navy,true),30,0f,6);val y=edit("مثال: 1995",true);add(c,y,56,0f,2);val id=center("سيظهر معرفك هنا",14f,teal,true);id.background=box(Color.WHITE,16,line);add(c,id,58,0f,10);val update={val a=n.text.toString().trim();val b=y.text.toString().trim().toIntOrNull();id.text=if(a.isBlank()||b==null)"سيظهر معرفك هنا" else "@${makeId(a,b)}"};n.setOnFocusChangeListener{_,_->update()};y.setOnFocusChangeListener{_,_->update()};add(c,center("لا تُنشئ هوية محلية جديدة إذا كنت تريد نفس المعرف الموجود على الخادم.",12f,gray),48,0f,4);add(c,btn(action,{val a=n.text.toString().trim();val b=y.text.toString().trim().toIntOrNull();val words=a.split(Regex("\\s+")).filter{it.isNotBlank()};val max=Calendar.getInstance().get(Calendar.YEAR);if(words.size<3){toast("اكتب الاسم الثلاثي");return@btn};if(b==null||b !in 1900..max){toast("سنة الميلاد غير صحيحة");return@btn};submit(a,b)}),58,0f,6);add(c,outline("إلغاء",{welcome()}),50,0f,3);sc.addView(c);add(r,sc,0,1f);setContentView(r)}

    private fun home(){val r=root();add(r,header("وَثاق","مرحبًا $myName"));val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(14),dp(8),dp(14),dp(14))};val p=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;background=box(Color.WHITE,20,line);setPadding(dp(10),dp(10),dp(10),dp(10))};p.addView(avatar(58));add(p,text("$myName\n@$myId",13f,navy,true),0,1f,10);add(c,p,82,0f,4);val q=edit("ابحث بالاسم أو معرف وَثاق");add(c,q,54,0f,4);add(c,btn("⌕  بحث عن شخص",{search(q.text.toString())}),54,0f,4);add(c,btn("◉  جهات الاتصال",{contacts()},Color.rgb(28,71,91)),54,0f,4);add(c,btn("◎  ملفي ومعرفي",{profile()},Color.rgb(70,90,100)),54,0f,4);add(c,center("✓ يمكنك فتح ملفك وجهات الاتصال والبحث في النتائج المحفوظة دون إنترنت.",12f,gray),55,0f,6);add(c,outline("↪  تسجيل الخروج",{prefs.edit().clear().apply();welcome()}),50,0f,4);add(r,c,0,1f);setContentView(r);flushPendingMessages()}
    private fun profile(){val r=root();val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(20),dp(12),dp(20),dp(20))};add(c,header("ملفي","هوية وَثاق",{home()}));add(c,avatar(110),110,0f,12);add(c,center(myName,22f,navy,true),38);add(c,center("@$myId",15f,teal,true),42);add(c,btn("⧉  نسخ المعرف",{(getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager).setPrimaryClip(ClipData.newPlainText("Wethaq ID",myId));toast("تم نسخ المعرف")}),54,0f,8);add(c,center("المعرف محفوظ محليًا، ويمكن عرضه دون اتصال.",13f,gray),42,0f,5);add(r,c,0,1f);setContentView(r)}

    private fun search(q:String){val query=q.trim().removePrefix("@").trim();if(query.length<2){toast("اكتب اسمًا أو معرفًا");return};val local=readCache().filter{it.optString("wethaq_id").contains(query,true)||it.optString("name").contains(query,true)};if(local.isNotEmpty())showResults(local.toJSONArray(),"نتائج محفوظة محليًا"){serverSearch(query)}else serverSearch(query)}
    private fun serverSearch(query:String){val encoded=Uri.encode(query);request("GET","/api/search?q=$encoded",null,false){ok,b->runOnUiThread{if(ok){val arr=b.optJSONArray("users")?:JSONArray();cacheUsers(arr);showResults(arr,"نتائج البحث على الخادم",null)}else toast("لا يوجد اتصال بالخادم. ابحث فقط ضمن النتائج المحفوظة.")}}}
    private fun showResults(arr:JSONArray,title:String,onRetry:(()->Unit)?){val r=root();val sc=ScrollView(this);val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(14),dp(8),dp(14),dp(20))};add(c,header("البحث",title,{home()}));if(arr.length()==0){add(c,center("لم يتم العثور على هذا المعرف.",16f,navy,true),70,0f,8);if(onRetry!=null)add(c,btn("↻ البحث عبر الإنترنت",onRetry),54,0f,5)}else{for(i in 0 until arr.length()){val u=arr.optJSONObject(i)?:continue;val id=u.optString("wethaq_id");val name=u.optString("name");val card=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;background=box(Color.WHITE,18,line);setPadding(dp(14),dp(10),dp(14),dp(10))};add(card,text(name,17f,navy,true),30);add(card,text("@$id",14f,teal,true),28);add(card,text(if(u.optBoolean("online",false))"● متصل" else "○ آخر ظهور محفوظ",12f,gray),25);add(card,btn("＋ إضافة إلى جهات الاتصال",{addContact(id)}),48,0f,4);add(c,card,0,1f,5)}};sc.addView(c);add(r,sc,0,1f);setContentView(r)}
    private fun addContact(id:String){request("POST","/api/contacts",JSONObject().put("wethaqId",id),true){ok,b->runOnUiThread{if(ok){cacheUser(b.optJSONObject("contact")?:JSONObject());toast("تمت إضافة جهة الاتصال");contacts()}else toast("تعذر الإضافة الآن. يمكنك المحاولة عند عودة الإنترنت.")}}}
    private fun contacts(){val r=root();val sc=ScrollView(this);val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(14),dp(8),dp(14),dp(20))};add(c,header("جهات الاتصال","تعمل من الذاكرة دون إنترنت",{home()}));val cached=readContacts();if(cached.length()>0){for(i in 0 until cached.length()){val u=cached.optJSONObject(i)?:continue;val id=u.optString("wethaq_id");val name=u.optString("name");add(c,btn("$name\n@$id",{conversation(id,name)}),70,0f,5)}}else add(c,center("لا توجد جهات اتصال محفوظة.",60f,gray),80,0f,5);if(token.isNotBlank())add(c,btn("↻ تحديث جهات الاتصال من الخادم",{syncContacts()}),54,0f,5);sc.addView(c);add(r,sc,0,1f);setContentView(r)}
    private fun syncContacts(){request("GET","/api/contacts",null,true){ok,b->runOnUiThread{if(ok){cacheContacts(b.optJSONArray("contacts")?:JSONArray());toast("تمت المزامنة");contacts()}else toast("لا يوجد اتصال بالإنترنت")}}}
    private fun conversation(id:String,name:String){val r=root();val sc=ScrollView(this);val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setPadding(dp(14),dp(8),dp(14),dp(14))};add(c,header(name,"@$id",{contacts()}));val history=readMessages(id);for(i in 0 until history.length()){val m=history.optJSONObject(i)?:continue;val mine=m.optString("sender_id")==prefs.getString("server_id","");add(c,text(if(mine)"أنت: ${m.optString("body")}" else "$name: ${m.optString("body")}",15f,if(mine)teal else navy,mine),0,1f,4)};val input=edit("اكتب رسالة");add(c,input,54,0f,4);add(c,btn("إرسال",{val body=input.text.toString().trim();if(body.isNotBlank()){sendMessage(id,body);input.setText("")}}),54,0f,4);add(c,center("يمكن كتابة الرسالة دون إنترنت. ستبقى محفوظة محليًا وتُرسل تلقائيًا عند عودة الاتصال.",12f,gray),48,0f,4);sc.addView(c);add(r,sc,0,1f);setContentView(r);loadMessagesOnline(id)}
    private fun sendMessage(to:String,body:String){if(token.isBlank()){toast("هذه الهوية محلية فقط. اتصل بالإنترنت لمزامنتها أولًا.");return};val obj=JSONObject().put("to",to).put("body",body);request("POST","/api/messages",obj,true){ok,_->runOnUiThread{if(ok)toast("تم إرسال الرسالة")else{queueMessage(obj);cacheMessage(to,JSONObject().put("sender_id",prefs.getString("server_id","")).put("body",body).put("status","queued"));toast("لا يوجد اتصال. حُفظت الرسالة وسترسل تلقائيًا.")}}}}
    private fun loadMessagesOnline(id:String){request("GET","/api/messages/${Uri.encode(id)}",null,true){ok,b->if(ok)runOnUiThread{cacheMessages(id,b.optJSONArray("messages")?:JSONArray())}}}
    private fun queueMessage(o:JSONObject){val a=JSONArray(prefs.getString("pending_messages","[]")?:"[]");a.put(o);prefs.edit().putString("pending_messages",a.toString()).apply()}
    private fun flushPendingMessages(){if(token.isBlank())return;val old=JSONArray(prefs.getString("pending_messages","[]")?:"[]");if(old.length()==0)return;Thread{for(i in 0 until old.length()){val o=old.optJSONObject(i)?:continue;request("POST","/api/messages",o,true){_,_->}}}.start();prefs.edit().remove("pending_messages").apply()}

    private fun request(method:String,path:String,json:JSONObject?,auth:Boolean,done:(Boolean,JSONObject)->Unit){Thread{try{val rb=Request.Builder().url(apiBase+path);if(auth&&token.isNotBlank())rb.header("Authorization","Bearer $token");val b=json?.toString()?.toRequestBody("application/json".toMediaType());if(method=="POST")rb.post(b?:"{}".toRequestBody("application/json".toMediaType()))else rb.get();http.newCall(rb.build()).execute().use{res->val raw=res.body?.string()? :"";var out=JSONObject();try{out=JSONObject(raw)}catch(_:Exception){};done(res.isSuccessful,out)}}catch(_:Exception){done(false,JSONObject())}}.start()}
    private fun deviceKey():String{val old=prefs.getString("device","")?:"";if(old.length>=48)return old;val b=ByteArray(32);SecureRandom().nextBytes(b);val k=b.joinToString(""){String.format("%02x",it)};prefs.edit().putString("device",k).apply();return k}
    private fun saveServer(b:JSONObject){val u=b.optJSONObject("user")?:return;prefs.edit().putString("token",b.optString("token")).putString("name",u.optString("name")).putInt("year",u.optInt("birth_year")).putString("id",u.optString("wethaq_id")).putString("server_id",u.optString("id")).apply();cacheUser(u)}
    private fun saveLocal(n:String,y:Int){prefs.edit().putString("name",n).putInt("year",y).putString("id",makeId(n,y)).remove("token").apply()}
    private fun makeId(name:String,year:Int):String{val known=mapOf("حاتم" to "Hatem","حسين" to "Hussin","الحاج" to "Al_Haj","رمضان" to "Ramadan","محمد" to "Mohammad","أحمد" to "Ahmad","علي" to "Ali","خالد" to "Khaled","سارة" to "Sara","نور" to "Nour","هدى" to "Huda","وسام" to "Wisam","يامن" to "Yamen","هشام" to "Hisham","أيمن" to "Ayman","حسام" to "Hossam");val map=mapOf('ا' to "a",'أ' to "a",'إ' to "i",'آ' to "a",'ب' to "b",'ت' to "t",'ث' to "th",'ج' to "j",'ح' to "h",'خ' to "kh",'د' to "d",'ذ' to "dh",'ر' to "r",'ز' to "z",'س' to "s",'ش' to "sh",'ص' to "s",'ض' to "d",'ط' to "t",'ظ' to "z",'ع' to "a",'غ' to "gh",'ف' to "f",'ق' to "q",'ك' to "k",'ل' to "l",'م' to "m",'ن' to "n",'ه' to "h",'و' to "w",'ي' to "y",'ى' to "a",'ة' to "h");return(name.replace("ـ","").split(Regex("[\\s،,]+" )).filter{it.isNotBlank()}.map{w->known[w]?:w.map{ch->map[ch]?:if(ch.isLetterOrDigit())ch.toString()else""}.joinToString("").replaceFirstChar{it.uppercase()}}.filter{it.isNotBlank()}.joinToString("_")+year}
    private fun readCache():List<JSONObject>{val a=JSONArray(prefs.getString("user_cache","[]")?:"[]");return(0 until a.length()).mapNotNull{a.optJSONObject(it)}}
    private fun cacheUser(u:JSONObject){if(u.optString("wethaq_id").isBlank())return;val a=JSONArray();readCache().filterNot{it.optString("wethaq_id")==u.optString("wethaq_id")}.forEach{a.put(it)};a.put(u);prefs.edit().putString("user_cache",a.toString()).apply()}
    private fun cacheUsers(a:JSONArray){for(i in 0 until a.length())a.optJSONObject(i)?.let{cacheUser(it)}}
    private fun cacheContacts(a:JSONArray){prefs.edit().putString("contacts_cache",a.toString()).apply();cacheUsers(a)}
    private fun readContacts()=JSONArray(prefs.getString("contacts_cache","[]")?:"[]")
    private fun cacheMessage(id:String,m:JSONObject){val a=readMessages(id);a.put(m);prefs.edit().putString("messages_$id",a.toString()).apply()}
    private fun cacheMessages(id:String,a:JSONArray){prefs.edit().putString("messages_$id",a.toString()).apply()}
    private fun readMessages(id:String)=JSONArray(prefs.getString("messages_$id","[]")?:"[]")
    private fun JSONArray.toJSONArray():JSONArray{val a=JSONArray();for(i in 0 until length())a.put(optJSONObject(i));return a}
}
