package com.wethaq.app;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.BitmapDrawable;import android.graphics.drawable.Drawable;import android.graphics.drawable.GradientDrawable;import android.graphics.drawable.StateListDrawable;import android.media.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.text.InputType;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public final class MainActivity extends Activity{
 private static final String API="https://wethaq-backend-production.up.railway.app",P="wethaq",T="token",ID="wethaq_id",NAME="name",YEAR="birth_year",CONTACTS="saved_contacts";
 private final ExecutorService io=Executors.newSingleThreadExecutor();private final Handler h=new Handler(Looper.getMainLooper());private SharedPreferences prefs;private LinearLayout root,content,messages;private EditText input;private String activeId,activeName;private Runnable poller;private MediaRecorder recorder;private boolean recording;private long lastInboxId;private String pendingImageData,pendingAudioData,pendingMime;private int pendingMediaType;private ProgressDialog progress;
 private int gold(){return Color.rgb(212,175,55);}private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}private boolean hasToken(){return prefs.getString(T,"").length()>10;}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences(P,MODE_PRIVATE);createChannel();if(hasToken())home();else login();}
 @Override protected void onDestroy(){stopPolling();stopRecording(false);dismissProgress();io.shutdownNow();super.onDestroy();}
 private TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(dp(14),dp(10),dp(14),dp(10));t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 private EditText field(String s){EditText e=new EditText(this);e.setHint(s);e.setHintTextColor(Color.LTGRAY);e.setTextColor(Color.WHITE);e.setTextSize(18);e.setSingleLine(true);e.setPadding(dp(16),0,dp(16),0);e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(25,25,25));d.setCornerRadius(dp(14));d.setStroke(dp(2),Color.rgb(90,90,90));e.setBackground(d);e.setMinHeight(dp(64));return e;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(20);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setGravity(Gravity.CENTER);b.setPadding(dp(12),0,dp(12),0);b.setMinimumHeight(dp(76));b.setMinWidth(0);b.setMinimumWidth(0);b.setStateListAnimator(null);b.setVisibility(View.VISIBLE);b.setEnabled(true);b.setClickable(true);b.setFocusable(true);b.setIncludeFontPadding(true);StateListDrawable states=new StateListDrawable();GradientDrawable normal=new GradientDrawable();normal.setColor(Color.rgb(28,28,32));normal.setCornerRadius(dp(16));normal.setStroke(dp(3),gold());GradientDrawable pressed=new GradientDrawable();pressed.setColor(Color.rgb(55,45,24));pressed.setCornerRadius(dp(16));pressed.setStroke(dp(3),gold());GradientDrawable disabled=new GradientDrawable();disabled.setColor(Color.rgb(55,55,58));disabled.setCornerRadius(dp(16));disabled.setStroke(dp(2),Color.DKGRAY);states.addState(new int[]{android.R.attr.state_pressed},pressed);states.addState(new int[]{-android.R.attr.state_enabled},disabled);states.addState(new int[]{},normal);b.setBackground(states);b.setElevation(dp(7));b.setTranslationZ(dp(1));b.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)v.animate().scaleX(.97f).scaleY(.94f).translationZ(0).setDuration(70).start();else if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL)v.animate().scaleX(1f).scaleY(1f).translationZ(dp(1)).setDuration(100).start();return false;});return b;}
 private LinearLayout.LayoutParams lp(int w,int h,int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.bottomMargin=dp(m);return p;}
 private void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(16));root.setBackgroundColor(Color.BLACK);TextView top=tv(title,22,gold());top.setGravity(Gravity.CENTER);top.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(top,lp(-1,64,8));ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private void showProgress(String message){h.post(()->{dismissProgress();progress=new ProgressDialog(this);progress.setIndeterminate(true);progress.setCancelable(false);progress.setMessage(message);progress.show();});}
 private void dismissProgress(){h.post(()->{if(progress!=null&&progress.isShowing())progress.dismiss();progress=null;});}
 private void login(){base("وَثاق");TextView x=tv("هوية رقمية آمنة",25,Color.WHITE);x.setGravity(Gravity.CENTER);content.addView(x,lp(-1,-2,18));EditText n=field("الاسم الثلاثي"),y=field("سنة الميلاد");y.setInputType(InputType.TYPE_CLASS_NUMBER);content.addView(n,lp(-1,64,10));content.addView(y,lp(-1,64,14));Button l=btn("تسجيل الدخول"),c=btn("إنشاء هوية جديدة");content.addView(l,lp(-1,76,10));content.addView(c,lp(-1,76,14));l.bringToFront();c.bringToFront();l.setEnabled(true);c.setEnabled(true);content.addView(tv("المؤسس: حاتم حسين الحاج رمضان",14,gold()));l.setOnClickListener(v->{click();auth(n.getText().toString().trim(),y.getText().toString().trim(),false);});c.setOnClickListener(v->{click();auth(n.getText().toString().trim(),y.getText().toString().trim(),true);});}
 private void auth(String n,String y,boolean create){if(n.split("\\s+").length<3||!y.matches("\\d{4}")){toast("أدخل الاسم الثلاثي وسنة الميلاد");return;}io.execute(()->{try{JSONObject q=new JSONObject();q.put("name",n);q.put("birthYear",Integer.parseInt(y));q.put("deviceKey",deviceKey());HttpResult r=request("POST",create?"/api/identity":"/api/login",q.toString(),null);if(r.code>=200&&r.code<300){JSONObject o=new JSONObject(r.body),u=o.getJSONObject("user");prefs.edit().putString(T,o.getString("token")).putString(ID,u.optString("wethaq_id")).putString("db_user_id",u.optString("id")).putString(NAME,u.optString("name",n)).putString(YEAR,y).apply();h.post(this::home);}else{final HttpResult result=r;h.post(()->toast(error(result)));}}catch(Exception e){h.post(()->toast("تعذر الاتصال بالخادم"));}});}
 private void startMessageService(){try{Intent i=new Intent(this,WethaqMessageService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception ignored){}}
 private void home(){stopPolling();base("المؤسس: حاتم حسين الحاج رمضان");TextView me=tv(prefs.getString(NAME,"")+"\n"+prefs.getString(ID,""),18,Color.WHITE);me.setGravity(Gravity.CENTER);content.addView(me,lp(-1,-2,12));menu("⌕  البحث",this::searchScreen);menu("◉  جهات الاتصال",this::contactsScreen);menu("⚙  الإعدادات",this::settingsScreen);menu("♙  المعلومات الشخصية",this::profileScreen);menu("⚠  الشكاوى والتواصل مع المؤسس",this::sendComplaint);if(isOwner())menu("🛡  لوحة تحكم المؤسس",this::adminScreen);Button out=btn("تسجيل الخروج");content.addView(out,lp(-1,76,8));out.setOnClickListener(v->{click();stopService(new Intent(this,WethaqMessageService.class));prefs.edit().clear().apply();login();});if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestNotifications();startMessageService();startPolling();}
 private void menu(String s,Runnable r){Button b=btn(s);content.addView(b,lp(-1,76,8));b.setOnClickListener(v->{click();r.run();});}
 private void searchScreen(){base("البحث عن مستخدم");EditText q=field("الاسم أو معرف وَثاق");Button go=btn("بحث"),back=btn("رجوع");LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(q,lp(-1,64,8));content.addView(go,lp(-1,76,8));content.addView(list);content.addView(back,lp(-1,76,8));go.setOnClickListener(v->{click();search(q.getText().toString().trim(),list);});back.setOnClickListener(v->{click();home();});}
 private void search(String q,LinearLayout list){if(q.length()<2){toast("أدخل حرفين على الأقل");return;}io.execute(()->{try{HttpResult r=request("GET","/api/search?q="+URLEncoder.encode(q,"UTF-8"),null,null);if(r.code==200){JSONArray a=new JSONObject(r.body).optJSONArray("users");h.post(()->{list.removeAllViews();if(a==null||a.length()==0){list.addView(tv("لا توجد نتائج",16,Color.GRAY));return;}for(int i=0;i<a.length();i++){JSONObject u=a.optJSONObject(i);String id=u.optString("wethaq_id"),n=u.optString("name");LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);ImageView avatar=new ImageView(this);avatar.setScaleType(ImageView.ScaleType.CENTER_CROP);avatar.setImageDrawable(defaultAvatar());row.addView(avatar,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);TextView nm=tv(n,18,Color.WHITE),wi=tv(id,13,Color.LTGRAY);text.addView(nm);text.addView(wi);row.addView(text,new LinearLayout.LayoutParams(0,-2,1));Button save=btn("حفظ");row.addView(save,new LinearLayout.LayoutParams(dp(92),dp(68)));list.addView(row,lp(-1,-2,10));loadAvatarInto(id,avatar);save.setOnClickListener(v->{click();saveContact(id,n);});row.setOnClickListener(v->{click();saveContact(id,n);conversation(id,n);});}});}else{final HttpResult result=r;h.post(()->toast(error(result)));}}catch(Exception e){h.post(()->toast("فشل البحث"));}});}
 private Drawable defaultAvatar(){GradientDrawable d=new GradientDrawable();d.setShape(GradientDrawable.OVAL);d.setColor(Color.rgb(48,48,54));d.setStroke(dp(2),gold());d.setSize(dp(50),dp(50));return d;}
 private void saveContact(String id,String n){try{JSONArray a=contacts();for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("wethaq_id"))){toast("محفوظ مسبقًا");return;}JSONObject o=new JSONObject();o.put("wethaq_id",id);o.put("name",n);a.put(o);prefs.edit().putString(CONTACTS,a.toString()).apply();toast("تم الحفظ ✓");}catch(Exception e){toast("فشل الحفظ");}}
 private void contactsScreen(){base("جهات الاتصال");Button back=btn("رجوع");content.addView(back,lp(-1,76,8));back.setOnClickListener(v->{click();home();});JSONArray a=contacts();if(a.length()==0){content.addView(tv("لا توجد جهات اتصال محفوظة",16,Color.GRAY));return;}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);String id=o.optString("wethaq_id"),n=o.optString("name");LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);ImageView avatar=new ImageView(this);avatar.setImageDrawable(defaultAvatar());row.addView(avatar,new LinearLayout.LayoutParams(dp(54),dp(54)));TextView name=tv(n,18,Color.WHITE);row.addView(name,new LinearLayout.LayoutParams(0,dp(76),1));content.addView(row,lp(-1,-2,8));loadAvatarInto(id,avatar);row.setOnClickListener(v->{click();conversation(id,n);});}}
 private void conversation(String id,String n){stopPolling();activeId=id;activeName=n;base(n);Button call=btn("📹 مكالمة فيديو"),audioCall=btn("📞 مكالمة صوتية");content.addView(call,lp(-1,76,6));content.addView(audioCall,lp(-1,76,6));audioCall.setOnClickListener(v->{click();startAudioCall();});call.setOnClickListener(v->{click();startVideoCall();});messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(messages);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);Button mic=btn("🎙"),gallery=btn("▧"),send=btn("إرسال");input=field("اكتب رسالة…");bar.addView(mic,new LinearLayout.LayoutParams(dp(64),dp(76)));bar.addView(gallery,new LinearLayout.LayoutParams(dp(64),dp(76)));bar.addView(input,new LinearLayout.LayoutParams(0,dp(76),1));bar.addView(send,new LinearLayout.LayoutParams(dp(88),dp(76)));root.addView(bar);Button back=btn("‹ جهات الاتصال");root.addView(back,new LinearLayout.LayoutParams(-1,dp(76)));back.setOnClickListener(v->{click();contactsScreen();});send.setOnClickListener(v->{click();send();});mic.setOnClickListener(v->{click();if(recording)stopRecording(true);else startRecording();});gallery.setOnClickListener(v->{click();pickImage();});loadMessages();startPolling();}
 private void loadMessages(){final String target=activeId;if(target==null)return;io.execute(()->{try{HttpResult r=request("GET","/api/messages/"+URLEncoder.encode(target,"UTF-8"),null,auth());if(r.code==200){JSONArray a=new JSONObject(r.body).optJSONArray("messages");h.post(()->{if(target.equals(activeId))render(a);});}}catch(Exception ignored){}});}
 private void render(JSONArray a){if(messages==null)return;messages.removeAllViews();String meW=prefs.getString(ID,"");String meDb=prefs.getString("db_user_id","");if(a==null||a.length()==0){messages.addView(tv("ابدأ المحادثة الآن",17,Color.GRAY));return;}for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;String s=m.optString("sender_id"),senderW=m.optString("sender_wethaq_id"),senderName=m.optString("sender_name","مستخدم");String type=m.optString("message_type","text");boolean mine=meW.equals(senderW)||meDb.equals(s);LinearLayout line=new LinearLayout(this);line.setOrientation(LinearLayout.HORIZONTAL);line.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);ImageView av=new ImageView(this);av.setScaleType(ImageView.ScaleType.CENTER_CROP);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(dp(44),dp(44));ap.setMargins(dp(4),dp(4),dp(4),dp(4));av.setLayoutParams(ap);if(!senderW.isEmpty())loadAvatarInto(senderW,av);line.addView(av);LinearLayout bubble=new LinearLayout(this);bubble.setOrientation(LinearLayout.VERTICAL);bubble.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);TextView name=tv(mine?"أنت":senderName,17,mine?gold():Color.WHITE);name.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);bubble.addView(name);if("image".equals(type)){ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setMaxHeight(dp(280));im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);try{byte[] z=Base64.getDecoder().decode(m.optString("audio_data"));im.setImageBitmap(BitmapFactory.decodeByteArray(z,0,z.length));}catch(Exception e){}bubble.addView(im);}else if("audio".equals(type)){TextView b=tv("▶ رسالة صوتية",19,Color.WHITE);String data=m.optString("audio_data");b.setOnClickListener(v->playAudio(data));bubble.addView(b);}else{TextView b=tv(m.optString("body",m.optString("text")),19,mine?Color.BLACK:Color.WHITE);b.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);bubble.addView(b);TextView st=tv(mine?"✓✓":"✓",14,mine?Color.BLACK:Color.LTGRAY);st.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);bubble.addView(st);}GradientDrawable d=new GradientDrawable();d.setColor(mine?gold():Color.rgb(32,32,32));d.setCornerRadius(dp(14));bubble.setPadding(dp(12),dp(8),dp(12),dp(8));bubble.setBackground(d);line.addView(bubble,new LinearLayout.LayoutParams(0,-2,1));messages.addView(line,lp(-1,-2,8));}}
 private void addLocalContact(String id,String name){try{if(id==null||id.isEmpty())return;JSONArray a=contacts();for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("wethaq_id")))return;JSONObject o=new JSONObject();o.put("wethaq_id",id);o.put("name",name==null?"مستخدم":name);a.put(o);prefs.edit().putString(CONTACTS,a.toString()).apply();}catch(Exception ignored){}}
 private void send(){
 final String target=activeId;if(target==null||target.trim().isEmpty())return;
 if(pendingAudioData!=null&&!pendingAudioData.isEmpty()){final String data=pendingAudioData;final String mime=pendingMime==null?"audio/mp4":pendingMime;io.execute(()->{try{JSONObject q=new JSONObject();q.put("to",target);q.put("audioBase64",data);q.put("mimeType",mime);HttpResult r=request("POST","/api/messages/audio",q.toString(),auth());h.post(()->{if(r.code>=200&&r.code<300){pendingAudioData=null;pendingMime=null;pendingMediaType=0;clearComposerMedia();loadMessages();toast("تم إرسال التسجيل الصوتي ✓");}else toast(error(r));});}catch(Exception e){h.post(()->toast("فشل إرسال التسجيل الصوتي"));}});return;}
 if(pendingImageData!=null&&!pendingImageData.isEmpty()){final String data=pendingImageData;final String mime=pendingMime==null?"image/jpeg":pendingMime;io.execute(()->{try{JSONObject q=new JSONObject();q.put("to",target);q.put("imageBase64",data);q.put("mimeType",mime);HttpResult r=request("POST","/api/messages/image",q.toString(),auth());h.post(()->{if(r.code>=200&&r.code<300){pendingImageData=null;pendingMime=null;pendingMediaType=0;clearComposerMedia();loadMessages();toast("تم إرسال الصورة ✓");}else toast(error(r));});}catch(Exception e){h.post(()->toast("فشل إرسال الصورة"));}});return;}
 String text=input==null?"":input.getText().toString().trim();if(text.isEmpty())return;io.execute(()->{try{JSONObject q=new JSONObject();q.put("to",target);q.put("body",text);HttpResult r=request("POST","/api/messages",q.toString(),auth());h.post(()->{if(r.code>=200&&r.code<300){input.setText("");loadMessages();}else toast(error(r));});}catch(Exception e){h.post(()->toast("فشل الإرسال"));}});
}
 private void clearComposerMedia(){if(input!=null){input.setCompoundDrawables(null,null,null,null);input.setHint("اكتب رسالة…");input.setText("");}}

 

 

 

 

 
 private void settingsScreen(){base("الإعدادات");Button n=btn("🔔 إشعارات الرسائل"),sound=btn("🔊 صوت النقر"),pic=btn("🖼 الصورة الشخصية"),save=btn("حفظ"),back=btn("رجوع");EditText name=field("الاسم الثلاثي"),year=field("المواليد");name.setText(prefs.getString(NAME,""));year.setText(prefs.getString(YEAR,""));year.setInputType(InputType.TYPE_CLASS_NUMBER);content.addView(n,lp(-1,76,6));content.addView(sound,lp(-1,76,6));content.addView(tv("الاسم الشخصي",14,gold()));content.addView(name,lp(-1,64,8));content.addView(tv("المواليد",14,gold()));content.addView(year,lp(-1,64,8));content.addView(tv("المعرف الشخصي تلقائيًا",14,gold()));content.addView(tv(prefs.getString(ID,""),18,Color.WHITE),lp(-1,-2,8));content.addView(pic,lp(-1,76,6));content.addView(save,lp(-1,76,6));content.addView(back,lp(-1,76,8));n.setOnClickListener(v->{click();requestNotifications();startMessageService();toast("إشعارات الرسائل مفعلة");});sound.setOnClickListener(v->{click();prefs.edit().putBoolean("click_sound",!prefs.getBoolean("click_sound",true)).apply();toast("تم تغيير صوت النقر");});pic.setOnClickListener(v->{click();pickProfile();});save.setOnClickListener(v->{click();prefs.edit().putString(NAME,name.getText().toString().trim()).putString(YEAR,year.getText().toString().trim()).apply();toast("تم حفظ الإعدادات ✓");});back.setOnClickListener(v->{click();home();});}
 private void profileScreen(){base("المعلومات الشخصية");ImageView av=new ImageView(this);av.setAdjustViewBounds(true);av.setImageDrawable(defaultAvatar());content.addView(av,new LinearLayout.LayoutParams(-1,260));loadAvatarInto(prefs.getString(ID,""),av);content.addView(tv("المعرف الشخصي\n"+prefs.getString(ID,""),18,gold()),lp(-1,-2,8));content.addView(tv("الاسم الثلاثي\n"+prefs.getString(NAME,""),18,Color.WHITE),lp(-1,-2,8));content.addView(tv("المواليد\n"+prefs.getString(YEAR,""),18,Color.WHITE),lp(-1,-2,8));Button edit=btn("تغيير الصورة الشخصية"),b=btn("رجوع");content.addView(edit,lp(-1,76,8));content.addView(b,lp(-1,76,8));edit.setOnClickListener(v->pickProfile());b.setOnClickListener(v->home());}
 private void pickImage(){startActivityForResult(new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI),702);}
 private boolean isOwner(){return "Hatem_Hussin_Al_Haj_Ramadan1995".equals(prefs.getString(ID,""));}
 private void sendComplaint(){base("الشكاوى والتواصل مع المؤسس");TextView info=tv("اكتب شكواك أو رسالتك للمؤسس ثم اضغط إرسال.",18,Color.WHITE);info.setGravity(Gravity.CENTER);EditText box=field("اكتب الشكوى هنا…");box.setSingleLine(false);box.setMinHeight(dp(180));box.setGravity(Gravity.TOP|Gravity.RIGHT);Button send=btn("إرسال الشكوى"),back=btn("رجوع");content.addView(info,lp(-1,-2,12));content.addView(box,lp(-1,190,12));content.addView(send,lp(-1,76,8));content.addView(back,lp(-1,76,8));send.setOnClickListener(v->{click();String msg=box.getText().toString().trim();if(msg.length()<2){toast("اكتب الشكوى أولاً");return;}io.execute(()->{try{JSONObject q=new JSONObject();q.put("message",msg);HttpResult r=request("POST","/api/complaints",q.toString(),auth());h.post(()->toast(r.code>=200&&r.code<300?"تم إرسال الشكوى إلى المؤسس ✓":error(r)));}catch(Exception e){h.post(()->toast("تعذر إرسال الشكوى"));}});});back.setOnClickListener(v->{click();home();});}
 private void adminScreen(){startActivity(new Intent(this,AdminActivity.class));}private void pickProfile(){startActivityForResult(new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI),703);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null||d.getData()==null)return;try{String b64=compressImageToBase64(d.getData());if(b64==null)throw new Exception("image");if(r==703){showProgress("جاري رفع الصورة الشخصية…");uploadAvatar(b64,"image/jpeg");}else{pendingImageData=b64;pendingAudioData=null;pendingMime="image/jpeg";pendingMediaType=1;showImagePreview(b64);toast("الصورة جاهزة للإرسال — اضغط إرسال");}}catch(Exception e){dismissProgress();toast("تعذر قراءة الصورة");}}
 private String compressImageToBase64(Uri u)throws Exception{Bitmap src=BitmapFactory.decodeStream(getContentResolver().openInputStream(u));if(src==null)return null;int max=1280;float sc=Math.min(1f,max/(float)Math.max(src.getWidth(),src.getHeight()));Bitmap b=Bitmap.createScaledBitmap(src,Math.max(1,(int)(src.getWidth()*sc)),Math.max(1,(int)(src.getHeight()*sc)),true);ByteArrayOutputStream o=new ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,78,o);if(b!=src)b.recycle();if(src!=b)src.recycle();return Base64.getEncoder().encodeToString(o.toByteArray());}
 private void uploadAvatar(String data,String mime){io.execute(()->{try{JSONObject q=new JSONObject();q.put("imageBase64",data);q.put("mimeType",mime);HttpResult r=request("POST","/api/profile/avatar",q.toString(),auth());h.post(()->{dismissProgress();toast(r.code>=200&&r.code<300?"تم حفظ الصورة الشخصية ✓":"فشل حفظ الصورة");});}catch(Exception e){h.post(()->{dismissProgress();toast("فشل رفع الصورة");});}});}
 private void loadAvatarInto(String id,ImageView v){v.setImageDrawable(defaultAvatar());io.execute(()->{try{HttpResult r=request("GET","/api/users/"+URLEncoder.encode(id,"UTF-8")+"/avatar",null,auth());if(r.code==200){String d=new JSONObject(r.body).optString("imageBase64");byte[] z=Base64.getDecoder().decode(d);h.post(()->v.setImageBitmap(BitmapFactory.decodeByteArray(z,0,z.length)));}}catch(Exception ignored){}});}
 private void showImagePreview(String data){try{byte[] z=Base64.getDecoder().decode(data);Bitmap bm=BitmapFactory.decodeByteArray(z,0,z.length);if(input!=null){input.setCompoundDrawablesWithIntrinsicBounds(new BitmapDrawable(getResources(),bm),null,null,null);input.setHint("الصورة جاهزة للإرسال — اضغط إرسال");}}catch(Exception ignored){}}
 private void startRecording(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},701);return;}try{File f=new File(getCacheDir(),"wethaq_audio.m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(f.getAbsolutePath());recorder.prepare();recorder.start();recording=true;toast("جارٍ التسجيل… اضغط 🎙 لإرسال");}catch(Exception e){stopRecording(false);toast("تعذر تشغيل الميكروفون");}}
 private void stopRecording(boolean send){File f=new File(getCacheDir(),"wethaq_audio.m4a" );if(recorder!=null){try{recorder.stop();}catch(Exception ignored){}try{recorder.release();}catch(Exception ignored){}recorder=null;}recording=false;if(send&&f.exists()&&activeId!=null){showProgress("جاري تجهيز التسجيل الصوتي…");io.execute(()->{try{String data=Base64.getEncoder().encodeToString(readFile(f));h.post(()->{dismissProgress();pendingAudioData=data;pendingImageData=null;pendingMime="audio/mp4";pendingMediaType=2;input.setHint("التسجيل جاهز للإرسال — اضغط إرسال");});f.delete();}catch(Exception e){h.post(()->{dismissProgress();toast("فشل تجهيز التسجيل");});}});}}
 private byte[] readFile(File f)throws Exception{FileInputStream in=new FileInputStream(f);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);in.close();return o.toByteArray();}
 private void playAudio(String data){try{byte[] z=Base64.getDecoder().decode(data);File f=new File(getCacheDir(),"play.m4a");FileOutputStream o=new FileOutputStream(f);o.write(z);o.close();MediaPlayer p=new MediaPlayer();p.setDataSource(f.getAbsolutePath());p.setOnCompletionListener(x->{x.release();f.delete();});p.prepare();p.start();}catch(Exception e){toast("تعذر تشغيل الرسالة الصوتية");}}
 private void startVideoCall(){if(activeId==null||activeId.trim().isEmpty()){toast("معرف الطرف الآخر غير موجود");return;}try{Intent i=new Intent(this,VideoCallActivity.class);i.putExtra("target",activeId);i.putExtra("name",activeName==null?"مستخدم":activeName);i.putExtra("audioOnly",false);startActivity(i);}catch(Exception e){toast("تعذر فتح مكالمة الفيديو");}}private void startAudioCall(){if(activeId==null||activeId.trim().isEmpty()){toast("معرف الطرف الآخر غير موجود");return;}try{Intent i=new Intent(this,VideoCallActivity.class);i.putExtra("target",activeId);i.putExtra("name",activeName==null?"مستخدم":activeName);i.putExtra("audioOnly",true);startActivity(i);}catch(Exception e){toast("تعذر فتح المكالمة الصوتية");}}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("wethaq_messages","رسائل وثاق",NotificationManager.IMPORTANCE_HIGH);c.enableVibration(true);c.setSound(android.provider.Settings.System.DEFAULT_NOTIFICATION_URI,null);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private void requestNotifications(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},900);}
 private void pollInbox(){if(!hasToken())return;io.execute(()->{try{HttpResult r=request("GET","/api/messages/inbox",null,auth());if(r.code==200){JSONArray a=new JSONObject(r.body).optJSONArray("messages");if(a!=null&&a.length()>0){for(int k=0;k<a.length();k++){JSONObject z=a.optJSONObject(k);if(z!=null)addLocalContact(z.optString("sender_wethaq_id"),z.optString("sender_name","مستخدم"));}JSONObject m=a.optJSONObject(a.length()-1);long id=m.optLong("id");if(lastInboxId>0&&id>lastInboxId){String body=m.optString("body"),sender=m.optString("sender_name","مستخدم");h.post(()->{toneIncoming();notifyIncoming(sender+"\n"+(body.isEmpty()?"وسائط جديدة":body));});}lastInboxId=Math.max(lastInboxId,id);}}}catch(Exception ignored){}});}
 private void startPolling(){stopPolling();poller=()->{if(activeId!=null)loadMessages();pollInbox();if(hasToken())h.postDelayed(poller,2500);};h.postDelayed(poller,1200);}private void stopPolling(){if(poller!=null)h.removeCallbacks(poller);poller=null;}
 private void click(){if(!prefs.getBoolean("click_sound",true))return;try{ToneGenerator t=new ToneGenerator(AudioManager.STREAM_NOTIFICATION,70);t.startTone(ToneGenerator.TONE_PROP_BEEP,80);new Handler().postDelayed(t::release,120);}catch(Exception ignored){}}private void toneIncoming(){try{ToneGenerator t=new ToneGenerator(AudioManager.STREAM_NOTIFICATION,90);t.startTone(ToneGenerator.TONE_PROP_ACK,250);new Handler().postDelayed(t::release,300);}catch(Exception ignored){}}
 private void notifyIncoming(String text){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)return;Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"wethaq_messages"):new Notification.Builder(this);b.setSmallIcon(android.R.drawable.ic_dialog_email).setContentTitle("رسالة جديدة في وَثاق").setContentText(text).setAutoCancel(true);getSystemService(NotificationManager.class).notify(2001,b.build());}
 private JSONArray contacts(){try{return new JSONArray(prefs.getString(CONTACTS,"[]"));}catch(Exception e){return new JSONArray();}}private String deviceKey(){String k=prefs.getString("device_key","");if(k.length()>20)return k;k="wethaq-"+UUID.randomUUID();prefs.edit().putString("device_key",k).apply();return k;}private String auth(){return "Bearer "+prefs.getString(T,"");}
 private String error(HttpResult r){try{JSONObject o=new JSONObject(r.body);String x=o.optString("error");if("user_banned".equals(x)){String reason=o.optString("reason");String type=o.optString("ban_type");if("permanent".equals(type))return "تم طردك نهائيًا من تطبيق وَثاق من الإدارة. السبب: "+(reason.isEmpty()?"مخالفة شروط الاستخدام":reason);return "تم حظرك من الإدارة مؤقتًا. السبب: "+(reason.isEmpty()?"مخالفة شروط الاستخدام":reason);}if(!x.isEmpty())return x;}catch(Exception ignored){}return "HTTP "+r.code;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 private HttpResult request(String m,String path,String body,String authorization)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API+path).openConnection();c.setRequestMethod(m);c.setConnectTimeout(12000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");if(authorization!=null)c.setRequestProperty("Authorization",authorization);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");byte[] z=body.getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(z.length);try(OutputStream o=c.getOutputStream()){o.write(z);}}int code=c.getResponseCode();InputStream in=code>=200&&code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();if(in!=null){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);in.close();}c.disconnect();return new HttpResult(code,new String(out.toByteArray(),StandardCharsets.UTF_8));}
 private static final class HttpResult{final int code;final String body;HttpResult(int c,String b){code=c;body=b;}}
}
