package com.wethaq.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public final class PublicAdministrationActivity extends Activity{
 private static final String API="https://wethaq-backend-production.up.railway.app";private LinearLayout body;private TextView status;private String founderId="",founderName="حاتم حسين الحاج رمضان";
 private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private TextView t(String s,float z,int c){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);x.setGravity(Gravity.RIGHT);x.setPadding(dp(14),dp(12),dp(14),dp(12));return x;}
 private Button b(String s){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(17);x.setAllCaps(false);GradientDrawable d=new GradientDrawable();d.setColor(Color.rgb(28,28,32));d.setCornerRadius(dp(14));d.setStroke(dp(2),Color.rgb(212,175,55));x.setBackground(d);x.setMinHeight(dp(64));return x;}
 @Override public void onCreate(Bundle z){super.onCreate(z);shell();load();}
 private void shell(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(14),dp(14),dp(14),dp(14));r.setBackgroundColor(Color.BLACK);TextView h=t("👥 الإدارة — الهيكل الإداري الرسمي",23,Color.rgb(212,175,55));h.setGravity(Gravity.CENTER);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(h,new LinearLayout.LayoutParams(-1,dp(72)));status=t("⏳ جاري تحديث البيانات…",15,Color.LTGRAY);status.setGravity(Gravity.CENTER);r.addView(status,new LinearLayout.LayoutParams(-1,dp(48)));ScrollView s=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);s.addView(body);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));Button back=b("رجوع");r.addView(back,new LinearLayout.LayoutParams(-1,dp(64)));back.setOnClickListener(v->finish());setContentView(r);}
 private void load(){new Thread(()->{HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(API+"/api/public/administration").openConnection();c.setRequestMethod("GET");c.setConnectTimeout(8000);c.setReadTimeout(12000);int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();ByteArrayOutputStream o=new ByteArrayOutputStream();if(in!=null){byte[] a=new byte[4096];int n;while((n=in.read(a))!=-1)o.write(a,0,n);in.close();}String raw=new String(o.toByteArray(),StandardCharsets.UTF_8);runOnUiThread(()->{if(code>=200&&code<300){status.setText("🟢 البيانات محدثة");show(raw);}else status.setText("🔴 تعذر تحميل الهيكل");});}catch(Exception e){runOnUiThread(()->status.setText("🔴 تعذر الاتصال بالخادم"));}finally{if(c!=null)c.disconnect();}}).start();}
 private void show(String raw){try{JSONObject o=new JSONObject(raw);JSONObject fo=o.optJSONObject("founder");if(fo!=null){founderId=fo.optString("wethaq_id","");founderName=fo.optString("name",founderName);}body.removeAllViews();body.addView(card("💳 العضويات والمناصب — اشتراك سنوي لمدة سنة واحدة",true));JSONArray p=o.optJSONArray("pricing");if(p!=null)for(int i=0;i<p.length();i++){JSONObject x=p.getJSONObject(i);String label=x.optString("role_label"),price=x.optString("price_usd"),perm=x.optString("permission");if(perm.isEmpty()){String ban=x.optString("ban");perm="alert".equals(ban)?"تنبيه فقط":("temporary".equals(ban)?"حظر مؤقت + تنبيه":"حظر مؤقت أو نهائي + تنبيه");}body.addView(card(label+"\nالسعر: $"+price+" سنويًا\nصلاحية الإجراءات: "+perm,true));}body.addView(card("👑 مدير ومؤسس وثاق\n"+person(fo),false));body.addView(card("🏛 المدير التنفيذي\n"+person(o.optJSONObject("executive")),false));JSONObject d=o.optJSONObject("deputies");body.addView(card("🥇 النائب الأول\n"+person(d==null?null:d.optJSONObject("deputy1")),false));body.addView(card("🥈 النائب الثاني\n"+person(d==null?null:d.optJSONObject("deputy2")),false));body.addView(card("🥉 النائب الثالث\n"+person(d==null?null:d.optJSONObject("deputy3")),false));body.addView(card("🛡 المشرف\n"+person(o.optJSONObject("supervisor")),false));body.addView(card("👥 أعضاء الإدارة — حتى 10 خانات",true));JSONArray m=o.optJSONArray("members");for(int i=0;i<10;i++){JSONObject x=m!=null&&i<m.length()?m.optJSONObject(i):null;body.addView(card((i+1)+". "+(x==null?"غير معين":x.optString("name","غير معروف")),false));}JSONArray pm=o.optJSONArray("premium_members");body.addView(card("⭐ الأعضاء المميزون\n"+(pm==null?0:pm.length())+" عضو مسجل حاليًا",false));body.addView(card("📩 الاشتراك لا يمنح الصفة تلقائيًا؛ تفعيل المنصب يتم من خلال المؤسس أو الرتبة المخولة وفق حصص التعيين.\n\nيمكنك فتح محادثة مباشرة مع المؤسس لطلب المنصب واستكمال الاشتراك.",true));Button contact=b("💬 فتح المحادثة مع المؤسس");body.addView(contact,new LinearLayout.LayoutParams(-1,dp(68)));contact.setOnClickListener(v->openFounderChat());}catch(Exception e){status.setText("🔴 بيانات الإدارة غير صالحة");}}
 private String person(JSONObject x){if(x==null)return"غير معين";return x.optString("name","غير معروف")+"\nمعرف وَثاق: "+x.optString("wethaq_id","");}
 private TextView card(String s,boolean emphasis){TextView x=t(s,emphasis?17:16,Color.WHITE);GradientDrawable d=new GradientDrawable();d.setColor(emphasis?Color.rgb(40,32,10):Color.rgb(23,23,27));d.setCornerRadius(dp(16));d.setStroke(dp(2),emphasis?Color.rgb(212,175,55):Color.rgb(65,65,72));x.setBackground(d);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(10);x.setLayoutParams(p);return x;}
 private void openFounderChat(){String token=getSharedPreferences("wethaq",MODE_PRIVATE).getString("token","");if(token.length()<10){new AlertDialog.Builder(this).setTitle("تسجيل الدخول مطلوب").setMessage("سجل الدخول أولًا لفتح المحادثة مع المؤسس.").setPositiveButton("حسنًا",null).show();return;}if(founderId==null||founderId.isEmpty()){new AlertDialog.Builder(this).setTitle("المؤسس غير متاح").setMessage("تعذر العثور على معرف المؤسس حاليًا.").setPositiveButton("حسنًا",null).show();return;}Intent i=new Intent(this,ProfessionalConversationActivity.class);i.putExtra("notification_target",founderId);i.putExtra("notification_name",founderName);startActivity(i);}
}
